import type { BlogArticle } from "./types";

/**
 * Articles de la catégorie "evenements-lyon", intégrés depuis le lot
 * "Kdrive — Articles blog octobre 2026" (8 articles, README-INTEGRATION.md).
 * Les liens internes vers des pages non encore créées sur le site
 * (VTC Centre de Congrès Lyon, VTC Eurexpo Lyon, VTC LDLC Arena) ont été
 * retirés du maillage pour ne créer aucun lien mort — à réintégrer si ces
 * pages sont créées. Dates, lieux et chiffres proviennent du lot fourni et
 * de sa source officielle (`sources`) ; non re-vérifiés en direct dans le
 * cadre de cette intégration.
 */
export const blogArticlesEvenementsLyon: BlogArticle[] = [
  {
    slug: "vtc-patrimonia-lyon",
    categorySlug: "evenements-lyon",
    title: "VTC Patrimonia Lyon 2026 | Chauffeur privé Kdrive",
    metaDescription: "Réservez votre VTC pour Patrimonia Lyon 2026 : aéroport, gares, hôtels et Centre de Congrès avec un chauffeur privé Kdrive.",
    h1: "VTC Patrimonia Lyon 2026 : organisez vos déplacements professionnels",
    excerpt: "La Convention Patrimonia revient à Lyon les 30 septembre et 1er octobre 2026. Ce rendez-vous réunit les professionnels du conseil patrimonial, de la gestion d'actifs, de la banque privée, de l'assurance et de l'investissement.",
    publishedAt: "2026-09-23",
    updatedAt: "2026-09-23",
    eventStartDate: "2026-09-30",
    eventEndDate: "2026-10-01",
    eventLocation: "Centre de Congrès de Lyon (Cité Internationale)",
    status: "a-venir",
    heroImage: "/images/corporate.jpg",
    heroImageAlt: "Chauffeur privé Kdrive pour la convention Patrimonia à Lyon",
    body: [
      { type: "paragraph", text: "La Convention Patrimonia revient à Lyon les 30 septembre et 1er octobre 2026. Ce rendez-vous réunit les professionnels du conseil patrimonial, de la gestion d’actifs, de la banque privée, de l’assurance et de l’investissement. Pour de nombreux participants, le séjour lyonnais ne se limite pas au salon : arrivée par avion ou TGV, hôtel, rendez-vous, déjeuners d’affaires et retour vers la gare ou l’aéroport s’enchaînent sur deux journées très denses." },
      { type: "paragraph", text: "Avec Kdrive, l’objectif est de réserver à l’avance les trajets les plus sensibles afin d’éviter de chercher une solution de transport au dernier moment. La prise en charge peut être prévue depuis Lyon-Saint-Exupéry, la gare Part-Dieu, la gare Perrache, un hôtel ou une adresse professionnelle de la métropole." },
      { type: "heading", text: "Patrimonia au Centre de Congrès de Lyon" },
      { type: "paragraph", text: "Patrimonia se tient au Centre de Congrès de Lyon, dans la Cité Internationale. Ce secteur du 6e arrondissement concentre hôtels, restaurants, espaces de réception et lieux de rendez-vous professionnels. Il est donc fréquent qu’un participant arrive à Lyon la veille, rejoigne son hôtel, puis se rende au Centre de Congrès tôt le lendemain." },
      { type: "paragraph", text: "Pour ce type de séjour, un chauffeur privé réservé à l’avance apporte surtout de la lisibilité : heure de prise en charge connue, trajet identifié et contact direct en cas de changement de programme." },
      { type: "heading", text: "Transfert Lyon-Saint-Exupéry vers Patrimonia" },
      { type: "paragraph", text: "Pour les visiteurs arrivant en avion, Kdrive peut organiser un transfert entre l’aéroport Lyon-Saint-Exupéry et la Cité Internationale. Selon l’horaire d’arrivée, le trajet peut conduire directement au Centre de Congrès, à l’hôtel ou à un premier rendez-vous." },
      { type: "paragraph", text: "Lors de la réservation, il est utile de transmettre le numéro de vol, le nombre de passagers et le volume de bagages. Ces informations permettent d’anticiper la prise en charge et de choisir une catégorie de véhicule adaptée." },
      { type: "heading", text: "Gare Part-Dieu, Perrache et hôtels : préparer les trajets clés" },
      { type: "paragraph", text: "Les participants venant de Paris, Genève, Marseille ou d’autres grandes villes arrivent souvent par Lyon Part-Dieu ou Lyon Perrache. Un transfert gare vers Patrimonia peut être planifié de la même manière qu’un transfert aéroport." },
      { type: "paragraph", text: "Le retour mérite aussi d’être anticipé. Lorsque plusieurs centaines de visiteurs quittent un événement en même temps, réserver l’heure de départ vers la gare ou l’aéroport limite l’incertitude et permet de conserver une marge adaptée au train ou au vol." },
      { type: "heading", text: "Mise à disposition pour dirigeants et professionnels du patrimoine" },
      { type: "paragraph", text: "Patrimonia génère de nombreux rendez-vous parallèles : rencontres clients, déjeuners, cocktails, dîners et réunions privées. Pour un dirigeant ou une équipe ayant plusieurs étapes dans la même journée, une mise à disposition peut être plus cohérente qu’une succession de courses commandées séparément." },
      { type: "paragraph", text: "Un programme type peut par exemple enchaîner hôtel, Centre de Congrès, rendez-vous en Presqu’île, restaurant puis retour à l’hôtel. L’organisation est alors construite autour du planning communiqué au moment de la réservation." },
      { type: "heading", text: "Pourquoi réserver son VTC avant Patrimonia ?" },
      { type: "paragraph", text: "Les créneaux à surveiller sont l’arrivée des participants la veille, le début de matinée, la sortie des conférences et les départs en fin de Convention. Pour un trajet lié à un train, un vol ou un rendez-vous à heure fixe, la réservation préalable est particulièrement pertinente." },
      { type: "paragraph", text: "Kdrive confirme la disponibilité et le tarif selon le trajet demandé. Le client garde un contact direct et peut préparer plusieurs déplacements en une seule fois." },
      { type: "heading", text: "Réserver votre chauffeur pour Patrimonia Lyon" },
      { type: "paragraph", text: "Vous participez à Patrimonia comme visiteur, exposant, intervenant ou dirigeant ? Préparez vos transferts entre l’aéroport, les gares, votre hôtel et le Centre de Congrès avec Kdrive. Une demande de réservation peut être envoyée en ligne et la disponibilité est ensuite confirmée directement." },
      { type: "heading", text: "Quel véhicule prévoir pour Patrimonia ?" },
      { type: "paragraph", text: "Pour un déplacement individuel ou en duo, une berline convient généralement à un séjour professionnel classique. Pour trois personnes ou davantage, ou lorsque plusieurs valises cabine et bagages sont prévus, il est préférable d’indiquer précisément le volume transporté dès la demande. Une catégorie plus spacieuse peut alors être proposée selon les disponibilités." },
      { type: "paragraph", text: "Pour une équipe d’entreprise, l’intérêt n’est pas seulement le confort : voyager ensemble facilite aussi l’arrivée au même horaire et limite les réservations séparées. Le choix du véhicule doit donc être fait en fonction du nombre de passagers, des bagages et du niveau de confort recherché." },
      { type: "heading", text: "Où loger et comment organiser les trajets ?" },
      { type: "paragraph", text: "La Cité Internationale est naturellement pratique pour les participants souhaitant rester à proximité immédiate du Centre de Congrès. D’autres visiteurs préfèrent Part-Dieu, les Brotteaux, la Presqu’île ou Bellecour afin de combiner le salon avec des rendez-vous et des dîners en centre-ville." },
      { type: "paragraph", text: "Quel que soit le quartier choisi, l’approche la plus simple consiste à préparer les trajets fixes avant le séjour : arrivée gare ou aéroport, transfert vers l’hôtel, départ matinal vers Patrimonia et retour final. Les déplacements intermédiaires peuvent ensuite être ajoutés selon le programme." },
      { type: "heading", text: "Bien préparer votre réservation Kdrive" },
      { type: "paragraph", text: "Pour accélérer la confirmation, transmettez l’adresse de départ, la destination, la date, l’heure souhaitée, le nombre de passagers, les bagages et, lorsqu’il s’agit d’un vol ou d’un train, la référence utile. Si plusieurs courses sont nécessaires, regroupez-les dans une même demande avec les horaires prévus." },
      { type: "paragraph", text: "Le tarif et la disponibilité sont confirmés avant la course. Pour un événement professionnel, il est conseillé de réserver le plus tôt possible les créneaux liés à une arrivée, un départ ou un rendez-vous à heure fixe." },
      { type: "heading", text: "Exemple d’organisation d’une journée Patrimonia" },
      { type: "paragraph", text: "Un scénario fréquent consiste à partir de l’hôtel vers 8 h, rejoindre le Centre de Congrès, prévoir un transfert en milieu ou fin de journée vers un rendez-vous en Presqu’île, puis terminer par un dîner avant le retour à l’hôtel. Pour le dernier jour, le trajet Centre de Congrès → Part-Dieu ou Lyon-Saint-Exupéry peut être réservé dès le matin afin de sécuriser le départ." },
    ],
    faq: [
      { q: "Où se déroule Patrimonia 2026?", a: "Au Centre de Congrès de Lyon, dans la Cité Internationale." },
      { q: "Peut-on réserver un VTC depuis Lyon-Saint-Exupéry?", a: "Oui, pour rejoindre le Centre de Congrès, un hôtel ou une autre adresse lyonnaise." },
      { q: "Kdrive peut-il venir à la gare Part-Dieu ou Perrache?", a: "Oui, une prise en charge peut être planifiée depuis les principales gares de Lyon." },
      { q: "Peut-on réserver plusieurs trajets pendant les deux jours?", a: "Oui. Selon le programme, plusieurs transferts ou une mise à disposition peuvent être organisés." },
      { q: "Faut-il attendre d’être à Lyon pour réserver?", a: "Non. Pour les trajets contraints par un horaire de vol, de train ou de rendez-vous, il est préférable d’anticiper." },
    ],
    internalLinks: [
      { href: "/reserver", label: "Réserver votre VTC" },
      { href: "/transfert-aeroport", label: "transfert aéroport Lyon-Saint-Exupéry" },
      { href: "/transfert-gare", label: "transfert gare à Lyon" },
      { href: "/chauffeur-entreprise", label: "chauffeur privé entreprise" },
      { href: "/mise-a-disposition", label: "mise à disposition avec chauffeur" },
    ],
    sources: ["https://www.patrimonia.fr/"],
    annualUpdate: { keepSlug: true, note: "Mettre à jour chaque année le millésime dans le Title/H1, les dates, horaires, lieu si changement, chiffres de fréquentation, programme et informations d'accès. Conserver l'URL evergreen et le maillage si les services Kdrive restent identiques." },
  },
  {
    slug: "vtc-preventica-lyon",
    categorySlug: "evenements-lyon",
    title: "VTC Préventica Lyon 2026 | Transfert Eurexpo Kdrive",
    metaDescription: "Préventica Lyon 2026 à Eurexpo : réservez votre VTC depuis l'aéroport, les gares, votre hôtel ou Lyon avec Kdrive.",
    h1: "VTC Préventica Lyon 2026 : réservez votre transfert vers Eurexpo",
    excerpt: "Préventica Lyon se déroule du 6 au 8 octobre 2026 à Eurexpo. L'événement est consacré à l'innovation en santé, sécurité et qualité de vie au travail et annonce 550 exposants, 180 conférences, 750 experts et 15 000 participants attendus.",
    publishedAt: "2026-09-23",
    updatedAt: "2026-09-23",
    eventStartDate: "2026-10-06",
    eventEndDate: "2026-10-08",
    eventLocation: "Eurexpo Lyon (Chassieu)",
    status: "a-venir",
    heroImage: "/images/service-affaires.jpg",
    heroImageAlt: "Chauffeur privé Kdrive pour le salon Préventica à Eurexpo Lyon",
    body: [
      { type: "paragraph", text: "Préventica Lyon se déroule du 6 au 8 octobre 2026 à Eurexpo. L’événement est consacré à l’innovation en santé, sécurité et qualité de vie au travail et annonce 550 exposants, 180 conférences, 750 experts et 15 000 participants attendus. Pour les visiteurs professionnels, l’enjeu logistique est simple : rejoindre Chassieu à l’heure, puis organiser les trajets entre Eurexpo, l’hôtel, les gares, l’aéroport et les éventuels rendez-vous en ville." },
      { type: "paragraph", text: "Kdrive permet de réserver un chauffeur à l’avance pour ces déplacements. La prise en charge peut être organisée depuis Lyon-Saint-Exupéry, Part-Dieu, Perrache, le centre de Lyon ou un hôtel de l’est lyonnais." },
      { type: "heading", text: "Pourquoi Eurexpo demande davantage d’anticipation" },
      { type: "paragraph", text: "Eurexpo se situe à Chassieu, à l’est de Lyon. Pour un participant logé en Presqu’île, à Part-Dieu ou dans le 6e arrondissement, le trajet fait donc partie intégrante de la journée. Aux heures d’ouverture et de fermeture d’un salon majeur, la circulation et la concentration des visiteurs peuvent allonger les temps de déplacement." },
      { type: "paragraph", text: "La réservation d’un VTC ne supprime pas les contraintes de circulation, mais elle permet de fixer une heure de départ, un point de prise en charge et un contact direct, ce qui simplifie le planning professionnel." },
      { type: "heading", text: "Transfert aéroport Lyon-Saint-Exupéry vers Préventica" },
      { type: "paragraph", text: "Les visiteurs arrivant en avion peuvent réserver un trajet entre Lyon-Saint-Exupéry et Eurexpo. Selon le programme, la destination peut aussi être un hôtel, un restaurant ou une adresse professionnelle avant de rejoindre le salon." },
      { type: "paragraph", text: "Pour une équipe ou un exposant avec plusieurs bagages, il est recommandé de préciser le nombre de passagers et le volume transporté. Kdrive peut ainsi confirmer la catégorie de véhicule la plus cohérente avec la demande." },
      { type: "heading", text: "Gare Part-Dieu et gare Perrache : rejoindre Eurexpo sans perdre de temps" },
      { type: "paragraph", text: "Préventica attire des participants venant de toute la France. Les arrivées TGV à Part-Dieu ou Perrache peuvent être suivies d’un transfert direct vers Eurexpo. Cela évite d’ajouter des correspondances à une journée déjà chargée." },
      { type: "paragraph", text: "Le même principe s’applique au retour : lorsqu’un train est prévu peu après la fermeture du salon, mieux vaut définir l’heure de prise en charge avant la journée plutôt que de chercher une solution au moment du départ." },
      { type: "heading", text: "Mise à disposition pour exposants, dirigeants et délégations" },
      { type: "paragraph", text: "Préventica est un salon B2B : certains participants doivent enchaîner conférences, rendez-vous clients, visite d’un site, déjeuner ou dîner d’affaires. Dans ce cas, une mise à disposition peut mieux correspondre au besoin qu’un simple aller-retour vers Eurexpo." },
      { type: "paragraph", text: "Le chauffeur peut être intégré à un programme de déplacements communiqué en amont. Cette formule est particulièrement pertinente pour les dirigeants, intervenants, équipes exposantes ou petites délégations dont les horaires sont serrés." },
      { type: "heading", text: "Quand réserver son VTC pour Préventica ?" },
      { type: "paragraph", text: "Les créneaux les plus sensibles se concentrent généralement le matin avant l’ouverture, en fin d’après-midi et le dernier jour pour les retours vers les gares ou l’aéroport. Les exposants qui doivent être sur place tôt ont également intérêt à fixer leur prise en charge la veille." },
      { type: "paragraph", text: "Pour un trajet lié à un vol ou à un train, prévoyez toujours une marge adaptée à la circulation et aux formalités de départ." },
      { type: "heading", text: "Réserver votre chauffeur pour Préventica" },
      { type: "paragraph", text: "Vous venez à Préventica comme visiteur, exposant, intervenant ou membre d’une équipe ? Kdrive peut organiser vos transferts entre Lyon-Saint-Exupéry, les gares, votre hôtel, Eurexpo et vos rendez-vous professionnels. Envoyez votre demande de trajet en ligne pour vérifier la disponibilité." },
      { type: "heading", text: "Quel véhicule choisir pour un salon à Eurexpo ?" },
      { type: "paragraph", text: "Un visiteur seul avec un bagage n’a pas les mêmes besoins qu’une équipe exposante. Pour plusieurs collaborateurs, des valises nombreuses ou du petit matériel professionnel, indiquez le volume réel lors de la demande. Cela permet de vérifier qu’une berline suffit ou qu’une catégorie plus spacieuse doit être prévue." },
      { type: "paragraph", text: "La capacité doit être validée avant le trajet, en particulier lorsque la prise en charge se fait directement à l’aéroport ou à la gare avec l’ensemble des bagages du séjour." },
      { type: "heading", text: "Hôtel à Lyon ou près d’Eurexpo : quel impact sur les trajets ?" },
      { type: "paragraph", text: "Un hôtel proche de Chassieu réduit les déplacements matinaux vers le salon, tandis qu’un hébergement à Part-Dieu, dans le centre ou dans le 6e arrondissement facilite les dîners et rendez-vous en ville. Le bon choix dépend donc du programme professionnel autant que du salon lui-même." },
      { type: "paragraph", text: "Si plusieurs collaborateurs logent au même endroit, il peut être utile de grouper leur prise en charge. Pour les visiteurs logés dans différents hôtels, mieux vaut au contraire fixer des points et horaires précis afin d’éviter les détours." },
      { type: "heading", text: "Conseils pour une réservation fluide pendant Préventica" },
      { type: "paragraph", text: "Communiquez les heures d’ouverture auxquelles vous devez réellement être présent, pas seulement l’horaire officiel du salon. Un exposant ou un intervenant peut devoir arriver plus tôt. Ajoutez également l’heure du train ou du vol retour afin de calculer une marge suffisante." },
      { type: "paragraph", text: "Enfin, si votre programme comporte un dîner ou un rendez-vous après Eurexpo, ajoutez cette étape dès le départ : le trajet de fin de journée peut alors être pensé comme un enchaînement plutôt que comme une nouvelle réservation improvisée." },
      { type: "heading", text: "Exemple de parcours pendant Préventica" },
      { type: "paragraph", text: "Une équipe peut être prise en charge à son hôtel à Part-Dieu, rejoindre Eurexpo pour l’ouverture, repartir en fin d’après-midi vers un rendez-vous à Lyon puis retourner à l’hôtel. Le dernier jour, le trajet peut se terminer directement à Lyon-Saint-Exupéry ou à la gare." },
    ],
    faq: [
      { q: "Où se déroule Préventica Lyon 2026?", a: "À Eurexpo Lyon, à Chassieu." },
      { q: "Peut-on réserver un VTC depuis l’aéroport?", a: "Oui, vers Eurexpo, votre hôtel ou toute autre adresse convenue." },
      { q: "Kdrive dessert-il Part-Dieu et Perrache?", a: "Oui, les transferts depuis les gares peuvent être réservés à l’avance." },
      { q: "Peut-on transporter plusieurs collaborateurs?", a: "Oui. Le nombre de passagers et les bagages doivent être indiqués lors de la demande." },
      { q: "Une mise à disposition est-elle possible pendant le salon?", a: "Oui, lorsque plusieurs déplacements sont prévus dans la même journée." },
    ],
    internalLinks: [
      { href: "/reserver", label: "Réserver un VTC" },
      { href: "/transfert-aeroport", label: "transfert aéroport Lyon-Saint-Exupéry" },
      { href: "/transfert-gare", label: "transfert gare à Lyon" },
      { href: "/chauffeur-entreprise", label: "chauffeur privé entreprise" },
      { href: "/mise-a-disposition", label: "mise à disposition avec chauffeur" },
    ],
    sources: ["https://www.preventica.com/salon/lyon-2026/evenements"],
    annualUpdate: { keepSlug: true, note: "Mettre à jour chaque année le millésime dans le Title/H1, les dates, horaires, lieu si changement, chiffres de fréquentation, programme et informations d'accès. Conserver l'URL evergreen et le maillage si les services Kdrive restent identiques." },
  },
  {
    slug: "vtc-congres-sfm-lyon",
    categorySlug: "evenements-lyon",
    title: "VTC Congrès SFM Lyon 2026 | Chauffeur privé Kdrive",
    metaDescription: "Microbes 2026, congrès SFM à Lyon : réservez votre VTC vers le Centre de Congrès depuis l'aéroport, les gares ou votre hôtel.",
    h1: "VTC Congrès SFM Lyon 2026 : vos transferts pour Microbes 2026",
    excerpt: "Microbes 2026, le 21e Congrès national de la Société Française de Microbiologie, se tient du 7 au 9 octobre 2026 au Centre de Congrès de Lyon. Le programme réunit microbiologistes, cliniciens, chercheurs, jeunes scientifiques et partenaires.",
    publishedAt: "2026-09-23",
    updatedAt: "2026-09-23",
    eventStartDate: "2026-10-07",
    eventEndDate: "2026-10-09",
    eventLocation: "Centre de Congrès de Lyon (Cité Internationale)",
    status: "a-venir",
    heroImage: "/images/corporate.jpg",
    heroImageAlt: "Chauffeur privé Kdrive pour le congrès SFM Microbes 2026 à Lyon",
    body: [
      { type: "paragraph", text: "Microbes 2026, le 21e Congrès national de la Société Française de Microbiologie, se tient du 7 au 9 octobre 2026 au Centre de Congrès de Lyon. Le programme réunit microbiologistes, cliniciens, chercheurs, jeunes scientifiques et partenaires autour de nombreuses thématiques, de la microbiologie clinique à la virologie, en passant par les antimicrobiens, les biotechnologies et la modélisation du risque." },
      { type: "paragraph", text: "Pour un congrès de plusieurs jours, la mobilité ne se limite pas à l’aller-retour quotidien. Arrivée à Lyon, transfert vers l’hôtel, accueil au Centre de Congrès, soirées scientifiques, repas et retour vers la gare ou l’aéroport doivent souvent être coordonnés." },
      { type: "heading", text: "Rejoindre le Centre de Congrès de Lyon" },
      { type: "paragraph", text: "Le Centre de Congrès se trouve dans la Cité Internationale, dans le 6e arrondissement. Pour un congressiste hébergé à proximité, les déplacements peuvent être courts. Pour ceux qui logent à Part-Dieu, en Presqu’île, à Perrache ou dans un autre quartier, réserver un chauffeur permet surtout de sécuriser les trajets associés à des horaires de session précis." },
      { type: "paragraph", text: "Kdrive peut assurer une prise en charge à l’hôtel, à une gare ou à l’aéroport et conduire directement au lieu du congrès." },
      { type: "heading", text: "Transfert depuis Lyon-Saint-Exupéry" },
      { type: "paragraph", text: "Les participants arrivant en avion peuvent programmer leur trajet avant le départ. Il suffit de transmettre les informations de vol, l’horaire et la destination souhaitée : hôtel, Centre de Congrès ou autre adresse lyonnaise." },
      { type: "paragraph", text: "Cette préparation est particulièrement utile pour les intervenants, les participants internationaux ou les personnes voyageant avec du matériel, des posters ou plusieurs bagages." },
      { type: "heading", text: "Arrivée en TGV : Part-Dieu et Perrache" },
      { type: "paragraph", text: "Lyon Part-Dieu et Lyon Perrache accueillent de nombreux congressistes venus en train. Une prise en charge réservée à l’avance permet de rejoindre directement la Cité Internationale ou l’hôtel sans réorganiser le trajet à l’arrivée." },
      { type: "paragraph", text: "Pour le départ, le même principe s’applique : fixer l’heure de prise en charge selon le dernier atelier, le temps de trajet et l’heure du train." },
      { type: "heading", text: "Un chauffeur pour les temps forts du congrès" },
      { type: "paragraph", text: "Le programme de Microbes 2026 comprend des sessions scientifiques, des symposiums, des temps de networking et des moments conviviaux. Certains participants doivent également rencontrer des partenaires, visiter un laboratoire ou se rendre à un dîner professionnel." },
      { type: "paragraph", text: "Dans ce cas, une mise à disposition avec plusieurs arrêts peut simplifier la journée et éviter de réserver chaque déplacement séparément." },
      { type: "heading", text: "Réserver un VTC pour Microbes 2026" },
      { type: "paragraph", text: "Pour un séjour scientifique à Lyon, anticipez les trajets soumis à un horaire fixe : arrivée, première session, dîner, gare ou aéroport. Kdrive vous permet d’envoyer votre demande en ligne et de confirmer ensuite la disponibilité et le tarif." },
      { type: "heading", text: "Quel véhicule pour un congrès scientifique ?" },
      { type: "paragraph", text: "Pour un congressiste seul, une berline est généralement suffisante. Pour une équipe de laboratoire, plusieurs intervenants ou des voyageurs avec posters, valises et matériel de présentation, il est préférable de signaler les dimensions et le nombre de bagages au moment de réserver." },
      { type: "paragraph", text: "Cette précision évite de sous-estimer la place nécessaire, notamment lors d’une arrivée directement depuis Lyon-Saint-Exupéry ou une gare TGV." },
      { type: "heading", text: "Hébergement et déplacements pendant trois jours" },
      { type: "paragraph", text: "Un hôtel à la Cité Internationale limite les trajets vers le congrès, mais de nombreux participants choisissent aussi Part-Dieu, les Brotteaux, la Presqu’île ou d’autres quartiers de Lyon. Dans ce cas, les départs du matin doivent être prévus en fonction du premier créneau scientifique et de la circulation." },
      { type: "paragraph", text: "Pour un séjour de trois jours, il peut être utile de réserver en priorité l’arrivée, le premier matin et le départ. Les autres trajets peuvent ensuite être ajoutés selon les sessions et les événements du programme." },
      { type: "heading", text: "Préparer une prise en charge sans stress" },
      { type: "paragraph", text: "Indiquez l’horaire précis de la session ou du train plutôt qu’une simple plage approximative. Pour l’aéroport, ajoutez le numéro de vol. Pour les gares, précisez la gare et l’heure d’arrivée. Si plusieurs personnes voyagent ensemble, transmettez un contact principal joignable." },
      { type: "paragraph", text: "Une préparation claire est particulièrement utile pour les participants qui découvrent Lyon ou qui doivent intervenir à une heure précise devant un auditoire." },
      { type: "heading", text: "Exemple de parcours pour un congressiste" },
      { type: "paragraph", text: "Un chercheur arrivant la veille peut réserver Part-Dieu → hôtel, puis hôtel → Centre de Congrès le premier matin. Une soirée scientifique ou un dîner peut nécessiter un transfert supplémentaire, avant un dernier trajet vers la gare ou l’aéroport le 9 octobre." },
    ],
    faq: [
      { q: "Quand a lieu Microbes 2026?", a: "Du 7 au 9 octobre 2026." },
      { q: "Où se déroule le congrès?", a: "Au Centre de Congrès de Lyon." },
      { q: "Peut-on réserver depuis Lyon-Saint-Exupéry?", a: "Oui, vers le congrès, l’hôtel ou toute adresse indiquée." },
      { q: "Kdrive prend-il en charge les congressistes à Part-Dieu?", a: "Oui, sur réservation." },
      { q: "Une facture professionnelle peut-elle être demandée?", a: "Les informations nécessaires peuvent être précisées lors de la demande de trajet." },
    ],
    internalLinks: [
      { href: "/reserver", label: "Réserver un VTC" },
      { href: "/transfert-aeroport", label: "transfert aéroport" },
      { href: "/transfert-gare", label: "transfert gare" },
      { href: "/chauffeur-entreprise", label: "chauffeur entreprise" },
      { href: "/mise-a-disposition", label: "mise à disposition" },
    ],
    sources: ["https://www.alphavisa.com/sfm/2026/fr/"],
    annualUpdate: { keepSlug: true, note: "Mettre à jour chaque année le millésime dans le Title/H1, les dates, horaires, lieu si changement, chiffres de fréquentation, programme et informations d'accès. Conserver l'URL evergreen et le maillage si les services Kdrive restent identiques." },
  },
  {
    slug: "vtc-forum-franchise-lyon",
    categorySlug: "evenements-lyon",
    title: "VTC Forum Franchise Lyon 2026 | Chauffeur Kdrive",
    metaDescription: "Forum Franchise Lyon 2026 à la LDLC Arena : réservez votre VTC depuis l'aéroport, Part-Dieu, votre hôtel ou Lyon avec Kdrive.",
    h1: "VTC Forum Franchise Lyon 2026 : rejoindre la LDLC Arena",
    excerpt: "Le Forum Franchise Lyon revient le jeudi 8 octobre 2026. L'édition 2026 se déroule à la LDLC Arena, à Décines-Charpieu. Le salon rassemble enseignes, franchiseurs, candidats à la création d'entreprise, investisseurs et professionnels de l'accompagnement.",
    publishedAt: "2026-09-23",
    updatedAt: "2026-09-23",
    eventStartDate: "2026-10-08",
    eventEndDate: "2026-10-08",
    eventLocation: "LDLC Arena (Décines-Charpieu)",
    status: "a-venir",
    heroImage: "/images/service-affaires.jpg",
    heroImageAlt: "Chauffeur privé Kdrive pour le Forum Franchise Lyon à la LDLC Arena",
    body: [
      { type: "paragraph", text: "Le Forum Franchise Lyon revient le jeudi 8 octobre 2026. L’édition 2026 se déroule à la LDLC Arena, à Décines-Charpieu. Le salon rassemble enseignes, franchiseurs, candidats à la création d’entreprise, investisseurs et professionnels de l’accompagnement." },
      { type: "paragraph", text: "Comme l’événement se concentre sur une seule journée, les horaires d’arrivée et de départ ont une importance particulière. Un participant arrivant en TGV ou en avion le matin doit pouvoir rejoindre rapidement l’Arena, tandis qu’un exposant peut avoir besoin d’une prise en charge plus tôt." },
      { type: "heading", text: "LDLC Arena : un lieu différent du centre de Lyon" },
      { type: "paragraph", text: "La LDLC Arena se situe à Décines-Charpieu, à l’est de l’agglomération. L’organisation indique une adresse au 5 avenue Simone Veil et un accès routier proche de l’aéroport Lyon-Saint-Exupéry. Pour un visiteur logé dans le centre de Lyon, la distance doit donc être intégrée au planning." },
      { type: "paragraph", text: "Kdrive peut organiser une prise en charge depuis l’hôtel, la gare ou l’aéroport et conduire directement à la LDLC Arena." },
      { type: "heading", text: "Transfert Lyon-Saint-Exupéry vers Forum Franchise" },
      { type: "paragraph", text: "Pour les dirigeants, représentants d’enseigne ou visiteurs arrivant en avion, le transfert depuis Lyon-Saint-Exupéry est l’un des trajets les plus naturels. La réservation préalable permet de prévoir le véhicule, l’heure et le point de rendez-vous avant l’arrivée." },
      { type: "paragraph", text: "Le retour vers l’aéroport peut également être planifié à l’avance, notamment si le vol décolle peu après la fermeture du salon." },
      { type: "heading", text: "Depuis Part-Dieu ou le centre de Lyon" },
      { type: "paragraph", text: "Les visiteurs venant en TGV peuvent réserver une prise en charge à Part-Dieu puis rejoindre directement Décines. Pour un séjour avec nuitée, Kdrive peut aussi assurer hôtel vers LDLC Arena puis retour en fin de journée." },
      { type: "paragraph", text: "Les participants qui enchaînent le salon avec un rendez-vous, un restaurant ou un dîner d’affaires peuvent intégrer plusieurs étapes à leur réservation." },
      { type: "heading", text: "Une solution adaptée aux franchiseurs et entrepreneurs" },
      { type: "paragraph", text: "Le Forum Franchise est un événement où les échanges peuvent s’enchaîner rapidement : rendez-vous avec une enseigne, entretien avec un partenaire, conférence puis rencontre informelle. Pour un dirigeant ou un exposant, le temps de déplacement doit rester prévisible." },
      { type: "paragraph", text: "Un chauffeur réservé peut être particulièrement utile lorsqu’un programme comporte plusieurs lieux ou lorsqu’une équipe doit repartir immédiatement vers une gare ou un aéroport." },
      { type: "heading", text: "Réserver votre chauffeur pour Forum Franchise" },
      { type: "paragraph", text: "Vous venez au Forum Franchise comme exposant, dirigeant ou porteur de projet ? Programmez votre trajet vers la LDLC Arena depuis Lyon-Saint-Exupéry, Part-Dieu, votre hôtel ou une autre adresse de la métropole avec Kdrive." },
      { type: "heading", text: "Quel véhicule choisir pour cette journée business ?" },
      { type: "paragraph", text: "Pour un dirigeant ou un porteur de projet seul, une berline répond généralement au besoin. Une équipe d’enseigne, plusieurs collaborateurs ou des voyageurs avec bagages peuvent nécessiter une catégorie plus spacieuse. Le nombre de personnes et de valises doit donc être communiqué dès la demande." },
      { type: "paragraph", text: "Comme l’événement ne dure qu’une journée, certains visiteurs repartent directement après le salon. Dans ce cas, garder les bagages avec soi et réserver un véhicule adapté peut simplifier l’enchaînement LDLC Arena vers gare ou aéroport." },
      { type: "heading", text: "Combiner salon, rendez-vous et dîner à Lyon" },
      { type: "paragraph", text: "Une journée au Forum Franchise peut se prolonger par un rendez-vous avec un partenaire, un dîner avec une enseigne ou une rencontre en centre-ville. La LDLC Arena étant située à Décines, mieux vaut intégrer ces étapes au planning plutôt que de raisonner uniquement en aller-retour hôtel–salon." },
      { type: "paragraph", text: "Une réservation comprenant plusieurs adresses permet de mieux anticiper le temps nécessaire entre Décines et le centre de Lyon." },
      { type: "heading", text: "Les informations à transmettre à Kdrive" },
      { type: "paragraph", text: "Préparez l’adresse exacte de prise en charge, l’horaire, le nombre de passagers, les bagages et l’heure limite à respecter pour l’arrivée. Pour un retour gare ou aéroport, indiquez aussi l’heure du départ prévu afin de conserver une marge adaptée." },
      { type: "paragraph", text: "Pour les exposants ou dirigeants ayant plusieurs mouvements dans la journée, regrouper les trajets dans une seule demande facilite l’organisation." },
      { type: "heading", text: "Exemple d’organisation sur une journée" },
      { type: "paragraph", text: "Un participant peut arriver à Part-Dieu le matin, rejoindre directement la LDLC Arena, passer la journée au Forum puis repartir vers l’aéroport ou un dîner dans le centre. Pour un exposant, la prise en charge peut commencer plus tôt et le retour se faire après le démontage ou une rencontre professionnelle." },
    ],
    faq: [
      { q: "Quand a lieu Forum Franchise Lyon 2026?", a: "Le jeudi 8 octobre 2026." },
      { q: "Où se déroule l’édition 2026?", a: "À la LDLC Arena, à Décines-Charpieu." },
      { q: "Peut-on réserver depuis Lyon-Saint-Exupéry?", a: "Oui." },
      { q: "Kdrive peut-il prendre en charge à Part-Dieu?", a: "Oui, sur réservation." },
      { q: "Peut-on réserver un retour à heure fixe?", a: "Oui, ce qui est recommandé lorsqu’un train ou un vol est prévu après le salon." },
    ],
    internalLinks: [
      { href: "/reserver", label: "Réserver un VTC" },
      { href: "/transfert-aeroport", label: "transfert aéroport" },
      { href: "/transfert-gare", label: "transfert gare" },
      { href: "/chauffeur-entreprise", label: "chauffeur privé entreprise" },
    ],
    sources: ["https://www.lyon-franchise.com/"],
    annualUpdate: { keepSlug: true, note: "Mettre à jour chaque année le millésime dans le Title/H1, les dates, horaires, lieu si changement, chiffres de fréquentation, programme et informations d'accès. Conserver l'URL evergreen et le maillage si les services Kdrive restent identiques." },
  },
  {
    slug: "vtc-mesures-solutions-expo-lyon",
    categorySlug: "evenements-lyon",
    title: "VTC Mesures Solutions Expo Lyon 2026 | Kdrive",
    metaDescription: "Mesures Solutions EXPO Lyon 2026 : réservez votre VTC vers la Cité des Congrès depuis l'aéroport, les gares ou votre hôtel.",
    h1: "VTC Mesures Solutions EXPO Lyon 2026 : vos déplacements professionnels",
    excerpt: "Mesures Solutions EXPO se tient les 14 et 15 octobre 2026 à la Cité des Congrès de Lyon. Organisé autour des métiers de la mesure et de la métrologie, le salon réunit industriels, laboratoires, ingénieurs, responsables techniques, experts qualité.",
    publishedAt: "2026-09-23",
    updatedAt: "2026-09-23",
    eventStartDate: "2026-10-14",
    eventEndDate: "2026-10-15",
    eventLocation: "Cité des Congrès de Lyon (Cité Internationale)",
    status: "a-venir",
    heroImage: "/images/corporate.jpg",
    heroImageAlt: "Chauffeur privé Kdrive pour Mesures Solutions EXPO à Lyon",
    body: [
      { type: "paragraph", text: "Mesures Solutions EXPO se tient les 14 et 15 octobre 2026 à la Cité des Congrès de Lyon. Organisé autour des métiers de la mesure et de la métrologie, le salon réunit industriels, laboratoires, ingénieurs, responsables techniques, experts qualité, écoles et acteurs du recrutement." },
      { type: "paragraph", text: "La précédente édition a accueilli plus de 2 000 participants. Pour les visiteurs et exposants venant d’une autre région, le séjour implique souvent plusieurs déplacements : gare ou aéroport, hôtel, salon, dîner professionnel puis retour." },
      { type: "heading", text: "Rejoindre la Cité des Congrès avec Kdrive" },
      { type: "paragraph", text: "Le Centre de Congrès de Lyon est situé dans la Cité Internationale. Kdrive peut assurer une prise en charge depuis Lyon-Saint-Exupéry, Part-Dieu, Perrache, un hôtel ou une entreprise de la métropole." },
      { type: "paragraph", text: "Pour un salon B2B de deux jours, la réservation préalable permet surtout d’organiser les créneaux importants et de réduire les incertitudes entre deux rendez-vous." },
      { type: "heading", text: "Transfert aéroport pour exposants et visiteurs" },
      { type: "paragraph", text: "Les professionnels arrivant à Lyon-Saint-Exupéry peuvent réserver un transfert direct vers la Cité Internationale ou vers leur hôtel. Si le voyage comprend du matériel de démonstration ou plusieurs bagages, ces éléments doivent être précisés lors de la demande." },
      { type: "paragraph", text: "Un trajet retour peut également être programmé à l’avance en tenant compte de l’heure de fin de salon et de la marge nécessaire avant le vol." },
      { type: "heading", text: "Part-Dieu, Perrache et trajets professionnels" },
      { type: "paragraph", text: "La gare Part-Dieu est un point d’arrivée fréquent pour les visiteurs venant de Paris, Grenoble, Genève ou Marseille. Perrache reste également utile pour certains itinéraires. Une prise en charge directe évite de recomposer le trajet avec plusieurs correspondances lorsque le planning est serré." },
      { type: "paragraph", text: "Pour les équipes qui doivent également visiter un site industriel, rencontrer un client ou dîner en ville, une mise à disposition peut être envisagée." },
      { type: "heading", text: "Un service pensé pour les profils techniques et les entreprises" },
      { type: "paragraph", text: "Mesures Solutions EXPO accueille une forte proportion de cadres, ingénieurs et responsables de service. Le besoin de transport est donc souvent lié à des contraintes de rendez-vous et de ponctualité plus qu’à une simple visite de loisirs." },
      { type: "paragraph", text: "Kdrive peut centraliser plusieurs trajets et proposer une organisation adaptée à une personne seule, une petite équipe ou un groupe avec bagages." },
      { type: "heading", text: "Réserver un VTC pour Mesures Solutions EXPO" },
      { type: "paragraph", text: "Préparez votre déplacement professionnel avant le salon : arrivée à Lyon, transfert vers l’hôtel ou la Cité Internationale, déplacements de soirée et retour vers la gare ou l’aéroport. Kdrive confirme ensuite la disponibilité et le tarif de votre demande." },
      { type: "heading", text: "Quel véhicule pour une équipe technique ou un exposant ?" },
      { type: "paragraph", text: "Une berline peut convenir à un ou deux visiteurs avec peu de bagages. Pour une équipe technique, plusieurs valises, des catalogues ou du petit matériel de présentation, il faut vérifier la capacité avant confirmation. Une catégorie plus grande peut être plus adaptée." },
      { type: "paragraph", text: "Cette préparation est importante lorsque les voyageurs arrivent directement d’un train ou d’un vol et rejoignent le salon sans passer par leur hôtel." },
      { type: "heading", text: "Choisir son hôtel en fonction du programme" },
      { type: "paragraph", text: "Un hébergement proche de la Cité Internationale simplifie les journées de salon. Part-Dieu peut être plus pratique pour les voyageurs en TGV, tandis que la Presqu’île est souvent choisie lorsque des dîners et rendez-vous en centre-ville sont prévus." },
      { type: "paragraph", text: "Votre programme peut suivre un enchaînement hôtel → salon → rendez-vous client → dîner → retour. Pour une clientèle B2B, cette organisation globale est souvent plus utile qu’un simple transfert aller-retour." },
      { type: "heading", text: "Préparer les horaires sensibles" },
      { type: "paragraph", text: "Pour un exposant, l’heure d’arrivée peut être antérieure à celle du public. Pour un visiteur, le premier rendez-vous fixé sur un stand ou une conférence peut servir de référence. Pour le retour, partez de l’heure du train ou du vol et remontez jusqu’à l’heure de prise en charge conseillée." },
      { type: "paragraph", text: "En transmettant ces contraintes dès la demande, Kdrive peut confirmer plus clairement la faisabilité du planning." },
      { type: "heading", text: "Exemple de parcours B2B" },
      { type: "paragraph", text: "Un ingénieur peut arriver à Lyon-Saint-Exupéry, rejoindre son hôtel, se rendre au salon le lendemain, puis enchaîner avec un rendez-vous client ou un dîner dans la Presqu’île. Le second jour, la prise en charge peut se faire directement au Centre de Congrès pour un retour vers Part-Dieu." },
    ],
    faq: [
      { q: "Quelles sont les dates du salon?", a: "Les 14 et 15 octobre 2026." },
      { q: "Où a lieu Mesures Solutions EXPO?", a: "À la Cité des Congrès de Lyon." },
      { q: "Peut-on réserver depuis l’aéroport Lyon-Saint-Exupéry?", a: "Oui." },
      { q: "La prise en charge à Part-Dieu est-elle possible?", a: "Oui, sur réservation." },
      { q: "Peut-on organiser plusieurs arrêts dans la journée?", a: "Oui, via plusieurs trajets ou une mise à disposition selon le programme." },
    ],
    internalLinks: [
      { href: "/reserver", label: "Réserver un VTC" },
      { href: "/transfert-aeroport", label: "transfert aéroport" },
      { href: "/transfert-gare", label: "transfert gare" },
      { href: "/chauffeur-entreprise", label: "chauffeur entreprise" },
      { href: "/mise-a-disposition", label: "mise à disposition" },
    ],
    sources: ["https://mesures-solutions-expo.fr/"],
    annualUpdate: { keepSlug: true, note: "Mettre à jour chaque année le millésime dans le Title/H1, les dates, horaires, lieu si changement, chiffres de fréquentation, programme et informations d'accès. Conserver l'URL evergreen et le maillage si les services Kdrive restent identiques." },
  },
  {
    slug: "vtc-ib-global-conference-lyon",
    categorySlug: "evenements-lyon",
    title: "VTC IB Global Conference Lyon 2026 | Kdrive",
    metaDescription: "IB Global Conference Lyon 2026 : chauffeur privé et transferts entre Lyon-Saint-Exupéry, les gares, hôtels et le Convention Centre.",
    h1: "VTC IB Global Conference Lyon 2026 : private driver for your stay in Lyon",
    excerpt: "L'IB Global Conference Lyon 2026 se déroule du 22 au 24 octobre au Lyon Convention Centre. L'événement accueille des responsables d'établissements, coordinateurs, enseignants, exposants et partenaires du réseau International Baccalaureate.",
    publishedAt: "2026-09-23",
    updatedAt: "2026-09-23",
    eventStartDate: "2026-10-22",
    eventEndDate: "2026-10-24",
    eventLocation: "Lyon Convention Centre (Cité Internationale)",
    status: "a-venir",
    heroImage: "/images/corporate.jpg",
    heroImageAlt: "Chauffeur privé Kdrive pour l'IB Global Conference à Lyon",
    body: [
      { type: "paragraph", text: "L’IB Global Conference Lyon 2026 se déroule du 22 au 24 octobre au Lyon Convention Centre. L’événement accueille des responsables d’établissements, coordinateurs, enseignants, exposants et partenaires du réseau International Baccalaureate. L’édition 2026 est annoncée complète et réunit une audience internationale sur trois journées de conférences, ateliers et networking." },
      { type: "paragraph", text: "Pour des participants venant de plusieurs pays, la mobilité commence souvent à Lyon-Saint-Exupéry ou dans une gare TGV. Kdrive peut organiser les transferts entre l’aéroport, le Convention Centre, les hôtels et les différents rendez-vous du séjour." },
      { type: "heading", text: "Lyon Convention Centre : le point central de la conférence" },
      { type: "paragraph", text: "La conférence a lieu au Lyon Convention Centre, 50 quai Charles-de-Gaulle, dans la Cité Internationale. Le lieu est proche de plusieurs hôtels mais reste à distance des principales gares et de l’aéroport." },
      { type: "paragraph", text: "Une prise en charge réservée est particulièrement utile pour les participants qui arrivent avec des bagages, qui ne connaissent pas Lyon ou qui doivent respecter un horaire de session précis." },
      { type: "heading", text: "Airport transfer from Lyon-Saint-Exupéry" },
      { type: "paragraph", text: "Les participants internationaux peuvent réserver leur transfert depuis Lyon-Saint-Exupéry avant leur départ. Le trajet peut conduire à l’hôtel ou directement au Convention Centre selon l’horaire d’arrivée." },
      { type: "paragraph", text: "Pour simplifier l’accueil, communiquez le numéro de vol, le nombre de voyageurs et les bagages. En cas de déplacement en groupe, une catégorie adaptée peut être prévue selon la disponibilité." },
      { type: "heading", text: "Arrivée par Part-Dieu ou Perrache" },
      { type: "paragraph", text: "Lyon est bien reliée aux grandes villes françaises et européennes par le train. Une prise en charge à Part-Dieu ou Perrache permet de rejoindre directement l’hôtel ou le site de la conférence sans ajouter de correspondances." },
      { type: "paragraph", text: "Le samedi 24 octobre, le programme se poursuit jusqu’en fin d’après-midi et comprend un dîner de célébration le soir. Pour un départ tardif ou un retour le lendemain, les transferts peuvent être préparés en même temps que l’arrivée." },
      { type: "heading", text: "Chauffeur privé pour dirigeants d’établissement et délégations" },
      { type: "paragraph", text: "Les conférences internationales créent souvent des besoins spécifiques : déplacement d’un responsable d’établissement, transfert d’une équipe, rendez-vous avec un partenaire, dîner ou visite complémentaire en ville. Une mise à disposition peut être plus souple lorsqu’un planning comporte plusieurs adresses." },
      { type: "paragraph", text: "Kdrive peut construire le trajet autour des horaires fournis et confirmer le tarif avant la course." },
      { type: "heading", text: "A short note for international visitors" },
      { type: "paragraph", text: "Kdrive is a private-driver service based in Lyon. Airport, train-station, hotel and conference transfers can be requested in advance. Share your pick-up point, destination, date, time, passenger count and luggage when booking so the journey can be prepared before your arrival." },
      { type: "heading", text: "Book your private driver for the IB Global Conference" },
      { type: "paragraph", text: "Anticipate the journeys that matter most: airport or train arrival, hotel, conference venue, evening events and return transport. Send your request to Kdrive before your trip so availability and pricing can be confirmed." },
      { type: "heading", text: "Quel véhicule pour des participants internationaux ?" },
      { type: "paragraph", text: "Une arrivée internationale implique souvent davantage de bagages qu’un déplacement local. Pour un voyageur seul, une berline peut suffire ; pour plusieurs collègues, des accompagnants ou un groupe avec plusieurs valises, le volume doit être précisé au moment de la réservation." },
      { type: "paragraph", text: "Pour les écoles et organisations envoyant plusieurs participants, un transfert groupé peut réduire la dispersion à l’arrivée et simplifier la coordination avec l’hôtel." },
      { type: "heading", text: "Where to stay and how to plan your transfers" },
      { type: "paragraph", text: "Staying near the Cité Internationale is convenient for the conference itself. Part-Dieu can be practical for train travellers, while central Lyon may be preferred by participants planning dinners or sightseeing after sessions. Your transfer plan should reflect the actual programme, not only the conference venue." },
      { type: "paragraph", text: "For a three-day event, the most important journeys to book first are usually airport or train arrival, the first morning, any official evening event, and the final transfer back to the station or airport." },
      { type: "heading", text: "Informations utiles pour une réservation internationale" },
      { type: "paragraph", text: "Envoyez le nom du passager principal, un numéro de téléphone joignable, le numéro de vol ou l’heure du train, le nombre de bagages et l’adresse complète de l’hôtel. Ces données sont particulièrement utiles lorsqu’un voyageur arrive dans une ville qu’il ne connaît pas." },
      { type: "paragraph", text: "Pour une délégation, indiquez également si plusieurs personnes arrivent sur des vols différents. Les trajets peuvent alors être organisés séparément ou regroupés selon les horaires." },
      { type: "heading", text: "Example of a three-day transfer plan" },
      { type: "paragraph", text: "An international attendee may book Lyon Airport → hotel on arrival day, hotel → Lyon Convention Centre for the opening sessions, a transfer after the reception, and a final ride to Part-Dieu or the airport after the conference. A school delegation may also need several pick-ups if colleagues arrive on different flights." },
    ],
    faq: [
      { q: "When is the IB Global Conference Lyon 2026?", a: "From 22 to 24 October 2026." },
      { q: "Where is the conference held?", a: "At the Lyon Convention Centre, 50 quai Charles-de-Gaulle." },
      { q: "Can I book an airport transfer?", a: "Yes, from Lyon-Saint-Exupéry to your hotel, the conference venue or another address." },
      { q: "Can Kdrive pick me up at Lyon Part-Dieu?", a: "Yes, on reservation." },
      { q: "Can a group or delegation book several transfers?", a: "Yes. Passenger and luggage details should be provided when requesting the booking." },
    ],
    internalLinks: [
      { href: "/reserver", label: "Réserver un VTC" },
      { href: "/transfert-aeroport", label: "transfert aéroport" },
      { href: "/transfert-gare", label: "transfert gare" },
      { href: "/chauffeur-entreprise", label: "chauffeur privé entreprise" },
      { href: "/mise-a-disposition", label: "mise à disposition" },
    ],
    sources: ["https://ibo.org/ib-global-conference-lyon-2026/"],
    annualUpdate: { keepSlug: true, note: "Mettre à jour chaque année le millésime dans le Title/H1, les dates, horaires, lieu si changement, chiffres de fréquentation, programme et informations d'accès. Conserver l'URL evergreen et le maillage si les services Kdrive restent identiques." },
  },
  {
    slug: "vtc-cepas-lyon",
    categorySlug: "evenements-lyon",
    title: "VTC CEPAS Lyon 2026 | Chauffeur privé Kdrive",
    metaDescription: "CEPAS Lyon 2026 au Centre de Congrès : réservez votre chauffeur privé depuis l'aéroport, les gares, votre hôtel ou Lyon.",
    h1: "VTC CEPAS Lyon 2026 : votre chauffeur pour le congrès de pédiatrie",
    excerpt: "Le Congress of the European Paediatric Academic Societies, CEPAS 2026, se déroule à Lyon du 28 au 31 octobre. Il s'agit de la première édition de ce nouveau congrès européen porté par l'European Academy of Paediatrics.",
    publishedAt: "2026-09-23",
    updatedAt: "2026-09-23",
    eventStartDate: "2026-10-28",
    eventEndDate: "2026-10-31",
    eventLocation: "Lyon Convention Centre (Cité Internationale)",
    status: "a-venir",
    heroImage: "/images/corporate.jpg",
    heroImageAlt: "Chauffeur privé Kdrive pour le congrès CEPAS à Lyon",
    body: [
      { type: "paragraph", text: "Le Congress of the European Paediatric Academic Societies, CEPAS 2026, se déroule à Lyon du 28 au 31 octobre. Il s’agit de la première édition de ce nouveau congrès européen porté par l’European Academy of Paediatrics et l’European Society for Paediatric Research. L’événement réunit professionnels de santé, chercheurs, enseignants et partenaires autour de la recherche, de la pratique clinique et de la formation en pédiatrie." },
      { type: "paragraph", text: "Les cours pré-congrès commencent le 28 octobre et le congrès principal se déroule du 29 au 31 octobre au Lyon Convention Centre. Pour les participants venant de France ou de l’étranger, Kdrive peut organiser les transferts entre l’aéroport, les gares, l’hôtel et la Cité Internationale." },
      { type: "heading", text: "Lyon Convention Centre et Cité Internationale" },
      { type: "paragraph", text: "CEPAS se tient au Centre de Congrès de Lyon, 50 quai Charles-de-Gaulle. La Cité Internationale regroupe plusieurs hôtels et espaces de restauration, mais les participants logés dans d’autres quartiers doivent prévoir les temps de trajet vers le 6e arrondissement." },
      { type: "paragraph", text: "Un chauffeur réservé à l’avance permet de fixer les heures de départ en fonction du programme scientifique, notamment pour les premières sessions du matin ou les retours après les événements du soir." },
      { type: "heading", text: "Transfert depuis Lyon-Saint-Exupéry" },
      { type: "paragraph", text: "Pour un congrès européen, une part importante des participants peut arriver par avion. Kdrive peut assurer un transfert depuis Lyon-Saint-Exupéry vers l’hôtel ou directement vers le Centre de Congrès selon l’heure d’arrivée." },
      { type: "paragraph", text: "Les informations de vol, le nombre de passagers et les bagages doivent être transmis lors de la demande. Cela facilite l’organisation de la prise en charge et le choix de la catégorie de véhicule." },
      { type: "heading", text: "Prise en charge depuis Part-Dieu et Perrache" },
      { type: "paragraph", text: "Les congressistes arrivant en TGV peuvent réserver leur transfert depuis Part-Dieu ou Perrache. Le service peut aussi être utilisé pour le départ, avec une heure de prise en charge déterminée en fonction de la fin de session et de l’heure du train." },
      { type: "paragraph", text: "Pour un séjour de plusieurs jours, les trajets hôtel vers congrès peuvent être planifiés en amont afin de garder une organisation régulière." },
      { type: "heading", text: "Mise à disposition pour intervenants et délégations médicales" },
      { type: "paragraph", text: "Un intervenant ou une délégation peut avoir plusieurs étapes : conférence, rendez-vous institutionnel, dîner scientifique, rencontre avec un partenaire ou déplacement vers un établissement de santé. Une mise à disposition peut alors offrir une organisation plus cohérente." },
      { type: "paragraph", text: "Le planning est préparé à partir des adresses et horaires communiqués. Kdrive confirme la disponibilité et le tarif avant la prestation." },
      { type: "heading", text: "Réserver votre VTC pour CEPAS Lyon" },
      { type: "paragraph", text: "Pour un congrès médical international, les trajets à horaire fixe méritent d’être anticipés. Réservez vos arrivées, départs et déplacements professionnels avec Kdrive afin de disposer d’une organisation claire pendant votre séjour à Lyon." },
      { type: "heading", text: "Quel véhicule pour une délégation médicale ?" },
      { type: "paragraph", text: "Un médecin ou chercheur voyageant seul peut généralement utiliser une berline. Pour plusieurs congressistes, des bagages nombreux ou une équipe internationale, indiquez la composition du groupe et le volume transporté afin de vérifier la catégorie disponible." },
      { type: "paragraph", text: "Pour les intervenants transportant du matériel de présentation, cette information doit également être signalée avant confirmation." },
      { type: "heading", text: "Hébergement et organisation sur plusieurs jours" },
      { type: "paragraph", text: "La Cité Internationale est la zone la plus directe pour rejoindre le Lyon Convention Centre. D’autres participants peuvent choisir Part-Dieu, les Brotteaux ou la Presqu’île selon leurs contraintes de voyage et leurs rendez-vous du soir." },
      { type: "paragraph", text: "Comme CEPAS s’étend sur plusieurs jours, l’organisation peut combiner des transferts ponctuels et des déplacements récurrents. Réserver au minimum l’arrivée, le premier trajet vers le congrès et le départ permet de sécuriser les moments les plus sensibles." },
      { type: "heading", text: "Préparer l’accueil d’un intervenant ou d’un invité" },
      { type: "paragraph", text: "Pour un intervenant scientifique, un horaire approximatif n’est pas suffisant : communiquez l’heure de présence requise, le lieu exact et une marge adaptée. Ajoutez les informations de vol ou de train pour l’arrivée et le départ." },
      { type: "paragraph", text: "Si une organisation réserve pour un tiers, fournissez à la fois les coordonnées du passager et celles de la personne en charge du déplacement. Cela facilite les échanges en cas de modification." },
      { type: "heading", text: "Exemple de parcours pour une délégation" },
      { type: "paragraph", text: "Une délégation médicale peut arriver à Lyon-Saint-Exupéry le 27 ou le 28 octobre, rejoindre un hôtel de la Cité Internationale, se rendre aux cours pré-congrès puis organiser un dîner ou une rencontre scientifique en centre-ville. Le dernier jour, un transfert direct vers l’aéroport ou Part-Dieu évite une étape supplémentaire par l’hôtel." },
      { type: "paragraph", text: "Pour une réservation effectuée par un secrétariat ou une institution, transmettez le nom du passager, un numéro joignable, l’hôtel, l’horaire de session, les informations de vol ou de train et les éventuelles contraintes de bagages." },
    ],
    faq: [
      { q: "Quelles sont les dates de CEPAS 2026?", a: "Du 28 au 31 octobre 2026, avec les cours pré-congrès le 28." },
      { q: "Où se déroule CEPAS?", a: "Au Lyon Convention Centre, 50 quai Charles-de-Gaulle." },
      { q: "Peut-on réserver depuis Lyon-Saint-Exupéry?", a: "Oui, vers l’hôtel, le congrès ou une autre adresse." },
      { q: "Kdrive peut-il transporter une petite délégation?", a: "Oui, sous réserve de la capacité du véhicule disponible et des bagages annoncés." },
      { q: "Peut-on organiser plusieurs transferts pendant le congrès?", a: "Oui, ou choisir une mise à disposition si le planning comporte plusieurs déplacements." },
    ],
    internalLinks: [
      { href: "/reserver", label: "Réserver un VTC" },
      { href: "/transfert-aeroport", label: "transfert aéroport" },
      { href: "/transfert-gare", label: "transfert gare" },
      { href: "/chauffeur-entreprise", label: "chauffeur entreprise" },
      { href: "/mise-a-disposition", label: "mise à disposition" },
    ],
    sources: ["https://www.cepas.org/"],
    annualUpdate: { keepSlug: true, note: "Mettre à jour chaque année le millésime dans le Title/H1, les dates, horaires, lieu si changement, chiffres de fréquentation, programme et informations d'accès. Conserver l'URL evergreen et le maillage si les services Kdrive restent identiques." },
  },
  {
    slug: "vtc-equita-lyon",
    categorySlug: "evenements-lyon",
    title: "VTC Equita Lyon 2026 | Transfert Eurexpo Kdrive",
    metaDescription: "Equita Lyon 2026 à Eurexpo : réservez votre VTC depuis l'aéroport, les gares, votre hôtel ou Lyon avec Kdrive.",
    h1: "VTC Equita Lyon 2026 : votre transfert vers Eurexpo",
    excerpt: "Equita Lyon se tient du 28 octobre au 1er novembre 2026 à Eurexpo. Le Salon du Cheval de Lyon et le Longines Equita Lyon Concours Hippique International occupent un format particulièrement large, avec compétitions et nombreux exposants.",
    publishedAt: "2026-09-23",
    updatedAt: "2026-09-23",
    eventStartDate: "2026-10-28",
    eventEndDate: "2026-11-01",
    eventLocation: "Eurexpo Lyon (Chassieu)",
    status: "a-venir",
    heroImage: "/images/service-affaires.jpg",
    heroImageAlt: "Chauffeur privé Kdrive pour le salon Equita Lyon à Eurexpo",
    body: [
      { type: "paragraph", text: "Equita Lyon se tient du 28 octobre au 1er novembre 2026 à Eurexpo. Le Salon du Cheval de Lyon et le Longines Equita Lyon Concours Hippique International occupent un format particulièrement large, avec des compétitions, des animations, de nombreux exposants et une fréquentation importante sur plusieurs jours." },
      { type: "paragraph", text: "Pour un visiteur, un cavalier, un exposant ou un partenaire, le transport vers Chassieu peut devenir un élément important du séjour. Kdrive permet de réserver les trajets entre l’aéroport, les gares, les hôtels, Lyon et Eurexpo." },
      { type: "heading", text: "Eurexpo : anticiper les pics de fréquentation" },
      { type: "paragraph", text: "Equita Lyon occupe un vaste espace à Eurexpo et attire un public nombreux. L’organisation annonce des amplitudes horaires importantes, avec des journées pouvant se prolonger en soirée. Dans ce contexte, les arrivées du matin et les sorties après les épreuves majeures peuvent concentrer beaucoup de déplacements." },
      { type: "paragraph", text: "Réserver son chauffeur en amont permet de fixer un rendez-vous et d’éviter d’improviser le retour après une longue journée de salon ou de compétition." },
      { type: "heading", text: "Transfert Lyon-Saint-Exupéry vers Equita Lyon" },
      { type: "paragraph", text: "Eurexpo est situé à l’est de Lyon, relativement proche de l’aéroport. Les visiteurs venant d’une autre région ou de l’étranger peuvent donc réserver un transfert depuis Lyon-Saint-Exupéry vers leur hôtel ou directement vers le salon." },
      { type: "paragraph", text: "Pour les voyageurs avec plusieurs bagages, du matériel ou un groupe de plusieurs personnes, ces informations doivent être communiquées à la réservation afin de choisir la catégorie de véhicule la plus adaptée." },
      { type: "heading", text: "Part-Dieu, Perrache et hôtels : organiser l’aller-retour" },
      { type: "paragraph", text: "Les visiteurs arrivant par TGV peuvent être pris en charge à Part-Dieu ou Perrache. Pour ceux qui séjournent plusieurs nuits, un trajet hôtel vers Eurexpo peut être planifié chaque jour selon les horaires prévus." },
      { type: "paragraph", text: "Les retours après les compétitions du soir méritent une attention particulière. Le samedi 31 octobre, l’événement annonce une ouverture jusqu’en soirée, ce qui rend utile une prise en charge programmée plutôt qu’une recherche de transport au moment de la sortie." },
      { type: "heading", text: "VTC pour cavaliers, exposants, partenaires et visiteurs" },
      { type: "paragraph", text: "Les besoins ne sont pas les mêmes selon le profil. Un visiteur souhaite généralement un aller-retour confortable. Un exposant peut commencer plus tôt, transporter des bagages ou rejoindre un dîner professionnel. Un partenaire ou un invité peut avoir plusieurs rendez-vous dans Lyon." },
      { type: "paragraph", text: "Kdrive peut adapter la réservation au programme annoncé : trajet simple, retour à heure fixe, plusieurs transferts ou mise à disposition." },
      { type: "heading", text: "Voyager en groupe ou avec beaucoup de bagages" },
      { type: "paragraph", text: "Equita Lyon attire aussi des familles, groupes et équipes. Le nombre de passagers, les bagages et les éventuels équipements doivent être précisés avant confirmation. Une catégorie Van peut être pertinente lorsque plusieurs personnes voyagent ensemble ou lorsque le volume transporté est important." },
      { type: "paragraph", text: "Cette préparation évite les mauvaises surprises au moment de la prise en charge et permet de vérifier la capacité réelle du véhicule." },
      { type: "heading", text: "Mise à disposition pendant Equita Lyon" },
      { type: "paragraph", text: "Une mise à disposition peut intéresser les exposants, partenaires ou clients souhaitant combiner Eurexpo avec des rendez-vous, restaurants, hôtels ou déplacements en centre-ville. Le chauffeur est alors intégré à un programme plus large au lieu d’assurer uniquement un trajet ponctuel." },
      { type: "paragraph", text: "La prestation doit être préparée à l’avance, notamment pendant les journées de forte affluence." },
      { type: "heading", text: "Réserver votre chauffeur pour Equita Lyon" },
      { type: "paragraph", text: "Vous venez à Equita Lyon pour une journée, plusieurs jours, une compétition ou un rendez-vous professionnel ? Programmez vos transferts vers Eurexpo avec Kdrive et préparez en même temps votre arrivée, votre retour et les déplacements associés à votre séjour." },
      { type: "heading", text: "Quel véhicule choisir pour Equita ?" },
      { type: "paragraph", text: "Pour une personne seule ou un couple, une berline peut être suffisante. Pour une famille, un groupe, plusieurs bagages ou un séjour de plusieurs jours, une catégorie plus spacieuse est souvent préférable. Une équipe ou un exposant doit également signaler tout matériel transporté avant confirmation." },
      { type: "paragraph", text: "Le choix du véhicule doit être fait sur la capacité réelle, pas uniquement sur le nombre de sièges : plusieurs grandes valises peuvent rapidement réduire l’espace disponible." },
      { type: "heading", text: "Où loger pendant Equita Lyon ?" },
      { type: "paragraph", text: "Un hébergement dans l’est lyonnais rapproche d’Eurexpo et réduit le temps de trajet quotidien. Un hôtel dans le centre de Lyon permet en revanche de profiter plus facilement des restaurants, sorties et autres rendez-vous. Les participants présents plusieurs jours doivent donc arbitrer entre proximité du salon et vie en centre-ville." },
      { type: "paragraph", text: "Si le séjour combine Equita avec plusieurs activités, une mise à disposition ou des transferts planifiés peuvent être plus adaptés que des réservations isolées." },
      { type: "heading", text: "Préparer les journées longues et les retours du soir" },
      { type: "paragraph", text: "Equita se distingue par une amplitude horaire importante. Les visiteurs qui restent pour les compétitions ou animations du soir doivent penser au retour avant d’entrer sur le salon, surtout lors des journées les plus fréquentées." },
      { type: "paragraph", text: "Pour un départ vers une gare ou un aéroport, l’horaire doit tenir compte de la sortie d’Eurexpo, de la circulation et de la marge avant le train ou le vol. Mieux vaut prévoir cette contrainte dès la réservation." },
      { type: "heading", text: "Exemple de journée à Equita Lyon" },
      { type: "paragraph", text: "Une famille peut partir d’un hôtel du centre vers Eurexpo en matinée et réserver son retour après les animations. Un partenaire ou exposant peut avoir un programme différent : hôtel → Eurexpo → dîner en ville → hôtel, puis retour à l’aéroport le lendemain. Pour un groupe, le véhicule doit être dimensionné dès le départ en fonction des passagers et des bagages." },
    ],
    faq: [
      { q: "Quand a lieu Equita Lyon 2026?", a: "Du 28 octobre au 1er novembre 2026." },
      { q: "Où se déroule Equita Lyon?", a: "À Eurexpo Lyon, boulevard de l’Europe à Chassieu." },
      { q: "Peut-on réserver un VTC depuis l’aéroport?", a: "Oui, vers Eurexpo, un hôtel ou toute autre adresse convenue." },
      { q: "Kdrive prend-il en charge à Part-Dieu ou Perrache?", a: "Oui, sur réservation." },
      { q: "Peut-on réserver pour un groupe?", a: "Oui, en indiquant le nombre de passagers et de bagages." },
      { q: "Peut-on prévoir un retour tard le soir?", a: "Oui, sous réserve de disponibilité ; il est recommandé de l’anticiper." },
    ],
    internalLinks: [
      { href: "/reserver", label: "Réserver un VTC" },
      { href: "/transfert-aeroport", label: "transfert aéroport" },
      { href: "/transfert-gare", label: "transfert gare" },
      { href: "/mise-a-disposition", label: "mise à disposition" },
      { href: "/vehicules", label: "Nos véhicules" },
    ],
    sources: ["https://www.equitalyon.com/fr"],
    annualUpdate: { keepSlug: true, note: "Mettre à jour chaque année le millésime dans le Title/H1, les dates, horaires, lieu si changement, chiffres de fréquentation, programme et informations d'accès. Conserver l'URL evergreen et le maillage si les services Kdrive restent identiques." },
  },
];
