import type { LocalPageContent } from "./local-page-template";

/**
 * Les 9 arrondissements de Lyon. Quartiers et équipements cités : faits
 * géographiques et institutionnels généralement admis (mairie de Lyon,
 * connaissance publique) — à consolider auprès de la Mairie de Lyon et de la
 * Métropole avant une indexation large si un doute subsiste sur un point
 * précis (cf. registre SEO, statut editorialStatus). Aucun tarif, avis,
 * horaire ou disponibilité n'est mentionné.
 */
export const arrondissementsPages: LocalPageContent[] = [
  {
    slug: "vtc-lyon-1er-arrondissement",
    family: "arrondissement",
    editorialStatus: "needsEnrichment",
    title: "VTC Lyon 1er arrondissement | Chauffeur privé | KDRIVE",
    metaDescription: "Chauffeur privé dans le 1er arrondissement de Lyon : Terreaux, Hôtel de Ville, Opéra, pentes de la Croix-Rousse. Tarif confirmé avant votre course.",
    eyebrow: "VTC Lyon 1er",
    h1: "Chauffeur VTC dans le 1er arrondissement de Lyon",
    breadcrumbParent: { label: "Zones desservies", href: "/zones-desservies" },
    heroImage: "/images/hero-lyon.jpg",
    heroLead: "KDRIVE prend en charge vos trajets au départ ou à destination du 1er arrondissement de Lyon, du quartier des Terreaux aux pentes de la Croix-Rousse.",
    presentationTitle: "Un chauffeur privé au cœur historique et administratif de Lyon",
    presentationBody: [
      "Le 1er arrondissement regroupe le quartier des Terreaux, l'Hôtel de Ville, l'Opéra de Lyon et les pentes de la Croix-Rousse : un secteur dense, mêlant institutions, vie culturelle et rues parfois étroites ou en travaux.",
      "KDRIVE organise la prise en charge selon l'adresse exacte indiquée lors de la réservation, en tenant compte des contraintes de circulation propres à ce secteur.",
    ],
    quartiersTitle: "Quartiers et lieux du 1er arrondissement",
    quartiers: [
      { title: "Terreaux et Hôtel de Ville", body: "Cœur institutionnel et touristique de Lyon, point de départ ou d'arrivée fréquent pour un rendez-vous professionnel ou une visite." },
      { title: "Opéra de Lyon", body: "Sortie de spectacle ou rendez-vous en soirée : un point de rendez-vous à préciser selon l'accès autorisé au moment du trajet." },
      { title: "Pentes de la Croix-Rousse", body: "Secteur en dénivelé, rues parfois étroites : indiquez l'adresse précise pour faciliter la prise en charge." },
      { title: "Musée des Beaux-Arts", body: "Repère pratique pour une prise en charge dans le secteur des Terreaux." },
    ],
    casUsageTitle: "Motifs de déplacement courants",
    casUsageItems: [
      "Rendez-vous professionnel ou administratif près de l'Hôtel de Ville.",
      "Sortie culturelle (Opéra, Musée des Beaux-Arts) en soirée.",
      "Trajet vers une gare ou l'aéroport depuis les Terreaux ou la Croix-Rousse.",
      "Déplacement vers un autre arrondissement de Lyon.",
    ],
    frequentTrips: [
      { title: "1er arrondissement → Gare Part-Dieu", body: "Trajet vers la gare de la Part-Dieu, sur la base de votre horaire de train.", href: "/vtc-lyon-part-dieu" },
      { title: "1er arrondissement → Aéroport Lyon-Saint Exupéry", body: "Transfert direct vers l'aéroport.", href: "/transfert-aeroport" },
      { title: "1er arrondissement → 4e arrondissement", body: "Trajet court vers le plateau de la Croix-Rousse.", href: "/vtc-lyon-4e-arrondissement" },
    ],
    faq: [
      { q: "KDRIVE dessert-il tout le 1er arrondissement ?", a: "KDRIVE prend en charge les demandes dans le 1er arrondissement au cas par cas ; chaque demande est confirmée individuellement par l'équipe avant la course." },
      { q: "Un accès est-il possible près des Terreaux malgré la circulation piétonne ?", a: "Le point de prise en charge est confirmé avec vous selon les zones d'accès autorisées au moment du trajet." },
      { q: "Puis-je réserver un trajet en soirée après l'Opéra ?", a: "Oui, indiquez l'horaire souhaité lors de la réservation ; la disponibilité est confirmée par KDRIVE." },
    ],
    neighborLinksTitle: "Arrondissements limitrophes",
    neighborLinks: [
      { href: "/vtc-lyon-4e-arrondissement", label: "Lyon 4e (Croix-Rousse)" },
      { href: "/vtc-lyon-2e-arrondissement", label: "Lyon 2e (Presqu'île)" },
      { href: "/vtc-lyon-6e-arrondissement", label: "Lyon 6e (Brotteaux)" },
      { href: "/zones-desservies", label: "Toutes les zones desservies" },
    ],
    pillarLinksTitle: "Poursuivre votre réservation",
    pillarLinks: [
      { href: "/transfert-gare", label: "Transfert gare" },
      { href: "/transfert-aeroport", label: "Transfert aéroport" },
      { href: "/vehicules", label: "Nos véhicules" },
      { href: "/tarifs", label: "Grille tarifaire" },
      { href: "/reserver", label: "Réserver un trajet" },
    ],
    sources: ["Connaissance générale des quartiers de Lyon 1er (Terreaux, Croix-Rousse) — à consolider auprès de mairie1.lyon.fr avant indexation large."],
  },
  {
    slug: "vtc-lyon-2e-arrondissement",
    family: "arrondissement",
    editorialStatus: "needsEnrichment",
    title: "VTC Lyon 2e arrondissement | Chauffeur privé | KDRIVE",
    metaDescription: "Chauffeur privé dans le 2e arrondissement de Lyon : Bellecour, Presqu'île, Cordeliers, Confluence. Tarif confirmé avant votre course.",
    eyebrow: "VTC Lyon 2e",
    h1: "Chauffeur VTC dans le 2e arrondissement de Lyon",
    breadcrumbParent: { label: "Zones desservies", href: "/zones-desservies" },
    heroImage: "/images/hero-lyon.jpg",
    heroLead: "KDRIVE prend en charge vos trajets au départ ou à destination du 2e arrondissement de Lyon, de Bellecour à la Confluence.",
    presentationTitle: "Le cœur commerçant et central de la Presqu'île",
    presentationBody: [
      "Le 2e arrondissement couvre la partie sud de la Presqu'île : place Bellecour, Cordeliers, Ainay, le secteur de la gare de Perrache et le quartier de la Confluence. Un secteur très central, dense en commerces, bureaux et lieux de sortie.",
      "KDRIVE y organise des prises en charge pour des trajets professionnels, des sorties ou des transferts vers une gare ou l'aéroport.",
    ],
    quartiersTitle: "Quartiers et lieux du 2e arrondissement",
    quartiers: [
      { title: "Bellecour et Cordeliers", body: "Secteur commerçant central, fréquent pour un rendez-vous en journée ou une sortie en soirée." },
      { title: "Ainay", body: "Quartier résidentiel calme au sud de la Presqu'île." },
      { title: "Gare de Perrache", body: "Point de correspondance ferroviaire majeur du 2e arrondissement.", },
      { title: "Confluence", body: "Quartier réaménagé (musée des Confluences, centre commercial), pôle de bureaux et de loisirs en développement." },
    ],
    casUsageTitle: "Motifs de déplacement courants",
    casUsageItems: [
      "Rendez-vous professionnel ou shopping autour de Bellecour.",
      "Trajet vers ou depuis la gare de Perrache.",
      "Sortie ou déplacement vers le quartier de la Confluence.",
      "Transfert vers l'aéroport ou une autre gare de Lyon.",
    ],
    frequentTrips: [
      { title: "2e arrondissement → Gare Perrache", body: "Trajet court vers la gare de Perrache.", href: "/vtc-lyon-perrache" },
      { title: "2e arrondissement → Aéroport Lyon-Saint Exupéry", body: "Transfert direct vers l'aéroport.", href: "/transfert-aeroport" },
      { title: "2e arrondissement → 3e arrondissement", body: "Trajet vers la Part-Dieu et son quartier d'affaires.", href: "/vtc-lyon-3e-arrondissement" },
    ],
    faq: [
      { q: "KDRIVE dessert-il tout le 2e arrondissement ?", a: "KDRIVE prend en charge les demandes dans le 2e arrondissement au cas par cas ; chaque demande est confirmée individuellement par l'équipe avant la course." },
      { q: "Le point de rendez-vous à Bellecour est-il fixe ?", a: "Aucun point de rendez-vous fixe n'est promis sans confirmation ; l'emplacement précis est convenu avec vous selon l'accès autorisé." },
      { q: "KDRIVE dessert-il la Confluence ?", a: "Oui, le quartier de la Confluence est desservi comme le reste du 2e arrondissement, sur réservation." },
    ],
    neighborLinksTitle: "Arrondissements limitrophes",
    neighborLinks: [
      { href: "/vtc-lyon-3e-arrondissement", label: "Lyon 3e (Part-Dieu)" },
      { href: "/vtc-lyon-1er-arrondissement", label: "Lyon 1er (Terreaux)" },
      { href: "/vtc-lyon-perrache", label: "VTC Gare Lyon Perrache" },
      { href: "/zones-desservies", label: "Toutes les zones desservies" },
    ],
    pillarLinksTitle: "Poursuivre votre réservation",
    pillarLinks: [
      { href: "/transfert-gare", label: "Transfert gare" },
      { href: "/transfert-aeroport", label: "Transfert aéroport" },
      { href: "/vehicules", label: "Nos véhicules" },
      { href: "/tarifs", label: "Grille tarifaire" },
      { href: "/reserver", label: "Réserver un trajet" },
    ],
    sources: ["Connaissance générale des quartiers de Lyon 2e (Bellecour, Confluence, Perrache) — à consolider auprès de mairie2.lyon.fr."],
  },
  {
    slug: "vtc-lyon-3e-arrondissement",
    family: "arrondissement",
    editorialStatus: "needsEnrichment",
    title: "VTC Lyon 3e arrondissement | Chauffeur privé Part-Dieu | KDRIVE",
    metaDescription: "Chauffeur privé dans le 3e arrondissement de Lyon : Part-Dieu, Montchat, Halles de Lyon Paul Bocuse. Tarif confirmé avant votre course.",
    eyebrow: "VTC Lyon 3e",
    h1: "Chauffeur VTC dans le 3e arrondissement de Lyon",
    breadcrumbParent: { label: "Zones desservies", href: "/zones-desservies" },
    heroImage: "/images/service-affaires.jpg",
    heroLead: "KDRIVE prend en charge vos trajets au départ ou à destination du 3e arrondissement de Lyon, quartier d'affaires autour de la Part-Dieu.",
    presentationTitle: "Le plus grand arrondissement de Lyon, entre affaires et gare",
    presentationBody: [
      "Le 3e arrondissement est le plus étendu de Lyon : il regroupe le quartier d'affaires de la Part-Dieu, la gare du même nom, ainsi que les secteurs de la Villette et de Montchat. Un secteur très fréquenté pour les déplacements professionnels et les correspondances ferroviaires.",
      "KDRIVE y organise des prises en charge adaptées aux rendez-vous d'affaires comme aux trajets vers la gare Part-Dieu.",
    ],
    quartiersTitle: "Quartiers et lieux du 3e arrondissement",
    quartiers: [
      { title: "Part-Dieu", body: "Quartier d'affaires et pôle multimodal majeur de la métropole lyonnaise, avec la gare éponyme." },
      { title: "Halles de Lyon Paul Bocuse", body: "Marché couvert bien identifié du 3e arrondissement, repère pratique pour une prise en charge." },
      { title: "Montchat", body: "Quartier résidentiel à l'est de l'arrondissement." },
      { title: "La Villette", body: "Secteur mêlant logements et petites entreprises, proche de la Part-Dieu." },
    ],
    casUsageTitle: "Motifs de déplacement courants",
    casUsageItems: [
      "Rendez-vous professionnel dans le quartier d'affaires de la Part-Dieu.",
      "Trajet vers ou depuis la gare de la Part-Dieu.",
      "Déplacement depuis Montchat ou la Villette vers le centre de Lyon.",
      "Transfert vers l'aéroport ou une autre gare.",
    ],
    frequentTrips: [
      { title: "3e arrondissement → Gare Part-Dieu", body: "Trajet court vers la gare, sur la base de votre horaire de train.", href: "/vtc-lyon-part-dieu" },
      { title: "3e arrondissement → Aéroport Lyon-Saint Exupéry", body: "Transfert direct vers l'aéroport.", href: "/transfert-aeroport" },
      { title: "3e arrondissement → Villeurbanne", body: "Trajet vers la commune limitrophe de Villeurbanne.", href: "/vtc-villeurbanne" },
    ],
    faq: [
      { q: "KDRIVE dessert-il tout le 3e arrondissement ?", a: "KDRIVE prend en charge les demandes dans le 3e arrondissement au cas par cas ; chaque demande est confirmée individuellement par l'équipe avant la course." },
      { q: "Quel véhicule pour un rendez-vous professionnel à la Part-Dieu ?", a: "La catégorie Premium est recommandée pour un rendez-vous d'affaires ; Essentiel convient pour un trajet simple." },
      { q: "KDRIVE dessert-il aussi Montchat et la Villette ?", a: "Oui, ces secteurs du 3e arrondissement sont desservis comme le reste de l'arrondissement, sur réservation." },
    ],
    neighborLinksTitle: "Arrondissements limitrophes",
    neighborLinks: [
      { href: "/vtc-lyon-6e-arrondissement", label: "Lyon 6e (Brotteaux)" },
      { href: "/vtc-lyon-7e-arrondissement", label: "Lyon 7e (Gerland)" },
      { href: "/vtc-villeurbanne", label: "VTC Villeurbanne" },
      { href: "/zones-desservies", label: "Toutes les zones desservies" },
    ],
    pillarLinksTitle: "Poursuivre votre réservation",
    pillarLinks: [
      { href: "/chauffeur-entreprise", label: "Chauffeur entreprise" },
      { href: "/transfert-gare", label: "Transfert gare" },
      { href: "/vehicules", label: "Nos véhicules" },
      { href: "/tarifs", label: "Grille tarifaire" },
      { href: "/reserver", label: "Réserver un trajet" },
    ],
    sources: ["Connaissance générale du 3e arrondissement (Part-Dieu, Halles Paul Bocuse, Montchat) — à consolider auprès de mairie3.lyon.fr."],
  },
  {
    slug: "vtc-lyon-4e-arrondissement",
    family: "arrondissement",
    editorialStatus: "needsEnrichment",
    title: "VTC Lyon 4e arrondissement | Chauffeur privé Croix-Rousse | KDRIVE",
    metaDescription: "Chauffeur privé dans le 4e arrondissement de Lyon : plateau de la Croix-Rousse, Gros Caillou. Tarif confirmé avant votre course.",
    eyebrow: "VTC Lyon 4e",
    h1: "Chauffeur VTC dans le 4e arrondissement de Lyon",
    breadcrumbParent: { label: "Zones desservies", href: "/zones-desservies" },
    heroImage: "/images/hero-lyon.jpg",
    heroLead: "KDRIVE prend en charge vos trajets au départ ou à destination du 4e arrondissement de Lyon, sur le plateau de la Croix-Rousse.",
    presentationTitle: "Le plateau de la Croix-Rousse, entre habitat et patrimoine",
    presentationBody: [
      "Le 4e arrondissement correspond au plateau de la Croix-Rousse, quartier résidentiel au patrimoine canut, avec ses rues en pente et ses traboules. Le secteur du Gros Caillou et l'hôpital de la Croix-Rousse en sont des repères connus.",
      "KDRIVE organise la prise en charge selon l'adresse exacte indiquée, en tenant compte du relief et des rues parfois étroites du plateau.",
    ],
    quartiersTitle: "Quartiers et lieux du 4e arrondissement",
    quartiers: [
      { title: "Plateau de la Croix-Rousse", body: "Quartier résidentiel en hauteur, connu pour son marché et son patrimoine canut." },
      { title: "Gros Caillou", body: "Place emblématique du plateau, repère pratique pour une prise en charge." },
      { title: "Hôpital de la Croix-Rousse", body: "Établissement de santé du secteur, cité ici comme lieu de déplacement ordinaire." },
    ],
    casUsageTitle: "Motifs de déplacement courants",
    casUsageItems: [
      "Trajet résidentiel depuis ou vers le plateau de la Croix-Rousse.",
      "Déplacement lié à un rendez-vous à l'hôpital de la Croix-Rousse.",
      "Trajet vers le centre de Lyon ou une gare.",
    ],
    frequentTrips: [
      { title: "4e arrondissement → 1er arrondissement", body: "Trajet vers les Terreaux, en contrebas du plateau.", href: "/vtc-lyon-1er-arrondissement" },
      { title: "4e arrondissement → Gare Part-Dieu", body: "Transfert vers la gare de la Part-Dieu.", href: "/vtc-lyon-part-dieu" },
      { title: "4e arrondissement → Aéroport Lyon-Saint Exupéry", body: "Transfert direct vers l'aéroport.", href: "/transfert-aeroport" },
    ],
    faq: [
      { q: "KDRIVE dessert-il tout le plateau de la Croix-Rousse ?", a: "KDRIVE prend en charge les demandes dans le 4e arrondissement au cas par cas ; chaque demande est confirmée individuellement par l'équipe avant la course." },
      { q: "Les rues en pente posent-elles une difficulté pour la prise en charge ?", a: "Indiquez l'adresse exacte lors de la réservation : le point de prise en charge est confirmé selon l'accès possible au véhicule." },
      { q: "Puis-je réserver un trajet vers l'hôpital de la Croix-Rousse ?", a: "Oui, ce type de trajet est traité comme toute autre demande de VTC dans le secteur." },
    ],
    neighborLinksTitle: "Arrondissements limitrophes",
    neighborLinks: [
      { href: "/vtc-lyon-1er-arrondissement", label: "Lyon 1er (Terreaux)" },
      { href: "/vtc-lyon-9e-arrondissement", label: "Lyon 9e (Vaise)" },
      { href: "/zones-desservies", label: "Toutes les zones desservies" },
    ],
    pillarLinksTitle: "Poursuivre votre réservation",
    pillarLinks: [
      { href: "/transfert-gare", label: "Transfert gare" },
      { href: "/transfert-aeroport", label: "Transfert aéroport" },
      { href: "/vehicules", label: "Nos véhicules" },
      { href: "/tarifs", label: "Grille tarifaire" },
      { href: "/reserver", label: "Réserver un trajet" },
    ],
    sources: ["Connaissance générale du 4e arrondissement (plateau Croix-Rousse, Gros Caillou) — à consolider auprès de mairie4.lyon.fr."],
  },
  {
    slug: "vtc-lyon-5e-arrondissement",
    family: "arrondissement",
    editorialStatus: "needsEnrichment",
    title: "VTC Lyon 5e arrondissement | Chauffeur privé Vieux Lyon | KDRIVE",
    metaDescription: "Chauffeur privé dans le 5e arrondissement de Lyon : Vieux Lyon, Fourvière, Point-du-Jour. Tarif confirmé avant votre course.",
    eyebrow: "VTC Lyon 5e",
    h1: "Chauffeur VTC dans le 5e arrondissement de Lyon",
    breadcrumbParent: { label: "Zones desservies", href: "/zones-desservies" },
    heroImage: "/images/about-lyon.jpg",
    heroLead: "KDRIVE prend en charge vos trajets au départ ou à destination du 5e arrondissement de Lyon, du Vieux Lyon à Fourvière.",
    presentationTitle: "Le Lyon historique, entre Vieux Lyon et colline de Fourvière",
    presentationBody: [
      "Le 5e arrondissement regroupe le Vieux Lyon (quartier Saint-Jean), classé au patrimoine mondial de l'UNESCO, la colline de Fourvière et sa basilique, ainsi que des quartiers résidentiels comme Point-du-Jour, plus en hauteur.",
      "KDRIVE y organise des prises en charge en tenant compte des zones piétonnes du Vieux Lyon et du relief de la colline.",
    ],
    quartiersTitle: "Quartiers et lieux du 5e arrondissement",
    quartiers: [
      { title: "Vieux Lyon / Saint-Jean", body: "Quartier historique classé UNESCO, ruelles et traboules, accès parfois piéton selon les horaires." },
      { title: "Fourvière", body: "Colline emblématique de Lyon (basilique, théâtres romains), repère touristique et point de rendez-vous fréquent." },
      { title: "Point-du-Jour", body: "Quartier résidentiel du 5e arrondissement, plus éloigné du centre historique." },
    ],
    casUsageTitle: "Motifs de déplacement courants",
    casUsageItems: [
      "Trajet touristique ou professionnel vers le Vieux Lyon ou Fourvière.",
      "Déplacement résidentiel depuis Point-du-Jour.",
      "Trajet vers le centre de Lyon, une gare ou l'aéroport.",
    ],
    frequentTrips: [
      { title: "5e arrondissement → 2e arrondissement", body: "Trajet vers la Presqu'île, de l'autre côté de la Saône.", href: "/vtc-lyon-2e-arrondissement" },
      { title: "5e arrondissement → Gare Perrache", body: "Transfert vers la gare de Perrache.", href: "/vtc-lyon-perrache" },
      { title: "5e arrondissement → Aéroport Lyon-Saint Exupéry", body: "Transfert direct vers l'aéroport.", href: "/transfert-aeroport" },
    ],
    faq: [
      { q: "KDRIVE peut-il prendre en charge dans le Vieux Lyon malgré les rues piétonnes ?", a: "Le point de prise en charge est confirmé avec vous selon les zones d'accès autorisées au moment du trajet." },
      { q: "KDRIVE dessert-il aussi Point-du-Jour ?", a: "Oui, ce secteur résidentiel du 5e arrondissement est desservi comme le reste de l'arrondissement." },
      { q: "Puis-je réserver un trajet touristique vers Fourvière ?", a: "Oui, indiquez votre besoin lors de la réservation ; KDRIVE confirme le tarif et la disponibilité par téléphone." },
    ],
    neighborLinksTitle: "Arrondissements limitrophes",
    neighborLinks: [
      { href: "/vtc-lyon-2e-arrondissement", label: "Lyon 2e (Presqu'île)" },
      { href: "/vtc-lyon-9e-arrondissement", label: "Lyon 9e (Vaise)" },
      { href: "/zones-desservies", label: "Toutes les zones desservies" },
    ],
    pillarLinksTitle: "Poursuivre votre réservation",
    pillarLinks: [
      { href: "/transfert-gare", label: "Transfert gare" },
      { href: "/transfert-aeroport", label: "Transfert aéroport" },
      { href: "/vehicules", label: "Nos véhicules" },
      { href: "/tarifs", label: "Grille tarifaire" },
      { href: "/reserver", label: "Réserver un trajet" },
    ],
    sources: ["Connaissance générale du 5e arrondissement (Vieux Lyon UNESCO, Fourvière) — à consolider auprès de mairie5.lyon.fr et lyon-france.com."],
  },
  {
    slug: "vtc-lyon-6e-arrondissement",
    family: "arrondissement",
    editorialStatus: "needsEnrichment",
    title: "VTC Lyon 6e arrondissement | Chauffeur privé Brotteaux | KDRIVE",
    metaDescription: "Chauffeur privé dans le 6e arrondissement de Lyon : Brotteaux, Parc de la Tête d'Or, Cité Internationale. Tarif confirmé avant votre course.",
    eyebrow: "VTC Lyon 6e",
    h1: "Chauffeur VTC dans le 6e arrondissement de Lyon",
    breadcrumbParent: { label: "Zones desservies", href: "/zones-desservies" },
    heroImage: "/images/service-vip.jpg",
    heroLead: "KDRIVE prend en charge vos trajets au départ ou à destination du 6e arrondissement de Lyon, entre Brotteaux et Cité Internationale.",
    presentationTitle: "Un arrondissement résidentiel et institutionnel, en bord de parc",
    presentationBody: [
      "Le 6e arrondissement regroupe le quartier des Brotteaux, le Parc de la Tête d'Or et la Cité Internationale, qui accueille notamment un centre de congrès. Un secteur recherché pour l'habitat comme pour les événements professionnels.",
      "KDRIVE y organise des prises en charge adaptées aux rendez-vous professionnels comme aux trajets résidentiels.",
    ],
    quartiersTitle: "Quartiers et lieux du 6e arrondissement",
    quartiers: [
      { title: "Brotteaux", body: "Quartier résidentiel haussmannien, repère connu du 6e arrondissement." },
      { title: "Parc de la Tête d'Or", body: "Grand parc urbain de Lyon, point de repère fréquent pour une prise en charge." },
      { title: "Cité Internationale", body: "Ensemble regroupant un centre de congrès et des espaces culturels, en bordure du parc." },
    ],
    casUsageTitle: "Motifs de déplacement courants",
    casUsageItems: [
      "Rendez-vous ou événement professionnel à la Cité Internationale.",
      "Trajet résidentiel depuis le quartier des Brotteaux.",
      "Trajet vers le centre de Lyon, une gare ou l'aéroport.",
    ],
    frequentTrips: [
      { title: "6e arrondissement → Gare Part-Dieu", body: "Trajet vers la gare de la Part-Dieu.", href: "/vtc-lyon-part-dieu" },
      { title: "6e arrondissement → 3e arrondissement", body: "Trajet vers le quartier d'affaires de la Part-Dieu.", href: "/vtc-lyon-3e-arrondissement" },
      { title: "6e arrondissement → Aéroport Lyon-Saint Exupéry", body: "Transfert direct vers l'aéroport.", href: "/transfert-aeroport" },
    ],
    faq: [
      { q: "KDRIVE dessert-il un événement à la Cité Internationale ?", a: "Oui, le point de rendez-vous est confirmé avec vous selon les dispositifs d'accès en vigueur le jour de l'événement." },
      { q: "KDRIVE dessert-il tout le 6e arrondissement ?", a: "KDRIVE prend en charge les demandes dans le 6e arrondissement au cas par cas ; chaque demande est confirmée individuellement par l'équipe avant la course." },
      { q: "Quel véhicule pour un rendez-vous professionnel à la Cité Internationale ?", a: "La catégorie Premium est recommandée pour ce type de rendez-vous." },
    ],
    neighborLinksTitle: "Arrondissements limitrophes",
    neighborLinks: [
      { href: "/vtc-lyon-3e-arrondissement", label: "Lyon 3e (Part-Dieu)" },
      { href: "/vtc-lyon-1er-arrondissement", label: "Lyon 1er (Terreaux)" },
      { href: "/vtc-villeurbanne", label: "VTC Villeurbanne" },
      { href: "/zones-desservies", label: "Toutes les zones desservies" },
    ],
    pillarLinksTitle: "Poursuivre votre réservation",
    pillarLinks: [
      { href: "/chauffeur-entreprise", label: "Chauffeur entreprise" },
      { href: "/transfert-gare", label: "Transfert gare" },
      { href: "/vehicules", label: "Nos véhicules" },
      { href: "/tarifs", label: "Grille tarifaire" },
      { href: "/reserver", label: "Réserver un trajet" },
    ],
    sources: ["Connaissance générale du 6e arrondissement (Brotteaux, Parc de la Tête d'Or, Cité Internationale) — à consolider auprès de mairie6.lyon.fr."],
  },
  {
    slug: "vtc-lyon-7e-arrondissement",
    family: "arrondissement",
    editorialStatus: "needsEnrichment",
    title: "VTC Lyon 7e arrondissement | Chauffeur privé Gerland | KDRIVE",
    metaDescription: "Chauffeur privé dans le 7e arrondissement de Lyon : Gerland, Guillotière, Jean Macé, Halle Tony Garnier. Tarif confirmé avant votre course.",
    eyebrow: "VTC Lyon 7e",
    h1: "Chauffeur VTC dans le 7e arrondissement de Lyon",
    breadcrumbParent: { label: "Zones desservies", href: "/zones-desservies" },
    heroImage: "/images/hero-lyon.jpg",
    heroLead: "KDRIVE prend en charge vos trajets au départ ou à destination du 7e arrondissement de Lyon, de la Guillotière à Gerland.",
    presentationTitle: "Entre quartier universitaire, biodistrict et grande salle de spectacle",
    presentationBody: [
      "Le 7e arrondissement s'étend de la Guillotière, quartier dense et multiculturel proche du centre, jusqu'à Gerland, pôle universitaire et scientifique (ENS de Lyon) accueillant aussi la Halle Tony Garnier. Depuis janvier 2026, la gare routière longue distance de Lyon (FlixBus, BlaBlaBus, Itabus) est installée à Gerland.",
      "KDRIVE y organise des prises en charge pour des trajets étudiants, professionnels ou événementiels (concerts, spectacles à la Halle Tony Garnier).",
    ],
    quartiersTitle: "Quartiers et lieux du 7e arrondissement",
    quartiers: [
      { title: "Guillotière", body: "Quartier central et multiculturel, à la frontière du 3e arrondissement." },
      { title: "Jean Macé", body: "Quartier résidentiel et commerçant, bien desservi par les transports." },
      { title: "Gerland", body: "Pôle universitaire et scientifique (ENS de Lyon), avec la Halle Tony Garnier et la gare routière longue distance depuis janvier 2026." },
      { title: "Halle Tony Garnier", body: "Grande salle de concerts et d'événements de Lyon, repère pour un trajet de soirée." },
    ],
    casUsageTitle: "Motifs de déplacement courants",
    casUsageItems: [
      "Trajet de ou vers un concert ou événement à la Halle Tony Garnier.",
      "Déplacement universitaire ou professionnel vers Gerland.",
      "Trajet vers la gare routière longue distance de Gerland.",
      "Trajet vers le centre de Lyon depuis la Guillotière ou Jean Macé.",
    ],
    frequentTrips: [
      { title: "7e arrondissement → Gare Perrache", body: "Trajet vers la gare de Perrache, à proximité du 7e arrondissement.", href: "/vtc-lyon-perrache" },
      { title: "7e arrondissement → Aéroport Lyon-Saint Exupéry", body: "Transfert direct vers l'aéroport.", href: "/transfert-aeroport" },
      { title: "7e arrondissement → Gare Part-Dieu", body: "Trajet vers la gare de la Part-Dieu.", href: "/vtc-lyon-part-dieu" },
    ],
    faq: [
      { q: "KDRIVE dessert-il la gare routière de Gerland ?", a: "Oui, KDRIVE organise des trajets de et vers la gare routière longue distance de Gerland, installée depuis janvier 2026." },
      { q: "KDRIVE dessert-il un concert à la Halle Tony Garnier ?", a: "Oui, le point de rendez-vous est confirmé avec vous selon les dispositifs d'accès en vigueur le soir de l'événement." },
      { q: "KDRIVE dessert-il tout le 7e arrondissement ?", a: "KDRIVE prend en charge les demandes dans le 7e arrondissement au cas par cas ; chaque demande est confirmée individuellement par l'équipe avant la course." },
    ],
    neighborLinksTitle: "Arrondissements limitrophes",
    neighborLinks: [
      { href: "/vtc-lyon-3e-arrondissement", label: "Lyon 3e (Part-Dieu)" },
      { href: "/vtc-lyon-2e-arrondissement", label: "Lyon 2e (Presqu'île)" },
      { href: "/vtc-lyon-8e-arrondissement", label: "Lyon 8e (Monplaisir)" },
      { href: "/zones-desservies", label: "Toutes les zones desservies" },
    ],
    pillarLinksTitle: "Poursuivre votre réservation",
    pillarLinks: [
      { href: "/transfert-gare", label: "Transfert gare" },
      { href: "/vtc-halle-tony-garnier", label: "VTC Halle Tony Garnier" },
      { href: "/vehicules", label: "Nos véhicules" },
      { href: "/tarifs", label: "Grille tarifaire" },
      { href: "/reserver", label: "Réserver un trajet" },
    ],
    sources: ["Connaissance générale du 7e arrondissement (Gerland, Guillotière, Halle Tony Garnier) — gare routière Gerland confirmée lors du sprint transfert-gare précédent — à consolider auprès de mairie7.lyon.fr."],
  },
  {
    slug: "vtc-lyon-8e-arrondissement",
    family: "arrondissement",
    editorialStatus: "needsEnrichment",
    title: "VTC Lyon 8e arrondissement | Chauffeur privé Monplaisir | KDRIVE",
    metaDescription: "Chauffeur privé dans le 8e arrondissement de Lyon : Monplaisir, Institut Lumière, Grange-Blanche. Tarif confirmé avant votre course.",
    eyebrow: "VTC Lyon 8e",
    h1: "Chauffeur VTC dans le 8e arrondissement de Lyon",
    breadcrumbParent: { label: "Zones desservies", href: "/zones-desservies" },
    heroImage: "/images/hero-lyon.jpg",
    heroLead: "KDRIVE prend en charge vos trajets au départ ou à destination du 8e arrondissement de Lyon, de Monplaisir à Grange-Blanche.",
    presentationTitle: "Un arrondissement résidentiel, entre patrimoine du cinéma et pôle hospitalier",
    presentationBody: [
      "Le 8e arrondissement regroupe les quartiers de Monplaisir (connu pour l'Institut Lumière, berceau du cinématographe), Mermoz et États-Unis, ainsi que le secteur de Grange-Blanche, à la limite du 3e arrondissement, où se trouve un grand pôle hospitalier.",
      "KDRIVE y organise des prises en charge résidentielles comme des trajets liés à un rendez-vous médical, sans que cela ne constitue une spécialisation particulière.",
    ],
    quartiersTitle: "Quartiers et lieux du 8e arrondissement",
    quartiers: [
      { title: "Monplaisir", body: "Quartier résidentiel connu pour l'Institut Lumière, lié à l'histoire du cinéma." },
      { title: "Mermoz et États-Unis", body: "Quartiers résidentiels du 8e arrondissement." },
      { title: "Grange-Blanche", body: "Secteur accueillant un pôle hospitalier important, cité ici comme lieu de déplacement ordinaire, à la limite du 3e arrondissement." },
    ],
    casUsageTitle: "Motifs de déplacement courants",
    casUsageItems: [
      "Trajet résidentiel depuis Monplaisir, Mermoz ou États-Unis.",
      "Déplacement lié à un rendez-vous médical à Grange-Blanche.",
      "Trajet vers le centre de Lyon, une gare ou l'aéroport.",
    ],
    frequentTrips: [
      { title: "8e arrondissement → Gare Part-Dieu", body: "Trajet vers la gare de la Part-Dieu.", href: "/vtc-lyon-part-dieu" },
      { title: "8e arrondissement → Aéroport Lyon-Saint Exupéry", body: "Transfert direct vers l'aéroport, axe est de la métropole.", href: "/transfert-aeroport" },
      { title: "8e arrondissement → Bron", body: "Trajet vers la commune limitrophe de Bron.", href: "/vtc-bron" },
    ],
    faq: [
      { q: "KDRIVE dessert-il tout le 8e arrondissement ?", a: "KDRIVE prend en charge les demandes dans le 8e arrondissement au cas par cas ; chaque demande est confirmée individuellement par l'équipe avant la course." },
      { q: "KDRIVE dessert-il le secteur de Grange-Blanche ?", a: "Oui, ce secteur est desservi comme le reste de l'arrondissement, y compris pour un trajet lié à un rendez-vous médical." },
      { q: "KDRIVE dessert-il un trajet vers l'aéroport depuis Monplaisir ?", a: "Oui, un transfert direct est possible ; aucun délai n'est garanti à l'avance, la durée dépend du trafic." },
    ],
    neighborLinksTitle: "Arrondissements limitrophes",
    neighborLinks: [
      { href: "/vtc-lyon-7e-arrondissement", label: "Lyon 7e (Gerland)" },
      { href: "/vtc-lyon-3e-arrondissement", label: "Lyon 3e (Part-Dieu)" },
      { href: "/vtc-bron", label: "VTC Bron" },
      { href: "/zones-desservies", label: "Toutes les zones desservies" },
    ],
    pillarLinksTitle: "Poursuivre votre réservation",
    pillarLinks: [
      { href: "/transfert-gare", label: "Transfert gare" },
      { href: "/transfert-aeroport", label: "Transfert aéroport" },
      { href: "/vehicules", label: "Nos véhicules" },
      { href: "/tarifs", label: "Grille tarifaire" },
      { href: "/reserver", label: "Réserver un trajet" },
    ],
    sources: ["Connaissance générale du 8e arrondissement (Monplaisir, Institut Lumière, Grange-Blanche) — à consolider auprès de mairie8.lyon.fr."],
  },
  {
    slug: "vtc-lyon-9e-arrondissement",
    family: "arrondissement",
    editorialStatus: "needsEnrichment",
    title: "VTC Lyon 9e arrondissement | Chauffeur privé Vaise | KDRIVE",
    metaDescription: "Chauffeur privé dans le 9e arrondissement de Lyon : Vaise, Gorge de Loup, La Duchère. Tarif confirmé avant votre course.",
    eyebrow: "VTC Lyon 9e",
    h1: "Chauffeur VTC dans le 9e arrondissement de Lyon",
    breadcrumbParent: { label: "Zones desservies", href: "/zones-desservies" },
    heroImage: "/images/hero-lyon.jpg",
    heroLead: "KDRIVE prend en charge vos trajets au départ ou à destination du 9e arrondissement de Lyon, de Vaise à La Duchère.",
    presentationTitle: "Un pôle d'activité au nord-ouest de Lyon, en bord de Saône",
    presentationBody: [
      "Le 9e arrondissement regroupe Vaise, pôle d'activité et de bureaux en bord de Saône, le nœud de transport de Gorge de Loup, ainsi que le quartier résidentiel de La Duchère, en cours de renouvellement urbain.",
      "KDRIVE y organise des prises en charge pour des trajets professionnels comme résidentiels.",
    ],
    quartiersTitle: "Quartiers et lieux du 9e arrondissement",
    quartiers: [
      { title: "Vaise", body: "Pôle de bureaux et d'activité en bord de Saône, repère pour un trajet professionnel." },
      { title: "Gorge de Loup", body: "Nœud de transport (métro, gare) du 9e arrondissement." },
      { title: "La Duchère", body: "Quartier résidentiel en renouvellement urbain." },
      { title: "Île Barbe", body: "Secteur au bord de la Saône, à la limite du 9e arrondissement." },
    ],
    casUsageTitle: "Motifs de déplacement courants",
    casUsageItems: [
      "Rendez-vous professionnel à Vaise.",
      "Trajet résidentiel depuis La Duchère ou le secteur de Gorge de Loup.",
      "Trajet vers le centre de Lyon, une gare ou l'aéroport.",
    ],
    frequentTrips: [
      { title: "9e arrondissement → 1er arrondissement", body: "Trajet vers les Terreaux, au sud du 9e arrondissement.", href: "/vtc-lyon-1er-arrondissement" },
      { title: "9e arrondissement → Gare Part-Dieu", body: "Trajet vers la gare de la Part-Dieu.", href: "/vtc-lyon-part-dieu" },
      { title: "9e arrondissement → Aéroport Lyon-Saint Exupéry", body: "Transfert direct vers l'aéroport.", href: "/transfert-aeroport" },
    ],
    faq: [
      { q: "KDRIVE dessert-il tout le 9e arrondissement ?", a: "KDRIVE prend en charge les demandes dans le 9e arrondissement au cas par cas ; chaque demande est confirmée individuellement par l'équipe avant la course." },
      { q: "KDRIVE dessert-il un rendez-vous professionnel à Vaise ?", a: "Oui, la catégorie Premium est recommandée pour ce type de rendez-vous." },
      { q: "KDRIVE dessert-il le quartier de La Duchère ?", a: "Oui, ce quartier résidentiel est desservi comme le reste du 9e arrondissement." },
    ],
    neighborLinksTitle: "Arrondissements limitrophes",
    neighborLinks: [
      { href: "/vtc-lyon-1er-arrondissement", label: "Lyon 1er (Terreaux)" },
      { href: "/vtc-lyon-4e-arrondissement", label: "Lyon 4e (Croix-Rousse)" },
      { href: "/vtc-lyon-5e-arrondissement", label: "Lyon 5e (Vieux Lyon)" },
      { href: "/zones-desservies", label: "Toutes les zones desservies" },
    ],
    pillarLinksTitle: "Poursuivre votre réservation",
    pillarLinks: [
      { href: "/chauffeur-entreprise", label: "Chauffeur entreprise" },
      { href: "/transfert-gare", label: "Transfert gare" },
      { href: "/vehicules", label: "Nos véhicules" },
      { href: "/tarifs", label: "Grille tarifaire" },
      { href: "/reserver", label: "Réserver un trajet" },
    ],
    sources: ["Connaissance générale du 9e arrondissement (Vaise, Gorge de Loup, La Duchère) — à consolider auprès de mairie9.lyon.fr."],
  },
];
