import type { LocalPageContent } from "./local-page-template";

/**
 * Les 9 arrondissements de Lyon. Quartiers et équipements cités : faits
 * géographiques et institutionnels généralement admis (mairie de Lyon,
 * connaissance publique) — à consolider auprès de la Mairie de Lyon et de la
 * Métropole avant une indexation large si un doute subsiste sur un point
 * précis (cf. registre SEO, statut editorialStatus). Aucun tarif, avis,
 * horaire ou disponibilité n'est mentionné.
 */
export const arrondissementsPages: LocalPageContent[] = [
  {
    slug: "vtc-lyon-1er-arrondissement",
    family: "arrondissement",
    editorialStatus: "readyForIndexing",
    title: "VTC Lyon 1er arrondissement | Chauffeur privé | KDRIVE",
    metaDescription: "Chauffeur privé dans le 1er arrondissement de Lyon : Terreaux, Hôtel de Ville, Opéra, pentes de la Croix-Rousse. Tarif confirmé avant votre course.",
    eyebrow: "VTC Lyon 1er",
    h1: "Chauffeur VTC dans le 1er arrondissement de Lyon",
    breadcrumbParent: { label: "Zones desservies", href: "/zones-desservies" },
    heroImage: "/images/hero-lyon.jpg",
    heroLead: "KDRIVE prend en charge vos trajets au départ ou à destination du 1er arrondissement de Lyon, du quartier des Terreaux aux pentes de la Croix-Rousse.",
    presentationTitle: "Un chauffeur privé au cœur historique et administratif de Lyon",
    presentationBody: [
      "Le 1er arrondissement regroupe le secteur des Terreaux et de Tolozan ainsi que les pentes de la Croix-Rousse, au nord de la Presqu'île. Il ne compte aucune gare SNCF ni station de tramway : seules les stations de métro Hôtel de Ville-Louis Pradel (lignes A et C) et Croix-Paquet, sur les pentes, le desservent. Une partie du secteur, jusqu'au bas des pentes, est intégrée à la zone à trafic limité (ZTL) de la Presqu'île, où VTC et taxis peuvent circuler sous réserve d'enregistrement préalable auprès de la Métropole.",
      "KDRIVE organise la prise en charge selon l'adresse exacte indiquée lors de la réservation, en tenant compte de la ZTL et du relief des pentes de la Croix-Rousse.",
    ],
    quartiersTitle: "Quartiers et lieux du 1er arrondissement",
    quartiers: [
      { title: "Terreaux et Hôtel de Ville", body: "Place des Terreaux, Hôtel de Ville et Opéra de Lyon (1 place de la Comédie) : cœur institutionnel et touristique, en zone à trafic limité." },
      { title: "Opéra de Lyon", body: "Sortie de spectacle ou rendez-vous en soirée place de la Comédie, accessible par le métro A/C station Hôtel de Ville." },
      { title: "Pentes de la Croix-Rousse", body: "Secteur en dénivelé desservi par la station de métro Croix-Paquet : indiquez l'adresse précise pour faciliter la prise en charge." },
      { title: "Musée des Beaux-Arts et parking Terreaux", body: "Musée au 20 place des Terreaux ; le parking Terreaux (18 rue d'Algérie), ouvert 24h/24, reste un repère pratique pour une dépose en zone ZTL." },
    ],
    casUsageTitle: "Motifs de déplacement courants",
    casUsageItems: [
      "Rendez-vous professionnel ou administratif près de l'Hôtel de Ville.",
      "Sortie culturelle (Opéra, Musée des Beaux-Arts) en soirée.",
      "Trajet vers la gare de Perrache ou de la Part-Dieu, sans gare directe dans le 1er.",
      "Déplacement vers un autre arrondissement de Lyon.",
    ],
    frequentTrips: [
      { title: "1er arrondissement → Gare Part-Dieu", body: "Trajet vers la gare de la Part-Dieu, sur la base de votre horaire de train.", href: "/vtc-lyon-part-dieu" },
      { title: "1er arrondissement → Aéroport Lyon-Saint Exupéry", body: "Transfert direct vers l'aéroport.", href: "/transfert-aeroport" },
      { title: "1er arrondissement → 4e arrondissement", body: "Trajet court vers le plateau de la Croix-Rousse.", href: "/vtc-lyon-4e-arrondissement" },
    ],
    faq: [
      { q: "Un VTC peut-il circuler dans la ZTL de la Presqu'île depuis le 1er arrondissement ?", a: "Oui, les VTC sont autorisés dans la zone à trafic limité sous réserve d'enregistrement préalable auprès de la Métropole de Lyon." },
      { q: "Le 1er arrondissement a-t-il une gare ?", a: "Non, aucune gare SNCF ni station de tramway ne dessert le 1er arrondissement ; KDRIVE assure la liaison directe vers Perrache ou la Part-Dieu." },
      { q: "Puis-je réserver un trajet en soirée après l'Opéra ?", a: "Oui, indiquez l'horaire souhaité lors de la réservation ; la disponibilité est confirmée par KDRIVE." },
    ],
    neighborLinksTitle: "Arrondissements limitrophes",
    neighborLinks: [
      { href: "/vtc-lyon-4e-arrondissement", label: "Lyon 4e (Croix-Rousse)" },
      { href: "/vtc-lyon-2e-arrondissement", label: "Lyon 2e (Presqu'île)" },
      { href: "/vtc-lyon-6e-arrondissement", label: "Lyon 6e (Brotteaux)" },
      { href: "/zones-desservies", label: "Toutes les zones desservies" },
    ],
    pillarLinksTitle: "Poursuivre votre réservation",
    pillarLinks: [
      { href: "/transfert-gare", label: "Transfert gare" },
      { href: "/transfert-aeroport", label: "Transfert aéroport" },
      { href: "/vehicules", label: "Nos véhicules" },
      { href: "/tarifs", label: "Grille tarifaire" },
      { href: "/reserver", label: "Réserver un trajet" },
    ],
    sources: ["Dossier documentaire vérifié VTC Kdrive — Lyon 1er arrondissement (mairie1.lyon.fr, Ville de Lyon, Métropole de Lyon, TCL, LPA Mobilités), consultation du 10/09/2026."],
  },
  {
    slug: "vtc-lyon-2e-arrondissement",
    family: "arrondissement",
    editorialStatus: "readyForIndexing",
    title: "VTC Lyon 2e arrondissement | Chauffeur privé | KDRIVE",
    metaDescription: "Chauffeur privé dans le 2e arrondissement de Lyon : Bellecour, Presqu'île, Cordeliers, Confluence. Tarif confirmé avant votre course.",
    eyebrow: "VTC Lyon 2e",
    h1: "Chauffeur VTC dans le 2e arrondissement de Lyon",
    breadcrumbParent: { label: "Zones desservies", href: "/zones-desservies" },
    heroImage: "/images/hero-lyon.jpg",
    heroLead: "KDRIVE prend en charge vos trajets au départ ou à destination du 2e arrondissement de Lyon, de Bellecour à la Confluence.",
    presentationTitle: "Le cœur commerçant et central de la Presqu'île",
    presentationBody: [
      "Le 2e arrondissement couvre la partie sud de la Presqu'île : place Bellecour, Cordeliers, Ainay, le secteur de la gare de Perrache et le quartier de la Confluence. Comme le 1er, il est concerné par la zone à trafic limité (ZTL), où VTC et taxis circulent sous réserve d'enregistrement préalable ; les 18 parkings publics de la Presqu'île restent accessibles malgré la ZTL. Le secteur de Perrache est en travaux (« Ouvrons Perrache ») : la passerelle piétonne entre le centre d'échanges et la gare SNCF est fermée depuis février 2025, l'accès se faisant par le tram Place des Archives ou le passage France Péjot.",
      "KDRIVE y organise des prises en charge pour des trajets professionnels, des sorties ou des transferts vers une gare ou l'aéroport, en tenant compte de ces contraintes locales.",
    ],
    quartiersTitle: "Quartiers et lieux du 2e arrondissement",
    quartiers: [
      { title: "Bellecour et Cordeliers", body: "Secteur commerçant central, en zone à trafic limité, fréquent pour un rendez-vous en journée ou une sortie en soirée." },
      { title: "Ainay", body: "Quartier résidentiel calme au sud de la Presqu'île." },
      { title: "Gare de Perrache", body: "14 cours de Verdun : point de correspondance ferroviaire majeur, actuellement en travaux (passerelle piétonne fermée depuis février 2025)." },
      { title: "Confluence", body: "Quartier réaménagé (musée des Confluences, centre commercial), pôle de bureaux et de loisirs en développement." },
    ],
    casUsageTitle: "Motifs de déplacement courants",
    casUsageItems: [
      "Rendez-vous professionnel ou shopping autour de Bellecour.",
      "Trajet vers ou depuis la gare de Perrache.",
      "Sortie ou déplacement vers le quartier de la Confluence.",
      "Transfert vers l'aéroport ou une autre gare de Lyon.",
    ],
    frequentTrips: [
      { title: "2e arrondissement → Gare Perrache", body: "Trajet court vers la gare de Perrache.", href: "/vtc-lyon-perrache" },
      { title: "2e arrondissement → Aéroport Lyon-Saint Exupéry", body: "Transfert direct vers l'aéroport.", href: "/transfert-aeroport" },
      { title: "2e arrondissement → 3e arrondissement", body: "Trajet vers la Part-Dieu et son quartier d'affaires.", href: "/vtc-lyon-3e-arrondissement" },
    ],
    faq: [
      { q: "Un VTC peut-il circuler dans la ZTL de la Presqu'île ?", a: "Oui, sous réserve d'enregistrement préalable auprès de la Métropole de Lyon ; les parkings publics de la Presqu'île restent accessibles." },
      { q: "Les travaux de Perrache modifient-ils l'accès à la gare ?", a: "Oui, la passerelle piétonne est fermée depuis février 2025 ; l'accès se fait par le tram Place des Archives ou le passage France Péjot depuis la place Carnot." },
      { q: "KDRIVE dessert-il la Confluence ?", a: "Oui, le quartier de la Confluence est desservi comme le reste du 2e arrondissement, sur réservation." },
    ],
    neighborLinksTitle: "Arrondissements limitrophes",
    neighborLinks: [
      { href: "/vtc-lyon-3e-arrondissement", label: "Lyon 3e (Part-Dieu)" },
      { href: "/vtc-lyon-1er-arrondissement", label: "Lyon 1er (Terreaux)" },
      { href: "/vtc-lyon-perrache", label: "VTC Gare Lyon Perrache" },
      { href: "/zones-desservies", label: "Toutes les zones desservies" },
    ],
    pillarLinksTitle: "Poursuivre votre réservation",
    pillarLinks: [
      { href: "/transfert-gare", label: "Transfert gare" },
      { href: "/transfert-aeroport", label: "Transfert aéroport" },
      { href: "/vehicules", label: "Nos véhicules" },
      { href: "/tarifs", label: "Grille tarifaire" },
      { href: "/reserver", label: "Réserver un trajet" },
    ],
    sources: ["Dossier documentaire vérifié VTC Kdrive — Lyon 2e arrondissement (mairie2.lyon.fr, Ville de Lyon, Métropole de Lyon, SNCF Gares & Connexions), consultation du 10/09/2026."],
  },
  {
    slug: "vtc-lyon-3e-arrondissement",
    family: "arrondissement",
    editorialStatus: "readyForIndexing",
    title: "VTC Lyon 3e arrondissement | Chauffeur privé Part-Dieu | KDRIVE",
    metaDescription: "Chauffeur privé dans le 3e arrondissement de Lyon : Part-Dieu, Montchat, Halles de Lyon Paul Bocuse. Tarif confirmé avant votre course.",
    eyebrow: "VTC Lyon 3e",
    h1: "Chauffeur VTC dans le 3e arrondissement de Lyon",
    breadcrumbParent: { label: "Zones desservies", href: "/zones-desservies" },
    heroImage: "/images/service-affaires.jpg",
    heroLead: "KDRIVE prend en charge vos trajets au départ ou à destination du 3e arrondissement de Lyon, quartier d'affaires autour de la Part-Dieu.",
    presentationTitle: "Le plus grand arrondissement de Lyon, entre affaires et gare",
    presentationBody: [
      "Le 3e arrondissement est le plus étendu de Lyon : il regroupe le quartier d'affaires de la Part-Dieu, sa gare (5 place Charles Béraudier), ainsi que les secteurs de la Villette-Paul-Bert, de Bonnel, de Montchat et de Sept-Chemins. La gare Part-Dieu concentre TGV, TER, Eurostar, trois lignes de tramway, une ligne de métro et une gare routière, avec un accès taxis rue de la Villette et des parkings à dépose-minute (Béraudier, Villette).",
      "KDRIVE y organise des prises en charge adaptées aux rendez-vous d'affaires comme aux trajets vers la gare Part-Dieu, quelle que soit la sortie utilisée (Béraudier côté boulevard Vivier-Merle, Porte Alpes côté rue de la Villette).",
    ],
    quartiersTitle: "Quartiers et lieux du 3e arrondissement",
    quartiers: [
      { title: "Part-Dieu", body: "Quartier d'affaires et pôle multimodal majeur de la métropole lyonnaise, avec la gare éponyme, 5 place Charles Béraudier." },
      { title: "Halles de Lyon Paul Bocuse", body: "102 cours Lafayette : marché couvert bien identifié du 3e arrondissement, repère pratique pour une prise en charge." },
      { title: "Montchat", body: "Quartier résidentiel à l'est de l'arrondissement." },
      { title: "Villette-Paul-Bert", body: "Secteur mêlant logements et petites entreprises, derrière la gare Part-Dieu, mitoyen de Villeurbanne." },
    ],
    casUsageTitle: "Motifs de déplacement courants",
    casUsageItems: [
      "Rendez-vous professionnel dans le quartier d'affaires de la Part-Dieu.",
      "Trajet vers ou depuis la gare de la Part-Dieu.",
      "Déplacement depuis Montchat ou la Villette vers le centre de Lyon.",
      "Transfert vers l'aéroport ou une autre gare.",
    ],
    frequentTrips: [
      { title: "3e arrondissement → Gare Part-Dieu", body: "Trajet court vers la gare, sur la base de votre horaire de train.", href: "/vtc-lyon-part-dieu" },
      { title: "3e arrondissement → Aéroport Lyon-Saint Exupéry", body: "Transfert direct vers l'aéroport.", href: "/transfert-aeroport" },
      { title: "3e arrondissement → Villeurbanne", body: "Trajet vers la commune limitrophe de Villeurbanne.", href: "/vtc-villeurbanne" },
    ],
    faq: [
      { q: "Où se fait la prise en charge à la gare Part-Dieu ?", a: "L'accès taxis se fait rue de la Villette ; des dépose-minute existent aussi aux parkings Béraudier et Villette, à proximité immédiate de la gare." },
      { q: "Quel véhicule pour un rendez-vous professionnel à la Part-Dieu ?", a: "La catégorie Premium est recommandée pour un rendez-vous d'affaires ; Essentiel convient pour un trajet simple." },
      { q: "KDRIVE dessert-il aussi Montchat et Villette-Paul-Bert ?", a: "Oui, ces secteurs du 3e arrondissement sont desservis comme le reste de l'arrondissement, sur réservation." },
    ],
    neighborLinksTitle: "Arrondissements limitrophes",
    neighborLinks: [
      { href: "/vtc-lyon-6e-arrondissement", label: "Lyon 6e (Brotteaux)" },
      { href: "/vtc-lyon-7e-arrondissement", label: "Lyon 7e (Gerland)" },
      { href: "/vtc-villeurbanne", label: "VTC Villeurbanne" },
      { href: "/zones-desservies", label: "Toutes les zones desservies" },
    ],
    pillarLinksTitle: "Poursuivre votre réservation",
    pillarLinks: [
      { href: "/chauffeur-entreprise", label: "Chauffeur entreprise" },
      { href: "/transfert-gare", label: "Transfert gare" },
      { href: "/vehicules", label: "Nos véhicules" },
      { href: "/tarifs", label: "Grille tarifaire" },
      { href: "/reserver", label: "Réserver un trajet" },
    ],
    sources: ["Dossier documentaire vérifié VTC Kdrive — Lyon 3e arrondissement (mairie3.lyon.fr, SNCF Gares & Connexions, SPL Lyon Part-Dieu, LPA Mobilités), consultation du 10/09/2026."],
  },
  {
    slug: "vtc-lyon-4e-arrondissement",
    family: "arrondissement",
    editorialStatus: "readyForIndexing",
    title: "VTC Lyon 4e arrondissement | Chauffeur privé Croix-Rousse | KDRIVE",
    metaDescription: "Chauffeur privé dans le 4e arrondissement de Lyon : plateau de la Croix-Rousse, Gros Caillou. Tarif confirmé avant votre course.",
    eyebrow: "VTC Lyon 4e",
    h1: "Chauffeur VTC dans le 4e arrondissement de Lyon",
    breadcrumbParent: { label: "Zones desservies", href: "/zones-desservies" },
    heroImage: "/images/hero-lyon.jpg",
    heroLead: "KDRIVE prend en charge vos trajets au départ ou à destination du 4e arrondissement de Lyon, sur le plateau de la Croix-Rousse.",
    presentationTitle: "Le plateau de la Croix-Rousse, entre habitat et patrimoine",
    presentationBody: [
      "Le 4e arrondissement correspond au plateau de la Croix-Rousse — distinct des pentes, situées dans le 1er. Il n'a qu'une seule ligne de métro (la ligne C, stations Croix-Rousse et Hénon) et aucune gare SNCF. Le boulevard de la Croix-Rousse, à cheval sur le 1er et le 4e, accueille un marché alimentaire très fréquenté (mardi, vendredi, samedi, dimanche) et, chaque automne, la Vogue des marrons.",
      "KDRIVE organise la prise en charge selon l'adresse exacte indiquée, en tenant compte du relief du plateau et de l'absence de desserte ferroviaire directe.",
    ],
    quartiersTitle: "Quartiers et lieux du 4e arrondissement",
    quartiers: [
      { title: "Plateau de la Croix-Rousse", body: "Quartier résidentiel en hauteur, connu pour son marché (boulevard de la Croix-Rousse) et son patrimoine canut (Maison des Canuts, 10-12 rue d'Ivry)." },
      { title: "Gros Caillou", body: "196 boulevard de la Croix-Rousse, à la station de métro Croix-Rousse : repère pratique pour une prise en charge." },
      { title: "Hôpital de la Croix-Rousse", body: "103 Grande Rue de la Croix-Rousse (HCL), cité ici comme lieu de déplacement ordinaire." },
    ],
    casUsageTitle: "Motifs de déplacement courants",
    casUsageItems: [
      "Trajet résidentiel depuis ou vers le plateau de la Croix-Rousse.",
      "Déplacement lié à un rendez-vous à l'hôpital de la Croix-Rousse.",
      "Trajet vers le centre de Lyon ou une gare.",
    ],
    frequentTrips: [
      { title: "4e arrondissement → 1er arrondissement", body: "Trajet vers les Terreaux, en contrebas du plateau.", href: "/vtc-lyon-1er-arrondissement" },
      { title: "4e arrondissement → Gare Part-Dieu", body: "Transfert vers la gare de la Part-Dieu.", href: "/vtc-lyon-part-dieu" },
      { title: "4e arrondissement → Aéroport Lyon-Saint Exupéry", body: "Transfert direct vers l'aéroport.", href: "/transfert-aeroport" },
    ],
    faq: [
      { q: "Le plateau de la Croix-Rousse a-t-il une gare ou un tramway ?", a: "Non, seule la ligne de métro C dessert le plateau (stations Croix-Rousse et Hénon) ; KDRIVE évite les correspondances vers Part-Dieu ou l'aéroport." },
      { q: "Les rues en pente posent-elles une difficulté pour la prise en charge ?", a: "Indiquez l'adresse exacte lors de la réservation : le point de prise en charge est confirmé selon l'accès possible au véhicule." },
      { q: "Puis-je réserver un trajet vers l'hôpital de la Croix-Rousse ?", a: "Oui, ce type de trajet est traité comme toute autre demande de VTC dans le secteur." },
    ],
    neighborLinksTitle: "Arrondissements limitrophes",
    neighborLinks: [
      { href: "/vtc-lyon-1er-arrondissement", label: "Lyon 1er (Terreaux)" },
      { href: "/vtc-lyon-9e-arrondissement", label: "Lyon 9e (Vaise)" },
      { href: "/zones-desservies", label: "Toutes les zones desservies" },
    ],
    pillarLinksTitle: "Poursuivre votre réservation",
    pillarLinks: [
      { href: "/transfert-gare", label: "Transfert gare" },
      { href: "/transfert-aeroport", label: "Transfert aéroport" },
      { href: "/vehicules", label: "Nos véhicules" },
      { href: "/tarifs", label: "Grille tarifaire" },
      { href: "/reserver", label: "Réserver un trajet" },
    ],
    sources: ["Dossier documentaire vérifié VTC Kdrive — Lyon 4e arrondissement (mairie4.lyon.fr, Ville de Lyon, TCL, HCL), consultation du 10/09/2026."],
  },
  {
    slug: "vtc-lyon-5e-arrondissement",
    family: "arrondissement",
    editorialStatus: "readyForIndexing",
    title: "VTC Lyon 5e arrondissement | Chauffeur privé Vieux Lyon | KDRIVE",
    metaDescription: "Chauffeur privé dans le 5e arrondissement de Lyon : Vieux Lyon, Fourvière, Point-du-Jour. Tarif confirmé avant votre course.",
    eyebrow: "VTC Lyon 5e",
    h1: "Chauffeur VTC dans le 5e arrondissement de Lyon",
    breadcrumbParent: { label: "Zones desservies", href: "/zones-desservies" },
    heroImage: "/images/about-lyon.jpg",
    heroLead: "KDRIVE prend en charge vos trajets au départ ou à destination du 5e arrondissement de Lyon, du Vieux Lyon à Fourvière.",
    presentationTitle: "Le Lyon historique, entre Vieux Lyon et colline de Fourvière",
    presentationBody: [
      "Le 5e arrondissement regroupe le Vieux Lyon (secteurs Saint-Paul, Saint-Jean, Saint-Georges), la colline de Fourvière et sa basilique, ainsi que des quartiers résidentiels comme Point-du-Jour, Ménival et Champvert. Plusieurs rues du Vieux Lyon sont en zone piétonne : certains établissements y indiquent un point d'accès véhicule distinct de leur adresse postale. La gare de Lyon-Saint-Paul (11 bis place Saint-Paul) dessert l'Ouest lyonnais, mais pas directement Part-Dieu ni Perrache.",
      "KDRIVE organise la prise en charge au point d'accès le plus proche de la zone piétonne du Vieux Lyon, et tient compte du relief de la colline de Fourvière.",
    ],
    quartiersTitle: "Quartiers et lieux du 5e arrondissement",
    quartiers: [
      { title: "Vieux Lyon / Saint-Jean", body: "Quartier historique classé UNESCO, ruelles et traboules, en partie en zone piétonne : précisez votre point de rendez-vous exact." },
      { title: "Fourvière", body: "Colline emblématique de Lyon (basilique, théâtres romains) ; le stationnement autour du site est limité, le parking de la basilique n'ouvrant que le soir." },
      { title: "Gare de Lyon-Saint-Paul", body: "11 bis place Saint-Paul : dessert l'Ouest lyonnais, sans liaison directe vers Part-Dieu ou Perrache." },
      { title: "Point-du-Jour, Ménival, Champvert", body: "Quartiers résidentiels de l'ouest du 5e arrondissement." },
    ],
    casUsageTitle: "Motifs de déplacement courants",
    casUsageItems: [
      "Trajet touristique ou professionnel vers le Vieux Lyon ou Fourvière.",
      "Déplacement résidentiel depuis Point-du-Jour.",
      "Trajet vers le centre de Lyon, une gare ou l'aéroport.",
    ],
    frequentTrips: [
      { title: "5e arrondissement → 2e arrondissement", body: "Trajet vers la Presqu'île, de l'autre côté de la Saône.", href: "/vtc-lyon-2e-arrondissement" },
      { title: "5e arrondissement → Gare Perrache", body: "Transfert vers la gare de Perrache.", href: "/vtc-lyon-perrache" },
      { title: "5e arrondissement → Aéroport Lyon-Saint Exupéry", body: "Transfert direct vers l'aéroport.", href: "/transfert-aeroport" },
    ],
    faq: [
      { q: "KDRIVE peut-il prendre en charge dans le Vieux Lyon malgré les rues piétonnes ?", a: "Le point de prise en charge est confirmé avec vous au point d'accès véhicule le plus proche de la zone piétonne." },
      { q: "La gare Saint-Paul dessert-elle Part-Dieu ou Perrache ?", a: "Non, elle dessert l'Ouest lyonnais ; KDRIVE assure la liaison directe vers les deux autres gares." },
      { q: "Puis-je réserver un trajet touristique vers Fourvière ?", a: "Oui, indiquez votre besoin lors de la réservation ; KDRIVE confirme le tarif et la disponibilité par téléphone." },
    ],
    neighborLinksTitle: "Arrondissements limitrophes",
    neighborLinks: [
      { href: "/vtc-lyon-2e-arrondissement", label: "Lyon 2e (Presqu'île)" },
      { href: "/vtc-lyon-9e-arrondissement", label: "Lyon 9e (Vaise)" },
      { href: "/zones-desservies", label: "Toutes les zones desservies" },
    ],
    pillarLinksTitle: "Poursuivre votre réservation",
    pillarLinks: [
      { href: "/transfert-gare", label: "Transfert gare" },
      { href: "/transfert-aeroport", label: "Transfert aéroport" },
      { href: "/vehicules", label: "Nos véhicules" },
      { href: "/tarifs", label: "Grille tarifaire" },
      { href: "/reserver", label: "Réserver un trajet" },
    ],
    sources: ["Dossier documentaire vérifié VTC Kdrive — Lyon 5e arrondissement (mairie5.lyon.fr, Ville de Lyon, SNCF Gares & Connexions, fourviere.org), consultation du 10/09/2026."],
  },
  {
    slug: "vtc-lyon-6e-arrondissement",
    family: "arrondissement",
    editorialStatus: "readyForIndexing",
    title: "VTC Lyon 6e arrondissement | Chauffeur privé Brotteaux | KDRIVE",
    metaDescription: "Chauffeur privé dans le 6e arrondissement de Lyon : Brotteaux, Parc de la Tête d'Or, Cité Internationale. Tarif confirmé avant votre course.",
    eyebrow: "VTC Lyon 6e",
    h1: "Chauffeur VTC dans le 6e arrondissement de Lyon",
    breadcrumbParent: { label: "Zones desservies", href: "/zones-desservies" },
    heroImage: "/images/service-vip.jpg",
    heroLead: "KDRIVE prend en charge vos trajets au départ ou à destination du 6e arrondissement de Lyon, entre Brotteaux et Cité Internationale.",
    presentationTitle: "Un arrondissement résidentiel et institutionnel, en bord de parc",
    presentationBody: [
      "Le 6e arrondissement regroupe le quartier des Brotteaux, le Parc de la Tête d'Or (105 hectares, 7 entrées) et la Cité Internationale, qui accueille le Centre de Congrès de Lyon (50 quai Charles de Gaulle). La gare des Brotteaux, elle, est fermée aux voyageurs depuis 1983 : les trains s'arrêtent désormais à la gare Part-Dieu, à 600 mètres de là. Aucune station Rhônexpress ne dessert le 6e, la navette vers l'aéroport partant de Part-Dieu.",
      "KDRIVE y organise des prises en charge adaptées aux rendez-vous professionnels comme aux trajets résidentiels, sans passer par une correspondance à Part-Dieu.",
    ],
    quartiersTitle: "Quartiers et lieux du 6e arrondissement",
    quartiers: [
      { title: "Brotteaux", body: "Quartier résidentiel haussmannien ; l'ancienne gare des Brotteaux, fermée depuis 1983, reste un repère patrimonial." },
      { title: "Parc de la Tête d'Or", body: "Grand parc urbain (105 hectares), point de repère fréquent pour une prise en charge, notamment place Général Leclerc." },
      { title: "Cité Internationale", body: "Centre de Congrès de Lyon (50 quai Charles de Gaulle) et hôtels associés, en bordure du parc." },
    ],
    casUsageTitle: "Motifs de déplacement courants",
    casUsageItems: [
      "Rendez-vous ou événement professionnel à la Cité Internationale.",
      "Trajet résidentiel depuis le quartier des Brotteaux.",
      "Trajet vers le centre de Lyon, une gare ou l'aéroport.",
    ],
    frequentTrips: [
      { title: "6e arrondissement → Gare Part-Dieu", body: "Trajet vers la gare de la Part-Dieu.", href: "/vtc-lyon-part-dieu" },
      { title: "6e arrondissement → 3e arrondissement", body: "Trajet vers le quartier d'affaires de la Part-Dieu.", href: "/vtc-lyon-3e-arrondissement" },
      { title: "6e arrondissement → Aéroport Lyon-Saint Exupéry", body: "Transfert direct vers l'aéroport.", href: "/transfert-aeroport" },
    ],
    faq: [
      { q: "Peut-on prendre un train à la gare des Brotteaux ?", a: "Non, elle est fermée aux voyageurs depuis 1983 ; les trains partent de la gare Part-Dieu, à 600 mètres." },
      { q: "Le Rhônexpress dessert-il le 6e arrondissement ?", a: "Non, la navette vers l'aéroport part uniquement de la gare Part-Dieu ; KDRIVE assure la liaison directe sans ce rabattement." },
      { q: "Quel véhicule pour un rendez-vous professionnel à la Cité Internationale ?", a: "La catégorie Premium est recommandée pour ce type de rendez-vous." },
    ],
    neighborLinksTitle: "Arrondissements limitrophes",
    neighborLinks: [
      { href: "/vtc-lyon-3e-arrondissement", label: "Lyon 3e (Part-Dieu)" },
      { href: "/vtc-lyon-1er-arrondissement", label: "Lyon 1er (Terreaux)" },
      { href: "/vtc-villeurbanne", label: "VTC Villeurbanne" },
      { href: "/zones-desservies", label: "Toutes les zones desservies" },
    ],
    pillarLinksTitle: "Poursuivre votre réservation",
    pillarLinks: [
      { href: "/chauffeur-entreprise", label: "Chauffeur entreprise" },
      { href: "/transfert-gare", label: "Transfert gare" },
      { href: "/vehicules", label: "Nos véhicules" },
      { href: "/tarifs", label: "Grille tarifaire" },
      { href: "/reserver", label: "Réserver un trajet" },
    ],
    sources: ["Dossier documentaire vérifié VTC Kdrive — Lyon 6e arrondissement (mairie6.lyon.fr, Ville de Lyon, Rhônexpress), consultation du 10/09/2026."],
  },
  {
    slug: "vtc-lyon-7e-arrondissement",
    family: "arrondissement",
    editorialStatus: "readyForIndexing",
    title: "VTC Lyon 7e arrondissement | Chauffeur privé Gerland | KDRIVE",
    metaDescription: "Chauffeur privé dans le 7e arrondissement de Lyon : Gerland, Guillotière, Jean Macé, Halle Tony Garnier. Tarif confirmé avant votre course.",
    eyebrow: "VTC Lyon 7e",
    h1: "Chauffeur VTC dans le 7e arrondissement de Lyon",
    breadcrumbParent: { label: "Zones desservies", href: "/zones-desservies" },
    heroImage: "/images/hero-lyon.jpg",
    heroLead: "KDRIVE prend en charge vos trajets au départ ou à destination du 7e arrondissement de Lyon, de la Guillotière à Gerland.",
    presentationTitle: "Entre quartier universitaire, biodistrict et grande salle de spectacle",
    presentationBody: [
      "Le 7e arrondissement s'étend de la Guillotière, quartier dense et multiculturel proche du centre, jusqu'à Gerland, pôle universitaire et scientifique (ENS de Lyon) accueillant aussi la Halle Tony Garnier. Depuis janvier 2026, la gare routière longue distance de Lyon (FlixBus, BlaBlaBus, Itabus) est installée à Gerland.",
      "KDRIVE y organise des prises en charge pour des trajets étudiants, professionnels ou événementiels (concerts, spectacles à la Halle Tony Garnier).",
    ],
    quartiersTitle: "Quartiers et lieux du 7e arrondissement",
    quartiers: [
      { title: "Guillotière", body: "Quartier central et multiculturel, à la frontière du 3e arrondissement." },
      { title: "Jean Macé", body: "Quartier résidentiel et commerçant, bien desservi par les transports." },
      { title: "Gerland", body: "Pôle universitaire et scientifique (ENS de Lyon), avec la Halle Tony Garnier et la gare routière longue distance depuis janvier 2026." },
      { title: "Halle Tony Garnier", body: "20 place des Docteurs Mérieux : grande salle de concerts et d'événements, dont l'accès est actuellement perturbé par le chantier du futur tramway T10." },
      { title: "Gare de Lyon-Jean-Macé", body: "Place Jean Macé, ouverte du lundi au samedi de 5h30 à 21h30 (dès 8h le dimanche et les jours fériés)." },
    ],
    casUsageTitle: "Motifs de déplacement courants",
    casUsageItems: [
      "Trajet de ou vers un concert ou événement à la Halle Tony Garnier.",
      "Déplacement universitaire ou professionnel vers Gerland.",
      "Trajet vers la gare routière longue distance de Gerland.",
      "Trajet vers le centre de Lyon depuis la Guillotière ou Jean Macé.",
    ],
    frequentTrips: [
      { title: "7e arrondissement → Gare Perrache", body: "Trajet vers la gare de Perrache, à proximité du 7e arrondissement.", href: "/vtc-lyon-perrache" },
      { title: "7e arrondissement → Aéroport Lyon-Saint Exupéry", body: "Transfert direct vers l'aéroport.", href: "/transfert-aeroport" },
      { title: "7e arrondissement → Gare Part-Dieu", body: "Trajet vers la gare de la Part-Dieu.", href: "/vtc-lyon-part-dieu" },
    ],
    faq: [
      { q: "KDRIVE dessert-il la gare routière de Gerland ?", a: "Oui, KDRIVE organise des trajets de et vers la gare routière longue distance de Gerland, installée depuis janvier 2026." },
      { q: "KDRIVE dessert-il un concert à la Halle Tony Garnier ?", a: "Oui, le point de rendez-vous est confirmé avec vous selon les dispositifs d'accès en vigueur le soir de l'événement." },
      { q: "KDRIVE dessert-il tout le 7e arrondissement ?", a: "KDRIVE prend en charge les demandes dans le 7e arrondissement au cas par cas ; chaque demande est confirmée individuellement par l'équipe avant la course." },
    ],
    neighborLinksTitle: "Arrondissements limitrophes",
    neighborLinks: [
      { href: "/vtc-lyon-3e-arrondissement", label: "Lyon 3e (Part-Dieu)" },
      { href: "/vtc-lyon-2e-arrondissement", label: "Lyon 2e (Presqu'île)" },
      { href: "/vtc-lyon-8e-arrondissement", label: "Lyon 8e (Monplaisir)" },
      { href: "/zones-desservies", label: "Toutes les zones desservies" },
    ],
    pillarLinksTitle: "Poursuivre votre réservation",
    pillarLinks: [
      { href: "/transfert-gare", label: "Transfert gare" },
      { href: "/vtc-halle-tony-garnier", label: "VTC Halle Tony Garnier" },
      { href: "/vehicules", label: "Nos véhicules" },
      { href: "/tarifs", label: "Grille tarifaire" },
      { href: "/reserver", label: "Réserver un trajet" },
    ],
    sources: ["Dossier documentaire vérifié VTC Kdrive — Lyon 7e arrondissement (mairie7.lyon.fr, Métropole de Lyon, Ville de Lyon, halle-tony-garnier.com), consultation du 10/09/2026."],
  },
  {
    slug: "vtc-lyon-8e-arrondissement",
    family: "arrondissement",
    editorialStatus: "readyForIndexing",
    title: "VTC Lyon 8e arrondissement | Chauffeur privé Monplaisir | KDRIVE",
    metaDescription: "Chauffeur privé dans le 8e arrondissement de Lyon : Monplaisir, Institut Lumière, Grange-Blanche. Tarif confirmé avant votre course.",
    eyebrow: "VTC Lyon 8e",
    h1: "Chauffeur VTC dans le 8e arrondissement de Lyon",
    breadcrumbParent: { label: "Zones desservies", href: "/zones-desservies" },
    heroImage: "/images/hero-lyon.jpg",
    heroLead: "KDRIVE prend en charge vos trajets au départ ou à destination du 8e arrondissement de Lyon, de Monplaisir à Grange-Blanche.",
    presentationTitle: "Un arrondissement résidentiel, entre patrimoine du cinéma et pôle hospitalier",
    presentationBody: [
      "Le 8e arrondissement regroupe les quartiers de Monplaisir (Institut Lumière, 25 rue du Premier-Film), Mermoz, Laënnec et États-Unis, ainsi que le secteur de Grange-Blanche, pôle multimodal (métro D, trams T2 et T5) en limite du 3e arrondissement où se trouve l'hôpital Édouard Herriot. Le tramway T5 relie directement Grange-Blanche au parc des expositions Eurexpo.",
      "KDRIVE y organise des prises en charge résidentielles comme des trajets liés à un rendez-vous médical ou à un salon à Eurexpo, sans que cela ne constitue une spécialisation particulière.",
    ],
    quartiersTitle: "Quartiers et lieux du 8e arrondissement",
    quartiers: [
      { title: "Monplaisir", body: "Quartier résidentiel connu pour l'Institut Lumière (25 rue du Premier-Film), lié à l'histoire du cinéma." },
      { title: "Mermoz, Laënnec et États-Unis", body: "Quartiers résidentiels du 8e arrondissement, desservis par la ligne de métro D." },
      { title: "Grange-Blanche", body: "Pôle multimodal (métro D, trams T2 et T5) accueillant l'hôpital Édouard Herriot, cité ici comme lieu de déplacement ordinaire, à la limite du 3e arrondissement." },
    ],
    casUsageTitle: "Motifs de déplacement courants",
    casUsageItems: [
      "Trajet résidentiel depuis Monplaisir, Mermoz ou États-Unis.",
      "Déplacement lié à un rendez-vous médical à Grange-Blanche.",
      "Trajet vers le centre de Lyon, une gare ou l'aéroport.",
    ],
    frequentTrips: [
      { title: "8e arrondissement → Gare Part-Dieu", body: "Trajet vers la gare de la Part-Dieu.", href: "/vtc-lyon-part-dieu" },
      { title: "8e arrondissement → Aéroport Lyon-Saint Exupéry", body: "Transfert direct vers l'aéroport, axe est de la métropole.", href: "/transfert-aeroport" },
      { title: "8e arrondissement → Bron", body: "Trajet vers la commune limitrophe de Bron.", href: "/vtc-bron" },
    ],
    faq: [
      { q: "L'hôpital Édouard Herriot est-il dans le 8e arrondissement ?", a: "Non, il est dans le 3e (5 place d'Arsonval), même si son accès se fait par la station Grange-Blanche, en limite du 8e." },
      { q: "Comment rejoindre Eurexpo depuis le 8e arrondissement ?", a: "Le tramway T5 relie directement Grange-Blanche à Eurexpo ; KDRIVE peut assurer ce trajet sans dépendre des horaires du tram." },
      { q: "KDRIVE dessert-il un trajet vers l'aéroport depuis Monplaisir ?", a: "Oui, un transfert direct est possible ; aucun délai n'est garanti à l'avance, la durée dépend du trafic." },
    ],
    neighborLinksTitle: "Arrondissements limitrophes",
    neighborLinks: [
      { href: "/vtc-lyon-7e-arrondissement", label: "Lyon 7e (Gerland)" },
      { href: "/vtc-lyon-3e-arrondissement", label: "Lyon 3e (Part-Dieu)" },
      { href: "/vtc-bron", label: "VTC Bron" },
      { href: "/zones-desservies", label: "Toutes les zones desservies" },
    ],
    pillarLinksTitle: "Poursuivre votre réservation",
    pillarLinks: [
      { href: "/transfert-gare", label: "Transfert gare" },
      { href: "/transfert-aeroport", label: "Transfert aéroport" },
      { href: "/vehicules", label: "Nos véhicules" },
      { href: "/tarifs", label: "Grille tarifaire" },
      { href: "/reserver", label: "Réserver un trajet" },
    ],
    sources: ["Dossier documentaire vérifié VTC Kdrive — Lyon 8e arrondissement (mairie8.lyon.fr, Ville de Lyon, CHU de Lyon / HCL), consultation du 10/09/2026."],
  },
  {
    slug: "vtc-lyon-9e-arrondissement",
    family: "arrondissement",
    editorialStatus: "readyForIndexing",
    title: "VTC Lyon 9e arrondissement | Chauffeur privé Vaise | KDRIVE",
    metaDescription: "Chauffeur privé dans le 9e arrondissement de Lyon : Vaise, Gorge de Loup, La Duchère. Tarif confirmé avant votre course.",
    eyebrow: "VTC Lyon 9e",
    h1: "Chauffeur VTC dans le 9e arrondissement de Lyon",
    breadcrumbParent: { label: "Zones desservies", href: "/zones-desservies" },
    heroImage: "/images/hero-lyon.jpg",
    heroLead: "KDRIVE prend en charge vos trajets au départ ou à destination du 9e arrondissement de Lyon, de Vaise à La Duchère.",
    presentationTitle: "Un pôle d'activité au nord-ouest de Lyon, en bord de Saône",
    presentationBody: [
      "Le 9e arrondissement regroupe Vaise, quartier historique du numérique lyonnais et pôle de bureaux en bord de Saône, le nœud de transport de Gorge de Loup, le plateau de La Duchère — non desservi par le métro, avec six lignes de bus et la gare de Vaise à proximité — ainsi que Saint-Rambert et l'Île Barbe, où le pont est fermé à la circulation automobile depuis 2020. Aucune station Rhônexpress ne dessert le 9e : la navette vers l'aéroport part de Part-Dieu.",
      "KDRIVE y organise des prises en charge pour des trajets professionnels comme résidentiels, y compris vers les secteurs les moins bien desservis du plateau.",
    ],
    quartiersTitle: "Quartiers et lieux du 9e arrondissement",
    quartiers: [
      { title: "Vaise", body: "Pôle de bureaux et d'activité en bord de Saône, avec la gare de Lyon-Vaise (2 place de Paris), repère pour un trajet professionnel ou une correspondance TER." },
      { title: "Gorge de Loup", body: "Nœud de transport (métro ligne D) du 9e arrondissement." },
      { title: "La Duchère", body: "Plateau résidentiel en renouvellement urbain, non desservi par le métro ; la gare de Vaise se trouve à environ cinq minutes." },
      { title: "Saint-Rambert et Île Barbe", body: "Secteur au bord de la Saône ; le pont de l'Île Barbe est fermé à la circulation automobile depuis 2020, hors desserte de l'île." },
    ],
    casUsageTitle: "Motifs de déplacement courants",
    casUsageItems: [
      "Rendez-vous professionnel à Vaise.",
      "Trajet résidentiel depuis La Duchère ou le secteur de Gorge de Loup.",
      "Trajet vers le centre de Lyon, une gare ou l'aéroport.",
    ],
    frequentTrips: [
      { title: "9e arrondissement → 1er arrondissement", body: "Trajet vers les Terreaux, au sud du 9e arrondissement.", href: "/vtc-lyon-1er-arrondissement" },
      { title: "9e arrondissement → Gare Part-Dieu", body: "Trajet vers la gare de la Part-Dieu.", href: "/vtc-lyon-part-dieu" },
      { title: "9e arrondissement → Aéroport Lyon-Saint Exupéry", body: "Transfert direct vers l'aéroport.", href: "/transfert-aeroport" },
    ],
    faq: [
      { q: "Le Rhônexpress passe-t-il par le 9e arrondissement ?", a: "Non, la navette vers l'aéroport part uniquement de la gare Part-Dieu ; KDRIVE assure la liaison directe sans ce rabattement." },
      { q: "La Duchère est-elle desservie par le métro ?", a: "Non, le plateau n'a pas de station de métro ; il est desservi par six lignes de bus, la gare de Vaise étant à environ cinq minutes." },
      { q: "Peut-on accéder à l'Île Barbe en voiture ?", a: "Non, le pont est fermé à la circulation automobile depuis 2020, hors desserte des riverains de l'île." },
    ],
    neighborLinksTitle: "Arrondissements limitrophes",
    neighborLinks: [
      { href: "/vtc-lyon-1er-arrondissement", label: "Lyon 1er (Terreaux)" },
      { href: "/vtc-lyon-4e-arrondissement", label: "Lyon 4e (Croix-Rousse)" },
      { href: "/vtc-lyon-5e-arrondissement", label: "Lyon 5e (Vieux Lyon)" },
      { href: "/zones-desservies", label: "Toutes les zones desservies" },
    ],
    pillarLinksTitle: "Poursuivre votre réservation",
    pillarLinks: [
      { href: "/chauffeur-entreprise", label: "Chauffeur entreprise" },
      { href: "/transfert-gare", label: "Transfert gare" },
      { href: "/vehicules", label: "Nos véhicules" },
      { href: "/tarifs", label: "Grille tarifaire" },
      { href: "/reserver", label: "Réserver un trajet" },
    ],
    sources: ["Dossier documentaire vérifié VTC Kdrive — Lyon 9e arrondissement (mairie9.lyon.fr, SNCF Gares & Connexions, TCL, Rhônexpress), consultation du 10/09/2026."],
  },
];
