import type { LocalPageContent } from "./local-page-template";

/**
 * Communes de la métropole de Lyon (hors Villeurbanne / Bron / Saint-Priest,
 * déjà couvertes dans local-pages-content.ts). Regroupement par hub de
 * banlieue à titre commercial uniquement (cf. banlieue-hubs-content.ts) —
 * ce n'est pas un découpage administratif officiel. Faits locaux basés sur
 * une connaissance générale publique, à consolider auprès des sites
 * officiels des communes et de la Métropole de Lyon avant indexation large.
 */

const standardPillarLinks: LocalPageContent["pillarLinks"] = [
  { href: "/transfert-aeroport", label: "Transfert aéroport" },
  { href: "/transfert-gare", label: "Transfert gare" },
  { href: "/vehicules", label: "Nos véhicules" },
  { href: "/tarifs", label: "Grille tarifaire" },
  { href: "/reserver", label: "Réserver un trajet" },
];

export const communesPages: LocalPageContent[] = [
  // --- Banlieue est ---
  {
    slug: "vtc-vaulx-en-velin",
    family: "commune",
    editorialStatus: "needsEnrichment",
    title: "VTC Vaulx-en-Velin | Chauffeur privé | KDRIVE",
    metaDescription: "Chauffeur privé à Vaulx-en-Velin : trajets vers Lyon, l'aéroport et les campus universitaires. Tarif confirmé avant votre course.",
    eyebrow: "VTC Vaulx-en-Velin",
    h1: "Chauffeur privé à Vaulx-en-Velin",
    breadcrumbParent: { label: "Banlieue est", href: "/vtc-banlieue-est-lyon" },
    heroImage: "/images/hero-lyon.jpg",
    heroLead: "KDRIVE dessert Vaulx-en-Velin pour vos trajets vers Lyon, l'aéroport ou une gare, sur réservation.",
    presentationTitle: "KDRIVE dessert Vaulx-en-Velin",
    presentationBody: [
      "Vaulx-en-Velin se situe à l'est de la métropole lyonnaise, entre Villeurbanne et l'aéroport. La commune accueille plusieurs établissements d'enseignement supérieur (dont l'ENTPE) et un secteur résidentiel en renouvellement urbain autour du Mas du Taureau.",
      "KDRIVE y assure des prises en charge pour des trajets étudiants, professionnels ou vers l'aéroport, chaque demande étant confirmée individuellement.",
    ],
    quartiersTitle: "Repères à Vaulx-en-Velin",
    quartiers: [
      { title: "Campus universitaires", body: "La commune accueille des établissements d'enseignement supérieur, générant des trajets réguliers vers Lyon." },
      { title: "Mas du Taureau", body: "Quartier résidentiel en renouvellement urbain." },
      { title: "Grand Parc / Anneau Bleu", body: "Secteur de loisirs au bord de l'eau, repère géographique de la commune." },
    ],
    casUsageTitle: "Motifs de déplacement courants",
    casUsageItems: [
      "Trajet étudiant vers un campus lyonnais.",
      "Déplacement professionnel vers Villeurbanne ou Lyon.",
      "Transfert vers l'aéroport ou une gare de Lyon.",
    ],
    frequentTrips: [
      { title: "Vaulx-en-Velin → Villeurbanne", body: "Trajet vers la commune limitrophe de Villeurbanne.", href: "/vtc-villeurbanne" },
      { title: "Vaulx-en-Velin → Aéroport Lyon-Saint Exupéry", body: "Transfert vers l'aéroport, à l'est de la métropole.", href: "/transfert-aeroport" },
      { title: "Vaulx-en-Velin → Gare Part-Dieu", body: "Trajet vers la gare de la Part-Dieu.", href: "/vtc-lyon-part-dieu" },
    ],
    faq: [
      { q: "KDRIVE dessert-il tout Vaulx-en-Velin ?", a: "KDRIVE prend en charge les demandes à Vaulx-en-Velin au cas par cas ; chaque demande est confirmée individuellement par l'équipe avant la course." },
      { q: "KDRIVE dessert-il les campus universitaires de la commune ?", a: "Oui, un trajet étudiant est traité comme toute autre demande de VTC." },
      { q: "Quel délai pour rejoindre l'aéroport depuis Vaulx-en-Velin ?", a: "Aucun délai n'est garanti à l'avance ; la durée dépend du trafic au moment du trajet." },
    ],
    neighborLinksTitle: "Communes voisines",
    neighborLinks: [
      { href: "/vtc-banlieue-est-lyon", label: "Banlieue est de Lyon" },
      { href: "/vtc-villeurbanne", label: "VTC Villeurbanne" },
      { href: "/vtc-decines-charpieu", label: "VTC Décines-Charpieu" },
    ],
    pillarLinksTitle: "Poursuivre votre réservation",
    pillarLinks: standardPillarLinks,
    sources: ["Connaissance générale de Vaulx-en-Velin (ENTPE, Mas du Taureau, Grand Parc) — à consolider auprès de vaulx-en-velin.net."],
  },
  {
    slug: "vtc-decines-charpieu",
    family: "commune",
    editorialStatus: "needsEnrichment",
    title: "VTC Décines-Charpieu | Chauffeur privé | KDRIVE",
    metaDescription: "Chauffeur privé à Décines-Charpieu : trajets vers Lyon, le Groupama Stadium, la LDLC Arena et l'aéroport. Tarif confirmé avant votre course.",
    eyebrow: "VTC Décines-Charpieu",
    h1: "Chauffeur privé à Décines-Charpieu",
    breadcrumbParent: { label: "Banlieue est", href: "/vtc-banlieue-est-lyon" },
    heroImage: "/images/hero-lyon.jpg",
    heroLead: "KDRIVE dessert Décines-Charpieu, commune qui accueille le Groupama Stadium et la LDLC Arena, pour vos trajets vers Lyon ou l'aéroport.",
    presentationTitle: "KDRIVE dessert Décines-Charpieu",
    presentationBody: [
      "Décines-Charpieu, à l'est de la métropole, accueille deux grands équipements : le Groupama Stadium (football) et la LDLC Arena (salle omnisports). Ces équipements génèrent des trajets ponctuels importants les soirs d'événement.",
      "KDRIVE y assure aussi des prises en charge résidentielles et professionnelles classiques, en dehors des soirs de match ou de concert.",
    ],
    quartiersTitle: "Repères à Décines-Charpieu",
    quartiers: [
      { title: "Groupama Stadium", body: "Stade accueillant des matchs et concerts, générateur de trajets ponctuels." },
      { title: "LDLC Arena", body: "Salle omnisports (basket, spectacles), à proximité du Groupama Stadium." },
      { title: "Centre-ville de Décines", body: "Secteur résidentiel de la commune." },
    ],
    casUsageTitle: "Motifs de déplacement courants",
    casUsageItems: [
      "Trajet vers ou depuis un événement au Groupama Stadium ou à la LDLC Arena.",
      "Déplacement résidentiel ou professionnel classique.",
      "Trajet vers l'aéroport, proche de la commune.",
    ],
    frequentTrips: [
      { title: "Décines-Charpieu → Groupama Stadium", body: "Trajet vers le stade pour un match ou un concert.", href: "/vtc-groupama-stadium" },
      { title: "Décines-Charpieu → Aéroport Lyon-Saint Exupéry", body: "Transfert vers l'aéroport, à proximité de la commune.", href: "/transfert-aeroport" },
      { title: "Décines-Charpieu → Lyon centre", body: "Trajet vers le centre de Lyon." },
    ],
    faq: [
      { q: "KDRIVE dessert-il les soirs de match au Groupama Stadium ?", a: "Oui, mais aucune disponibilité immédiate n'est garantie les soirs d'affluence : une réservation anticipée est recommandée." },
      { q: "KDRIVE dessert-il aussi la LDLC Arena ?", a: "Oui, les trajets vers la LDLC Arena sont traités comme toute autre demande de VTC." },
      { q: "KDRIVE dessert-il tout Décines-Charpieu en dehors des événements ?", a: "Oui, chaque demande est confirmée individuellement par l'équipe avant la course." },
    ],
    neighborLinksTitle: "Communes voisines",
    neighborLinks: [
      { href: "/vtc-banlieue-est-lyon", label: "Banlieue est de Lyon" },
      { href: "/vtc-meyzieu", label: "VTC Meyzieu" },
      { href: "/vtc-vaulx-en-velin", label: "VTC Vaulx-en-Velin" },
      { href: "/vtc-ldlc-arena", label: "VTC LDLC Arena" },
    ],
    pillarLinksTitle: "Poursuivre votre réservation",
    pillarLinks: standardPillarLinks,
    sources: ["Groupama Stadium et LDLC Arena confirmés situés à Décines-Charpieu (connaissance publique) — à consolider auprès des sites officiels avant indexation large."],
  },
  {
    slug: "vtc-meyzieu",
    family: "commune",
    editorialStatus: "needsEnrichment",
    title: "VTC Meyzieu | Chauffeur privé | KDRIVE",
    metaDescription: "Chauffeur privé à Meyzieu : trajets vers Lyon, l'aéroport Lyon-Saint Exupéry et le parc du Grand Large. Tarif confirmé avant votre course.",
    eyebrow: "VTC Meyzieu",
    h1: "Chauffeur privé à Meyzieu",
    breadcrumbParent: { label: "Banlieue est", href: "/vtc-banlieue-est-lyon" },
    heroImage: "/images/hero-lyon.jpg",
    heroLead: "KDRIVE dessert Meyzieu, commune de l'est lyonnais proche de l'aéroport, pour vos trajets vers Lyon ou vos transferts.",
    presentationTitle: "KDRIVE dessert Meyzieu",
    presentationBody: [
      "Meyzieu se situe à l'est de la métropole, sur l'axe menant à l'aéroport Lyon-Saint Exupéry. La commune est connue pour le parc de loisirs du Grand Large, aménagé autour d'un plan d'eau.",
      "Sa position sur l'axe aéroportuaire en fait un point de départ ou d'arrivée courant, aussi bien pour un trajet résidentiel que pour un transfert vers l'aéroport.",
    ],
    quartiersTitle: "Repères à Meyzieu",
    quartiers: [
      { title: "Grand Large", body: "Parc de loisirs aménagé autour d'un plan d'eau, repère géographique de Meyzieu." },
      { title: "Centre-ville de Meyzieu", body: "Secteur résidentiel et commerçant de la commune." },
    ],
    casUsageTitle: "Motifs de déplacement courants",
    casUsageItems: [
      "Trajet résidentiel ou familial, y compris vers le parc du Grand Large.",
      "Déplacement professionnel vers Lyon ou une commune voisine.",
      "Transfert vers l'aéroport Lyon-Saint Exupéry, proche de la commune.",
    ],
    frequentTrips: [
      { title: "Meyzieu → Aéroport Lyon-Saint Exupéry", body: "Transfert direct vers l'aéroport, axe est de la métropole.", href: "/transfert-aeroport" },
      { title: "Meyzieu → Décines-Charpieu", body: "Trajet vers la commune voisine, proche du Groupama Stadium.", href: "/vtc-decines-charpieu" },
      { title: "Meyzieu → Lyon centre", body: "Trajet vers le centre de Lyon." },
    ],
    faq: [
      { q: "KDRIVE dessert-il tout Meyzieu ?", a: "KDRIVE prend en charge les demandes à Meyzieu au cas par cas ; chaque demande est confirmée individuellement par l'équipe avant la course." },
      { q: "Le trajet vers l'aéroport est-il rapide depuis Meyzieu ?", a: "Aucun délai n'est garanti à l'avance ; la durée dépend du trafic au moment du trajet." },
      { q: "KDRIVE dessert-il un trajet familial vers le Grand Large ?", a: "Oui, ce type de trajet est traité comme toute autre demande de VTC." },
    ],
    neighborLinksTitle: "Communes voisines",
    neighborLinks: [
      { href: "/vtc-banlieue-est-lyon", label: "Banlieue est de Lyon" },
      { href: "/vtc-decines-charpieu", label: "VTC Décines-Charpieu" },
      { href: "/vtc-chassieu", label: "VTC Chassieu" },
    ],
    pillarLinksTitle: "Poursuivre votre réservation",
    pillarLinks: standardPillarLinks,
    sources: ["Connaissance générale de Meyzieu (parc du Grand Large) — à consolider auprès de meyzieu.fr."],
  },
  {
    slug: "vtc-chassieu",
    family: "commune",
    editorialStatus: "needsEnrichment",
    title: "VTC Chassieu | Chauffeur privé | KDRIVE",
    metaDescription: "Chauffeur privé à Chassieu : trajets vers Lyon, Eurexpo et l'aéroport Lyon-Saint Exupéry. Tarif confirmé avant votre course.",
    eyebrow: "VTC Chassieu",
    h1: "Chauffeur privé à Chassieu",
    breadcrumbParent: { label: "Banlieue est", href: "/vtc-banlieue-est-lyon" },
    heroImage: "/images/service-affaires.jpg",
    heroLead: "KDRIVE dessert Chassieu, commune qui accueille le parc des expositions Eurexpo, pour vos trajets professionnels ou vers l'aéroport.",
    presentationTitle: "KDRIVE dessert Chassieu",
    presentationBody: [
      "Chassieu, à l'est de la métropole, accueille le parc des expositions Eurexpo, qui génère des trajets ponctuels importants lors des salons professionnels. La commune regroupe aussi plusieurs zones d'activité logistique.",
      "KDRIVE y assure des prises en charge pour des trajets professionnels, des salons ou des transferts vers l'aéroport.",
    ],
    quartiersTitle: "Repères à Chassieu",
    quartiers: [
      { title: "Eurexpo", body: "Parc des expositions accueillant des salons professionnels et grand public." },
      { title: "Zones d'activité logistique", body: "Chassieu regroupe plusieurs zones d'activité à l'est de la métropole." },
    ],
    casUsageTitle: "Motifs de déplacement courants",
    casUsageItems: [
      "Trajet vers ou depuis un salon à Eurexpo.",
      "Déplacement professionnel vers une zone d'activité de Chassieu.",
      "Transfert vers l'aéroport Lyon-Saint Exupéry.",
    ],
    frequentTrips: [
      { title: "Chassieu → Eurexpo", body: "Trajet vers le parc des expositions pour un salon.", href: "/vtc-eurexpo-lyon" },
      { title: "Chassieu → Aéroport Lyon-Saint Exupéry", body: "Transfert direct vers l'aéroport.", href: "/transfert-aeroport" },
      { title: "Chassieu → Lyon centre", body: "Trajet vers le centre de Lyon." },
    ],
    faq: [
      { q: "KDRIVE dessert-il les salons à Eurexpo ?", a: "Oui, une réservation anticipée est recommandée lors des salons à forte affluence." },
      { q: "KDRIVE dessert-il tout Chassieu ?", a: "KDRIVE prend en charge les demandes à Chassieu au cas par cas ; chaque demande est confirmée individuellement par l'équipe avant la course." },
      { q: "Quel véhicule pour un trajet professionnel vers Eurexpo ?", a: "La catégorie Premium est recommandée pour un rendez-vous professionnel ou un salon." },
    ],
    neighborLinksTitle: "Communes voisines",
    neighborLinks: [
      { href: "/vtc-banlieue-est-lyon", label: "Banlieue est de Lyon" },
      { href: "/vtc-eurexpo-lyon", label: "VTC Eurexpo Lyon" },
      { href: "/vtc-meyzieu", label: "VTC Meyzieu" },
    ],
    pillarLinksTitle: "Poursuivre votre réservation",
    pillarLinks: standardPillarLinks,
    sources: ["Eurexpo confirmé situé à Chassieu (connaissance publique, cf. popular-destinations.ts) — à consolider auprès d'eurexpo.com."],
  },

  // --- Banlieue nord ---
  {
    slug: "vtc-caluire-et-cuire",
    family: "commune",
    editorialStatus: "needsEnrichment",
    title: "VTC Caluire-et-Cuire | Chauffeur privé | KDRIVE",
    metaDescription: "Chauffeur privé à Caluire-et-Cuire : trajets vers Lyon, la Croix-Rousse et les gares. Tarif confirmé avant votre course.",
    eyebrow: "VTC Caluire-et-Cuire",
    h1: "Chauffeur privé à Caluire-et-Cuire",
    breadcrumbParent: { label: "Banlieue nord", href: "/vtc-banlieue-nord-lyon" },
    heroImage: "/images/hero-lyon.jpg",
    heroLead: "KDRIVE dessert Caluire-et-Cuire, commune résidentielle au nord de Lyon, pour vos trajets vers le centre-ville ou une gare.",
    presentationTitle: "KDRIVE dessert Caluire-et-Cuire",
    presentationBody: [
      "Caluire-et-Cuire, commune résidentielle en bord de Saône, jouxte directement le 1er et le 4e arrondissement de Lyon (Croix-Rousse). Elle regroupe plusieurs établissements de santé et un habitat majoritairement pavillonnaire.",
      "KDRIVE y assure des prises en charge pour des trajets résidentiels, médicaux ou vers le centre de Lyon.",
    ],
    quartiersTitle: "Repères à Caluire-et-Cuire",
    quartiers: [
      { title: "Colline de Caluire", body: "Secteur résidentiel en hauteur, en continuité de la Croix-Rousse." },
      { title: "Bord de Saône", body: "Rives aménagées, à la limite du 1er arrondissement de Lyon." },
    ],
    casUsageTitle: "Motifs de déplacement courants",
    casUsageItems: [
      "Trajet résidentiel vers le centre de Lyon.",
      "Déplacement lié à un rendez-vous dans un établissement de santé local.",
      "Trajet vers une gare ou l'aéroport.",
    ],
    frequentTrips: [
      { title: "Caluire-et-Cuire → 1er arrondissement", body: "Trajet vers les Terreaux, commune limitrophe.", href: "/vtc-lyon-1er-arrondissement" },
      { title: "Caluire-et-Cuire → Gare Part-Dieu", body: "Trajet vers la gare de la Part-Dieu.", href: "/vtc-lyon-part-dieu" },
      { title: "Caluire-et-Cuire → Aéroport Lyon-Saint Exupéry", body: "Transfert vers l'aéroport.", href: "/transfert-aeroport" },
    ],
    faq: [
      { q: "KDRIVE dessert-il tout Caluire-et-Cuire ?", a: "KDRIVE prend en charge les demandes à Caluire-et-Cuire au cas par cas ; chaque demande est confirmée individuellement par l'équipe avant la course." },
      { q: "KDRIVE dessert-il un rendez-vous médical local ?", a: "Oui, ce type de trajet est traité comme toute autre demande de VTC." },
      { q: "Le centre de Lyon est-il proche depuis Caluire-et-Cuire ?", a: "Oui, la commune jouxte directement le 1er arrondissement ; aucun délai n'est garanti à l'avance." },
    ],
    neighborLinksTitle: "Communes voisines",
    neighborLinks: [
      { href: "/vtc-banlieue-nord-lyon", label: "Banlieue nord de Lyon" },
      { href: "/vtc-lyon-1er-arrondissement", label: "Lyon 1er (Terreaux)" },
      { href: "/vtc-rillieux-la-pape", label: "VTC Rillieux-la-Pape" },
    ],
    pillarLinksTitle: "Poursuivre votre réservation",
    pillarLinks: standardPillarLinks,
    sources: ["Connaissance générale de Caluire-et-Cuire (commune limitrophe de Lyon 1er/4e) — à consolider auprès de caluirecuire.fr."],
  },
  {
    slug: "vtc-rillieux-la-pape",
    family: "commune",
    editorialStatus: "needsEnrichment",
    title: "VTC Rillieux-la-Pape | Chauffeur privé | KDRIVE",
    metaDescription: "Chauffeur privé à Rillieux-la-Pape : trajets vers Lyon, Caluire et les gares. Tarif confirmé avant votre course.",
    eyebrow: "VTC Rillieux-la-Pape",
    h1: "Chauffeur privé à Rillieux-la-Pape",
    breadcrumbParent: { label: "Banlieue nord", href: "/vtc-banlieue-nord-lyon" },
    heroImage: "/images/hero-lyon.jpg",
    heroLead: "KDRIVE dessert Rillieux-la-Pape, commune du nord de la métropole lyonnaise, pour vos trajets vers Lyon ou une gare.",
    presentationTitle: "KDRIVE dessert Rillieux-la-Pape",
    presentationBody: [
      "Rillieux-la-Pape se situe au nord de Lyon, au-delà de Caluire-et-Cuire, en surplomb du Val de Saône. La commune comprend un secteur résidentiel en renouvellement urbain et des zones pavillonnaires.",
      "KDRIVE y traite chaque demande individuellement, qu'il s'agisse d'un trajet résidentiel ou d'un déplacement professionnel vers Lyon.",
    ],
    quartiersTitle: "Repères à Rillieux-la-Pape",
    quartiers: [
      { title: "Ville nouvelle", body: "Secteur résidentiel en renouvellement urbain de la commune." },
      { title: "Val de Saône", body: "Rillieux-la-Pape surplombe la vallée de la Saône, au nord de Caluire." },
    ],
    casUsageTitle: "Motifs de déplacement courants",
    casUsageItems: [
      "Trajet résidentiel vers Lyon ou Caluire-et-Cuire.",
      "Déplacement professionnel vers le centre de Lyon.",
      "Trajet vers une gare ou l'aéroport.",
    ],
    frequentTrips: [
      { title: "Rillieux-la-Pape → Caluire-et-Cuire", body: "Trajet vers la commune voisine, en direction de Lyon.", href: "/vtc-caluire-et-cuire" },
      { title: "Rillieux-la-Pape → Gare Part-Dieu", body: "Trajet vers la gare de la Part-Dieu.", href: "/vtc-lyon-part-dieu" },
      { title: "Rillieux-la-Pape → Aéroport Lyon-Saint Exupéry", body: "Transfert vers l'aéroport.", href: "/transfert-aeroport" },
    ],
    faq: [
      { q: "KDRIVE dessert-il tout Rillieux-la-Pape ?", a: "KDRIVE prend en charge les demandes à Rillieux-la-Pape au cas par cas ; chaque demande est confirmée individuellement par l'équipe avant la course." },
      { q: "Combien de temps pour rejoindre Lyon depuis Rillieux-la-Pape ?", a: "Aucun délai n'est garanti à l'avance ; la durée dépend du trafic au moment du trajet." },
      { q: "KDRIVE dessert-il un trajet vers l'aéroport depuis Rillieux-la-Pape ?", a: "Oui, un transfert direct est possible sur réservation." },
    ],
    neighborLinksTitle: "Communes voisines",
    neighborLinks: [
      { href: "/vtc-banlieue-nord-lyon", label: "Banlieue nord de Lyon" },
      { href: "/vtc-caluire-et-cuire", label: "VTC Caluire-et-Cuire" },
      { href: "/vtc-neuville-sur-saone", label: "VTC Neuville-sur-Saône" },
    ],
    pillarLinksTitle: "Poursuivre votre réservation",
    pillarLinks: standardPillarLinks,
    sources: ["Connaissance générale de Rillieux-la-Pape — à consolider auprès de rillieuxlapape.fr."],
  },
  {
    slug: "vtc-neuville-sur-saone",
    family: "commune",
    editorialStatus: "needsEnrichment",
    title: "VTC Neuville-sur-Saône | Chauffeur privé | KDRIVE",
    metaDescription: "Chauffeur privé à Neuville-sur-Saône : trajets vers Lyon et sa métropole. Tarif confirmé avant votre course.",
    eyebrow: "VTC Neuville-sur-Saône",
    h1: "Chauffeur privé à Neuville-sur-Saône",
    breadcrumbParent: { label: "Banlieue nord", href: "/vtc-banlieue-nord-lyon" },
    heroImage: "/images/hero-lyon.jpg",
    heroLead: "KDRIVE dessert Neuville-sur-Saône, commune du Val de Saône au nord de la métropole lyonnaise.",
    presentationTitle: "KDRIVE dessert Neuville-sur-Saône",
    presentationBody: [
      "Neuville-sur-Saône se situe à l'extrémité nord de la métropole lyonnaise, au bord de la Saône. Une commune résidentielle plus éloignée du centre de Lyon que Caluire-et-Cuire ou Rillieux-la-Pape.",
      "Compte tenu de cet éloignement, le tarif d'un trajet vers Lyon, une gare ou l'aéroport est calculé selon la distance réelle parcourue depuis Neuville-sur-Saône.",
    ],
    quartiersTitle: "Repères à Neuville-sur-Saône",
    quartiers: [
      { title: "Bords de Saône", body: "Commune riveraine de la Saône, à l'entrée nord de la métropole lyonnaise." },
    ],
    casUsageTitle: "Motifs de déplacement courants",
    casUsageItems: [
      "Trajet résidentiel vers Lyon ou une commune voisine.",
      "Déplacement vers une gare ou l'aéroport, sur une distance plus longue que depuis le centre de Lyon.",
    ],
    frequentTrips: [
      { title: "Neuville-sur-Saône → Lyon centre", body: "Trajet vers le centre de Lyon, au sud de la commune." },
      { title: "Neuville-sur-Saône → Aéroport Lyon-Saint Exupéry", body: "Transfert vers l'aéroport, sur une distance plus longue.", href: "/transfert-aeroport" },
      { title: "Neuville-sur-Saône → Rillieux-la-Pape", body: "Trajet vers la commune voisine.", href: "/vtc-rillieux-la-pape" },
    ],
    faq: [
      { q: "KDRIVE dessert-il Neuville-sur-Saône malgré la distance avec Lyon ?", a: "Oui, chaque demande est confirmée individuellement, avec un tarif calculé à partir de la distance réelle du trajet." },
      { q: "Le tarif est-il plus élevé depuis Neuville-sur-Saône ?", a: "Le tarif dépend de la distance réelle du trajet demandé ; aucun prix fixe n'est affiché à l'avance sur cette page." },
      { q: "KDRIVE dessert-il un trajet longue distance depuis Neuville-sur-Saône ?", a: "Oui, ce type de trajet est traité comme un trajet longue distance classique." },
    ],
    neighborLinksTitle: "Communes voisines",
    neighborLinks: [
      { href: "/vtc-banlieue-nord-lyon", label: "Banlieue nord de Lyon" },
      { href: "/vtc-rillieux-la-pape", label: "VTC Rillieux-la-Pape" },
    ],
    pillarLinksTitle: "Poursuivre votre réservation",
    pillarLinks: standardPillarLinks,
    sources: ["Connaissance générale de Neuville-sur-Saône — à consolider auprès du site officiel de la commune."],
  },

  // --- Banlieue ouest ---
  {
    slug: "vtc-ecully",
    family: "commune",
    editorialStatus: "needsEnrichment",
    title: "VTC Écully | Chauffeur privé | KDRIVE",
    metaDescription: "Chauffeur privé à Écully : trajets vers Lyon, l'EM Lyon Business School et l'Institut Paul Bocuse. Tarif confirmé avant votre course.",
    eyebrow: "VTC Écully",
    h1: "Chauffeur privé à Écully",
    breadcrumbParent: { label: "Banlieue ouest", href: "/vtc-banlieue-ouest-lyon" },
    heroImage: "/images/service-affaires.jpg",
    heroLead: "KDRIVE dessert Écully, commune résidentielle de l'ouest lyonnais qui accueille l'EM Lyon Business School et l'Institut Paul Bocuse.",
    presentationTitle: "KDRIVE dessert Écully",
    presentationBody: [
      "Écully, à l'ouest de Lyon, accueille deux établissements d'enseignement reconnus : l'EM Lyon Business School et l'Institut Paul Bocuse. La commune est également résidentielle, avec un cadre boisé apprécié.",
      "KDRIVE y assure des prises en charge pour des trajets étudiants, professionnels ou résidentiels.",
    ],
    quartiersTitle: "Repères à Écully",
    quartiers: [
      { title: "EM Lyon Business School", body: "École de commerce reconnue, implantée à Écully." },
      { title: "Institut Paul Bocuse", body: "École de gastronomie et de management hôtelier, également implantée à Écully." },
    ],
    casUsageTitle: "Motifs de déplacement courants",
    casUsageItems: [
      "Trajet étudiant ou professionnel vers l'EM Lyon Business School ou l'Institut Paul Bocuse.",
      "Déplacement résidentiel vers le centre de Lyon.",
      "Trajet vers une gare ou l'aéroport.",
    ],
    frequentTrips: [
      { title: "Écully → Lyon centre", body: "Trajet vers le centre de Lyon, à l'est de la commune." },
      { title: "Écully → Tassin-la-Demi-Lune", body: "Trajet vers la commune voisine.", href: "/vtc-tassin-la-demi-lune" },
      { title: "Écully → Aéroport Lyon-Saint Exupéry", body: "Transfert vers l'aéroport.", href: "/transfert-aeroport" },
    ],
    faq: [
      { q: "KDRIVE dessert-il l'EM Lyon Business School ?", a: "Oui, un trajet étudiant ou professionnel vers ce campus est traité comme toute autre demande de VTC." },
      { q: "KDRIVE dessert-il tout Écully ?", a: "KDRIVE prend en charge les demandes à Écully au cas par cas ; chaque demande est confirmée individuellement par l'équipe avant la course." },
      { q: "Quel véhicule pour un trajet professionnel vers Écully ?", a: "La catégorie Premium est recommandée pour un rendez-vous professionnel ou académique." },
    ],
    neighborLinksTitle: "Communes voisines",
    neighborLinks: [
      { href: "/vtc-banlieue-ouest-lyon", label: "Banlieue ouest de Lyon" },
      { href: "/vtc-tassin-la-demi-lune", label: "VTC Tassin-la-Demi-Lune" },
      { href: "/vtc-lyon-9e-arrondissement", label: "Lyon 9e (Vaise)" },
    ],
    pillarLinksTitle: "Poursuivre votre réservation",
    pillarLinks: standardPillarLinks,
    sources: ["EM Lyon Business School et Institut Paul Bocuse confirmés implantés à Écully (connaissance publique) — à consolider auprès des sites officiels."],
  },
  {
    slug: "vtc-tassin-la-demi-lune",
    family: "commune",
    editorialStatus: "needsEnrichment",
    title: "VTC Tassin-la-Demi-Lune | Chauffeur privé | KDRIVE",
    metaDescription: "Chauffeur privé à Tassin-la-Demi-Lune : trajets vers Lyon et l'ouest lyonnais. Tarif confirmé avant votre course.",
    eyebrow: "VTC Tassin-la-Demi-Lune",
    h1: "Chauffeur privé à Tassin-la-Demi-Lune",
    breadcrumbParent: { label: "Banlieue ouest", href: "/vtc-banlieue-ouest-lyon" },
    heroImage: "/images/hero-lyon.jpg",
    heroLead: "KDRIVE dessert Tassin-la-Demi-Lune, commune résidentielle de l'ouest lyonnais, pour vos trajets vers Lyon.",
    presentationTitle: "KDRIVE dessert Tassin-la-Demi-Lune",
    presentationBody: [
      "Tassin-la-Demi-Lune est une commune résidentielle de l'ouest lyonnais, porte d'entrée vers les communes de Charbonnières-les-Bains et Écully. Elle regroupe aussi des zones de bureaux et de commerces.",
      "Que le trajet parte d'un domicile ou d'un bureau de la commune, KDRIVE confirme chaque demande individuellement avant la course.",
    ],
    quartiersTitle: "Repères à Tassin-la-Demi-Lune",
    quartiers: [
      { title: "Centre-ville de Tassin", body: "Secteur résidentiel et commerçant de la commune." },
      { title: "Zone d'activité ouest", body: "Secteur de bureaux à la limite de Tassin et Écully." },
    ],
    casUsageTitle: "Motifs de déplacement courants",
    casUsageItems: [
      "Trajet résidentiel vers Lyon.",
      "Déplacement professionnel vers une zone de bureaux de l'ouest lyonnais.",
      "Trajet vers une gare ou l'aéroport.",
    ],
    frequentTrips: [
      { title: "Tassin-la-Demi-Lune → Lyon centre", body: "Trajet vers le centre de Lyon." },
      { title: "Tassin-la-Demi-Lune → Écully", body: "Trajet vers la commune voisine.", href: "/vtc-ecully" },
      { title: "Tassin-la-Demi-Lune → Aéroport Lyon-Saint Exupéry", body: "Transfert vers l'aéroport.", href: "/transfert-aeroport" },
    ],
    faq: [
      { q: "KDRIVE dessert-il tout Tassin-la-Demi-Lune ?", a: "KDRIVE prend en charge les demandes à Tassin-la-Demi-Lune au cas par cas ; chaque demande est confirmée individuellement par l'équipe avant la course." },
      { q: "KDRIVE dessert-il un trajet professionnel vers l'ouest lyonnais ?", a: "Oui, la catégorie Premium est recommandée pour ce type de rendez-vous." },
      { q: "Combien de temps pour rejoindre Lyon depuis Tassin-la-Demi-Lune ?", a: "Aucun délai n'est garanti à l'avance ; la durée dépend du trafic au moment du trajet." },
    ],
    neighborLinksTitle: "Communes voisines",
    neighborLinks: [
      { href: "/vtc-banlieue-ouest-lyon", label: "Banlieue ouest de Lyon" },
      { href: "/vtc-ecully", label: "VTC Écully" },
      { href: "/vtc-charbonnieres-les-bains", label: "VTC Charbonnières-les-Bains" },
    ],
    pillarLinksTitle: "Poursuivre votre réservation",
    pillarLinks: standardPillarLinks,
    sources: ["Connaissance générale de Tassin-la-Demi-Lune — à consolider auprès de tassinlademilune.fr."],
  },
  {
    slug: "vtc-charbonnieres-les-bains",
    family: "commune",
    editorialStatus: "needsEnrichment",
    title: "VTC Charbonnières-les-Bains | Chauffeur privé | KDRIVE",
    metaDescription: "Chauffeur privé à Charbonnières-les-Bains : trajets vers Lyon et l'ouest lyonnais. Tarif confirmé avant votre course.",
    eyebrow: "VTC Charbonnières-les-Bains",
    h1: "Chauffeur privé à Charbonnières-les-Bains",
    breadcrumbParent: { label: "Banlieue ouest", href: "/vtc-banlieue-ouest-lyon" },
    heroImage: "/images/service-vip.jpg",
    heroLead: "KDRIVE dessert Charbonnières-les-Bains, commune résidentielle de l'ouest lyonnais, pour vos trajets vers Lyon.",
    presentationTitle: "KDRIVE dessert Charbonnières-les-Bains",
    presentationBody: [
      "Charbonnières-les-Bains, à l'ouest de Lyon, est une commune résidentielle historiquement connue pour ses thermes. Elle regroupe aujourd'hui un habitat résidentiel valorisé et des activités de loisirs (golf).",
      "KDRIVE y organise aussi bien des trajets résidentiels que des déplacements professionnels vers le centre de Lyon.",
    ],
    quartiersTitle: "Repères à Charbonnières-les-Bains",
    quartiers: [
      { title: "Centre-ville", body: "Secteur résidentiel historique de la commune, connu pour son passé thermal." },
    ],
    casUsageTitle: "Motifs de déplacement courants",
    casUsageItems: [
      "Trajet résidentiel vers Lyon.",
      "Déplacement professionnel vers l'ouest lyonnais.",
    ],
    frequentTrips: [
      { title: "Charbonnières-les-Bains → Tassin-la-Demi-Lune", body: "Trajet vers la commune voisine.", href: "/vtc-tassin-la-demi-lune" },
      { title: "Charbonnières-les-Bains → Lyon centre", body: "Trajet vers le centre de Lyon." },
      { title: "Charbonnières-les-Bains → Aéroport Lyon-Saint Exupéry", body: "Transfert vers l'aéroport.", href: "/transfert-aeroport" },
    ],
    faq: [
      { q: "KDRIVE dessert-il tout Charbonnières-les-Bains ?", a: "KDRIVE prend en charge les demandes à Charbonnières-les-Bains au cas par cas ; chaque demande est confirmée individuellement par l'équipe avant la course." },
      { q: "Combien de temps pour rejoindre Lyon depuis Charbonnières-les-Bains ?", a: "Aucun délai n'est garanti à l'avance ; la durée dépend du trafic au moment du trajet." },
    ],
    neighborLinksTitle: "Communes voisines",
    neighborLinks: [
      { href: "/vtc-banlieue-ouest-lyon", label: "Banlieue ouest de Lyon" },
      { href: "/vtc-tassin-la-demi-lune", label: "VTC Tassin-la-Demi-Lune" },
      { href: "/vtc-craponne", label: "VTC Craponne" },
    ],
    pillarLinksTitle: "Poursuivre votre réservation",
    pillarLinks: standardPillarLinks,
    sources: ["Connaissance générale de Charbonnières-les-Bains — à consolider auprès du site officiel de la commune."],
  },
  {
    slug: "vtc-craponne",
    family: "commune",
    editorialStatus: "needsEnrichment",
    title: "VTC Craponne | Chauffeur privé | KDRIVE",
    metaDescription: "Chauffeur privé à Craponne : trajets vers Lyon et l'ouest lyonnais. Tarif confirmé avant votre course.",
    eyebrow: "VTC Craponne",
    h1: "Chauffeur privé à Craponne",
    breadcrumbParent: { label: "Banlieue ouest", href: "/vtc-banlieue-ouest-lyon" },
    heroImage: "/images/hero-lyon.jpg",
    heroLead: "KDRIVE dessert Craponne, commune résidentielle de l'ouest lyonnais, pour vos trajets vers Lyon.",
    presentationTitle: "KDRIVE dessert Craponne",
    presentationBody: [
      "Craponne, à l'ouest de la métropole lyonnaise, est une commune résidentielle au caractère semi-rural, plus éloignée du centre de Lyon que Tassin-la-Demi-Lune ou Écully.",
      "KDRIVE y assure des prises en charge pour des trajets vers Lyon, une gare ou l'aéroport.",
    ],
    quartiersTitle: "Repères à Craponne",
    quartiers: [
      { title: "Centre-ville de Craponne", body: "Secteur résidentiel de la commune, à l'ouest de la métropole." },
    ],
    casUsageTitle: "Motifs de déplacement courants",
    casUsageItems: [
      "Trajet résidentiel vers Lyon ou une commune voisine.",
      "Déplacement vers une gare ou l'aéroport.",
    ],
    frequentTrips: [
      { title: "Craponne → Charbonnières-les-Bains", body: "Trajet vers la commune voisine.", href: "/vtc-charbonnieres-les-bains" },
      { title: "Craponne → Lyon centre", body: "Trajet vers le centre de Lyon." },
      { title: "Craponne → Aéroport Lyon-Saint Exupéry", body: "Transfert vers l'aéroport.", href: "/transfert-aeroport" },
    ],
    faq: [
      { q: "KDRIVE dessert-il tout Craponne ?", a: "KDRIVE prend en charge les demandes à Craponne au cas par cas ; chaque demande est confirmée individuellement par l'équipe avant la course." },
      { q: "Le tarif est-il plus élevé depuis Craponne ?", a: "Le tarif dépend de la distance réelle du trajet demandé ; aucun prix fixe n'est affiché à l'avance sur cette page." },
    ],
    neighborLinksTitle: "Communes voisines",
    neighborLinks: [
      { href: "/vtc-banlieue-ouest-lyon", label: "Banlieue ouest de Lyon" },
      { href: "/vtc-charbonnieres-les-bains", label: "VTC Charbonnières-les-Bains" },
      { href: "/vtc-francheville", label: "VTC Francheville" },
    ],
    pillarLinksTitle: "Poursuivre votre réservation",
    pillarLinks: standardPillarLinks,
    sources: ["Connaissance générale de Craponne — à consolider auprès du site officiel de la commune."],
  },
  {
    slug: "vtc-dardilly",
    family: "commune",
    editorialStatus: "needsEnrichment",
    title: "VTC Dardilly | Chauffeur privé | KDRIVE",
    metaDescription: "Chauffeur privé à Dardilly : trajets vers Lyon et accès à l'autoroute A6. Tarif confirmé avant votre course.",
    eyebrow: "VTC Dardilly",
    h1: "Chauffeur privé à Dardilly",
    breadcrumbParent: { label: "Banlieue ouest", href: "/vtc-banlieue-ouest-lyon" },
    heroImage: "/images/hero-lyon.jpg",
    heroLead: "KDRIVE dessert Dardilly, commune au nord-ouest de Lyon, porte d'entrée vers l'autoroute A6.",
    presentationTitle: "KDRIVE dessert Dardilly",
    presentationBody: [
      "Dardilly se situe au nord-ouest de la métropole lyonnaise, à proximité de l'échangeur autoroutier de l'A6 (axe Lyon-Paris). La commune regroupe un secteur résidentiel et une zone d'activité.",
      "KDRIVE y assure des prises en charge pour des trajets résidentiels, professionnels ou vers un axe longue distance.",
    ],
    quartiersTitle: "Repères à Dardilly",
    quartiers: [
      { title: "Échangeur A6", body: "Accès autoroutier vers Paris et le nord, repère géographique de la commune." },
      { title: "Zone d'activité", body: "Secteur de bureaux et de commerces à Dardilly." },
    ],
    casUsageTitle: "Motifs de déplacement courants",
    casUsageItems: [
      "Trajet résidentiel ou professionnel vers Lyon.",
      "Déplacement vers un axe longue distance (A6) depuis Dardilly.",
    ],
    frequentTrips: [
      { title: "Dardilly → Limonest", body: "Trajet vers la commune voisine, également proche de l'A6.", href: "/vtc-limonest" },
      { title: "Dardilly → Lyon centre", body: "Trajet vers le centre de Lyon." },
      { title: "Dardilly → Aéroport Lyon-Saint Exupéry", body: "Transfert vers l'aéroport.", href: "/transfert-aeroport" },
    ],
    faq: [
      { q: "KDRIVE dessert-il tout Dardilly ?", a: "KDRIVE prend en charge les demandes à Dardilly au cas par cas ; chaque demande est confirmée individuellement par l'équipe avant la course." },
      { q: "KDRIVE dessert-il un trajet longue distance depuis Dardilly ?", a: "Oui, ce type de trajet est traité comme un trajet longue distance classique, avec un tarif calculé selon la distance réelle." },
    ],
    neighborLinksTitle: "Communes voisines",
    neighborLinks: [
      { href: "/vtc-banlieue-ouest-lyon", label: "Banlieue ouest de Lyon" },
      { href: "/vtc-limonest", label: "VTC Limonest" },
      { href: "/longues-distances", label: "Longues distances" },
    ],
    pillarLinksTitle: "Poursuivre votre réservation",
    pillarLinks: standardPillarLinks,
    sources: ["Connaissance générale de Dardilly (échangeur A6) — à consolider auprès du site officiel de la commune."],
  },
  {
    slug: "vtc-limonest",
    family: "commune",
    editorialStatus: "needsEnrichment",
    title: "VTC Limonest | Chauffeur privé | KDRIVE",
    metaDescription: "Chauffeur privé à Limonest : trajets vers Lyon et les zones d'activité de la Porte de Lyon. Tarif confirmé avant votre course.",
    eyebrow: "VTC Limonest",
    h1: "Chauffeur privé à Limonest",
    breadcrumbParent: { label: "Banlieue ouest", href: "/vtc-banlieue-ouest-lyon" },
    heroImage: "/images/service-affaires.jpg",
    heroLead: "KDRIVE dessert Limonest, commune du nord-ouest lyonnais qui regroupe un important pôle de bureaux (Porte de Lyon).",
    presentationTitle: "KDRIVE dessert Limonest",
    presentationBody: [
      "Limonest, au nord-ouest de la métropole, accueille une partie du pôle de bureaux et de commerces connu sous le nom de Porte de Lyon, à proximité de l'échangeur autoroutier de l'A6.",
      "KDRIVE y assure des prises en charge pour des trajets professionnels et résidentiels.",
    ],
    quartiersTitle: "Repères à Limonest",
    quartiers: [
      { title: "Porte de Lyon", body: "Pôle de bureaux et de commerces partagé avec la commune de Dardilly." },
    ],
    casUsageTitle: "Motifs de déplacement courants",
    casUsageItems: [
      "Trajet professionnel vers le pôle Porte de Lyon.",
      "Déplacement résidentiel vers Lyon.",
    ],
    frequentTrips: [
      { title: "Limonest → Dardilly", body: "Trajet vers la commune voisine, également sur l'axe A6.", href: "/vtc-dardilly" },
      { title: "Limonest → Lyon centre", body: "Trajet vers le centre de Lyon." },
      { title: "Limonest → Aéroport Lyon-Saint Exupéry", body: "Transfert vers l'aéroport.", href: "/transfert-aeroport" },
    ],
    faq: [
      { q: "KDRIVE dessert-il tout Limonest ?", a: "KDRIVE prend en charge les demandes à Limonest au cas par cas ; chaque demande est confirmée individuellement par l'équipe avant la course." },
      { q: "Quel véhicule pour un rendez-vous professionnel à la Porte de Lyon ?", a: "La catégorie Premium est recommandée pour ce type de rendez-vous." },
    ],
    neighborLinksTitle: "Communes voisines",
    neighborLinks: [
      { href: "/vtc-banlieue-ouest-lyon", label: "Banlieue ouest de Lyon" },
      { href: "/vtc-dardilly", label: "VTC Dardilly" },
    ],
    pillarLinksTitle: "Poursuivre votre réservation",
    pillarLinks: standardPillarLinks,
    sources: ["Connaissance générale de Limonest (pôle Porte de Lyon) — à consolider auprès du site officiel de la commune."],
  },
  {
    slug: "vtc-francheville",
    family: "commune",
    editorialStatus: "needsEnrichment",
    title: "VTC Francheville | Chauffeur privé | KDRIVE",
    metaDescription: "Chauffeur privé à Francheville : trajets vers Lyon et l'ouest lyonnais. Tarif confirmé avant votre course.",
    eyebrow: "VTC Francheville",
    h1: "Chauffeur privé à Francheville",
    breadcrumbParent: { label: "Banlieue ouest", href: "/vtc-banlieue-ouest-lyon" },
    heroImage: "/images/hero-lyon.jpg",
    heroLead: "KDRIVE dessert Francheville, commune résidentielle des coteaux de l'ouest lyonnais.",
    presentationTitle: "KDRIVE dessert Francheville",
    presentationBody: [
      "Francheville se situe sur les coteaux de l'ouest lyonnais, entre Sainte-Foy-lès-Lyon et Tassin-la-Demi-Lune. Une commune résidentielle familiale, en léger relief par rapport au centre de Lyon.",
      "KDRIVE y confirme individuellement chaque demande de trajet résidentiel vers le centre de Lyon.",
    ],
    quartiersTitle: "Repères à Francheville",
    quartiers: [
      { title: "Coteaux de l'ouest lyonnais", body: "Relief résidentiel caractéristique du secteur de Francheville." },
    ],
    casUsageTitle: "Motifs de déplacement courants",
    casUsageItems: [
      "Trajet résidentiel ou familial vers Lyon.",
      "Déplacement vers une commune voisine de l'ouest lyonnais.",
    ],
    frequentTrips: [
      { title: "Francheville → Sainte-Foy-lès-Lyon", body: "Trajet vers la commune voisine.", href: "/vtc-sainte-foy-les-lyon" },
      { title: "Francheville → Lyon centre", body: "Trajet vers le centre de Lyon." },
      { title: "Francheville → Aéroport Lyon-Saint Exupéry", body: "Transfert vers l'aéroport.", href: "/transfert-aeroport" },
    ],
    faq: [
      { q: "KDRIVE dessert-il tout Francheville ?", a: "KDRIVE prend en charge les demandes à Francheville au cas par cas ; chaque demande est confirmée individuellement par l'équipe avant la course." },
      { q: "Les rues en relief posent-elles une difficulté pour la prise en charge ?", a: "Indiquez l'adresse exacte lors de la réservation : le point de prise en charge est confirmé selon l'accès possible au véhicule." },
    ],
    neighborLinksTitle: "Communes voisines",
    neighborLinks: [
      { href: "/vtc-banlieue-ouest-lyon", label: "Banlieue ouest de Lyon" },
      { href: "/vtc-sainte-foy-les-lyon", label: "VTC Sainte-Foy-lès-Lyon" },
      { href: "/vtc-craponne", label: "VTC Craponne" },
    ],
    pillarLinksTitle: "Poursuivre votre réservation",
    pillarLinks: standardPillarLinks,
    sources: ["Connaissance générale de Francheville — à consolider auprès du site officiel de la commune."],
  },
  {
    slug: "vtc-sainte-foy-les-lyon",
    family: "commune",
    editorialStatus: "needsEnrichment",
    title: "VTC Sainte-Foy-lès-Lyon | Chauffeur privé | KDRIVE",
    metaDescription: "Chauffeur privé à Sainte-Foy-lès-Lyon : trajets vers Lyon et l'ouest lyonnais. Tarif confirmé avant votre course.",
    eyebrow: "VTC Sainte-Foy-lès-Lyon",
    h1: "Chauffeur privé à Sainte-Foy-lès-Lyon",
    breadcrumbParent: { label: "Banlieue ouest", href: "/vtc-banlieue-ouest-lyon" },
    heroImage: "/images/hero-lyon.jpg",
    heroLead: "KDRIVE dessert Sainte-Foy-lès-Lyon, commune résidentielle des coteaux, limitrophe de Lyon.",
    presentationTitle: "KDRIVE dessert Sainte-Foy-lès-Lyon",
    presentationBody: [
      "Sainte-Foy-lès-Lyon surplombe Lyon depuis les coteaux du sud-ouest, directement limitrophe des 2e et 5e arrondissements. Une commune résidentielle recherchée pour son cadre.",
      "KDRIVE y assure des prises en charge pour des trajets résidentiels vers le centre de Lyon, tout proche.",
    ],
    quartiersTitle: "Repères à Sainte-Foy-lès-Lyon",
    quartiers: [
      { title: "Coteaux surplombant Lyon", body: "Position en hauteur, à la limite directe des 2e et 5e arrondissements de Lyon." },
    ],
    casUsageTitle: "Motifs de déplacement courants",
    casUsageItems: [
      "Trajet résidentiel vers le centre de Lyon, tout proche.",
      "Déplacement vers une gare ou l'aéroport.",
    ],
    frequentTrips: [
      { title: "Sainte-Foy-lès-Lyon → 5e arrondissement", body: "Trajet vers le Vieux Lyon et Fourvière, en contrebas.", href: "/vtc-lyon-5e-arrondissement" },
      { title: "Sainte-Foy-lès-Lyon → Gare Perrache", body: "Trajet vers la gare de Perrache.", href: "/vtc-lyon-perrache" },
      { title: "Sainte-Foy-lès-Lyon → Aéroport Lyon-Saint Exupéry", body: "Transfert vers l'aéroport.", href: "/transfert-aeroport" },
    ],
    faq: [
      { q: "KDRIVE dessert-il tout Sainte-Foy-lès-Lyon ?", a: "KDRIVE prend en charge les demandes à Sainte-Foy-lès-Lyon au cas par cas ; chaque demande est confirmée individuellement par l'équipe avant la course." },
      { q: "Le centre de Lyon est-il proche depuis Sainte-Foy-lès-Lyon ?", a: "Oui, la commune est directement limitrophe de Lyon ; aucun délai n'est garanti à l'avance." },
    ],
    neighborLinksTitle: "Communes voisines",
    neighborLinks: [
      { href: "/vtc-banlieue-ouest-lyon", label: "Banlieue ouest de Lyon" },
      { href: "/vtc-lyon-5e-arrondissement", label: "Lyon 5e (Vieux Lyon)" },
      { href: "/vtc-francheville", label: "VTC Francheville" },
    ],
    pillarLinksTitle: "Poursuivre votre réservation",
    pillarLinks: standardPillarLinks,
    sources: ["Connaissance générale de Sainte-Foy-lès-Lyon — à consolider auprès du site officiel de la commune."],
  },

  // --- Banlieue sud ---
  {
    slug: "vtc-venissieux",
    family: "commune",
    editorialStatus: "needsEnrichment",
    title: "VTC Vénissieux | Chauffeur privé | KDRIVE",
    metaDescription: "Chauffeur privé à Vénissieux : trajets vers Lyon, l'aéroport et les zones industrielles. Tarif confirmé avant votre course.",
    eyebrow: "VTC Vénissieux",
    h1: "Chauffeur privé à Vénissieux",
    breadcrumbParent: { label: "Banlieue sud", href: "/vtc-banlieue-sud-lyon" },
    heroImage: "/images/hero-lyon.jpg",
    heroLead: "KDRIVE dessert Vénissieux, commune du sud-est lyonnais, pour vos trajets vers Lyon, une gare ou l'aéroport.",
    presentationTitle: "KDRIVE dessert Vénissieux",
    presentationBody: [
      "Vénissieux, au sud-est de Lyon, est une commune à l'histoire industrielle marquée (industrie automobile), qui regroupe aujourd'hui un habitat dense, dont le quartier des Minguettes, ainsi que des zones d'activité.",
      "Compte tenu de la diversité des quartiers de la commune, KDRIVE confirme individuellement chaque demande, qu'elle soit résidentielle, professionnelle ou liée à un transfert vers l'aéroport.",
    ],
    quartiersTitle: "Repères à Vénissieux",
    quartiers: [
      { title: "Minguettes", body: "Grand quartier résidentiel de Vénissieux." },
      { title: "Zones d'activité industrielle", body: "Vénissieux conserve un tissu industriel important, hérité de son histoire automobile." },
    ],
    casUsageTitle: "Motifs de déplacement courants",
    casUsageItems: [
      "Trajet résidentiel vers Lyon ou une commune voisine.",
      "Déplacement professionnel vers une zone d'activité de Vénissieux.",
      "Transfert vers l'aéroport ou une gare de Lyon.",
    ],
    frequentTrips: [
      { title: "Vénissieux → Gare Perrache", body: "Trajet vers la gare de Perrache.", href: "/vtc-lyon-perrache" },
      { title: "Vénissieux → Aéroport Lyon-Saint Exupéry", body: "Transfert vers l'aéroport.", href: "/transfert-aeroport" },
      { title: "Vénissieux → Corbas", body: "Trajet vers la commune voisine.", href: "/vtc-corbas" },
    ],
    faq: [
      { q: "KDRIVE dessert-il tout Vénissieux ?", a: "KDRIVE prend en charge les demandes à Vénissieux au cas par cas ; chaque demande est confirmée individuellement par l'équipe avant la course." },
      { q: "KDRIVE dessert-il le quartier des Minguettes ?", a: "Oui, ce quartier est desservi comme le reste de la commune, sur réservation." },
      { q: "KDRIVE dessert-il un trajet professionnel vers une zone industrielle de Vénissieux ?", a: "Oui, ce type de trajet est traité comme toute autre demande de VTC." },
    ],
    neighborLinksTitle: "Communes voisines",
    neighborLinks: [
      { href: "/vtc-banlieue-sud-lyon", label: "Banlieue sud de Lyon" },
      { href: "/vtc-corbas", label: "VTC Corbas" },
      { href: "/vtc-saint-fons", label: "VTC Saint-Fons" },
    ],
    pillarLinksTitle: "Poursuivre votre réservation",
    pillarLinks: standardPillarLinks,
    sources: ["Connaissance générale de Vénissieux (Minguettes, histoire industrielle) — à consolider auprès de venissieux.fr."],
  },
  {
    slug: "vtc-oullins-pierre-benite",
    family: "commune",
    editorialStatus: "needsEnrichment",
    title: "VTC Oullins-Pierre-Bénite | Chauffeur privé | KDRIVE",
    metaDescription: "Chauffeur privé à Oullins-Pierre-Bénite : trajets vers Lyon, la Presqu'île et l'aéroport. Tarif confirmé avant votre course.",
    eyebrow: "VTC Oullins-Pierre-Bénite",
    h1: "Chauffeur privé à Oullins-Pierre-Bénite",
    breadcrumbParent: { label: "Banlieue sud", href: "/vtc-banlieue-sud-lyon" },
    heroImage: "/images/hero-lyon.jpg",
    heroLead: "KDRIVE dessert Oullins-Pierre-Bénite, commune du sud-ouest lyonnais, terminus de la ligne de métro B.",
    presentationTitle: "KDRIVE dessert Oullins-Pierre-Bénite",
    presentationBody: [
      "Oullins-Pierre-Bénite, née de la fusion des communes d'Oullins et de Pierre-Bénite, se situe au sud-ouest de Lyon, à proximité immédiate de la Confluence. Le secteur de Pierre-Bénite conserve un tissu industriel.",
      "Chaque demande, résidentielle ou professionnelle, y est confirmée individuellement par l'équipe KDRIVE avant la course.",
    ],
    quartiersTitle: "Repères à Oullins-Pierre-Bénite",
    quartiers: [
      { title: "Oullins centre", body: "Secteur résidentiel et commerçant, terminus de la ligne de métro B." },
      { title: "Pierre-Bénite", body: "Secteur conservant un tissu industriel, en bord de Rhône." },
    ],
    casUsageTitle: "Motifs de déplacement courants",
    casUsageItems: [
      "Trajet résidentiel vers Lyon ou la Confluence.",
      "Déplacement professionnel vers le secteur industriel de Pierre-Bénite.",
      "Trajet vers une gare ou l'aéroport.",
    ],
    frequentTrips: [
      { title: "Oullins-Pierre-Bénite → 2e arrondissement", body: "Trajet vers la Confluence, tout proche.", href: "/vtc-lyon-2e-arrondissement" },
      { title: "Oullins-Pierre-Bénite → Gare Perrache", body: "Trajet vers la gare de Perrache.", href: "/vtc-lyon-perrache" },
      { title: "Oullins-Pierre-Bénite → Aéroport Lyon-Saint Exupéry", body: "Transfert vers l'aéroport.", href: "/transfert-aeroport" },
    ],
    faq: [
      { q: "KDRIVE dessert-il tout Oullins-Pierre-Bénite ?", a: "KDRIVE prend en charge les demandes à Oullins-Pierre-Bénite au cas par cas ; chaque demande est confirmée individuellement par l'équipe avant la course." },
      { q: "Le centre de Lyon est-il proche depuis Oullins ?", a: "Oui, la commune est limitrophe de la Confluence (2e arrondissement) ; aucun délai n'est garanti à l'avance." },
    ],
    neighborLinksTitle: "Communes voisines",
    neighborLinks: [
      { href: "/vtc-banlieue-sud-lyon", label: "Banlieue sud de Lyon" },
      { href: "/vtc-lyon-2e-arrondissement", label: "Lyon 2e (Confluence)" },
      { href: "/vtc-saint-genis-laval", label: "VTC Saint-Genis-Laval" },
    ],
    pillarLinksTitle: "Poursuivre votre réservation",
    pillarLinks: standardPillarLinks,
    sources: ["Fusion Oullins/Pierre-Bénite (2019, connaissance publique) — à consolider auprès du site officiel de la commune."],
  },
  {
    slug: "vtc-saint-genis-laval",
    family: "commune",
    editorialStatus: "needsEnrichment",
    title: "VTC Saint-Genis-Laval | Chauffeur privé | KDRIVE",
    metaDescription: "Chauffeur privé à Saint-Genis-Laval : trajets vers Lyon et le sud lyonnais. Tarif confirmé avant votre course.",
    eyebrow: "VTC Saint-Genis-Laval",
    h1: "Chauffeur privé à Saint-Genis-Laval",
    breadcrumbParent: { label: "Banlieue sud", href: "/vtc-banlieue-sud-lyon" },
    heroImage: "/images/hero-lyon.jpg",
    heroLead: "KDRIVE dessert Saint-Genis-Laval, commune résidentielle du sud lyonnais.",
    presentationTitle: "KDRIVE dessert Saint-Genis-Laval",
    presentationBody: [
      "Saint-Genis-Laval se situe au sud-ouest de la métropole lyonnaise, à proximité d'Oullins. Une commune résidentielle, entre coteaux et vallée du Rhône.",
      "Un trajet résidentiel entre Saint-Genis-Laval et Lyon y est traité comme toute autre demande de VTC, confirmée individuellement par l'équipe.",
    ],
    quartiersTitle: "Repères à Saint-Genis-Laval",
    quartiers: [
      { title: "Centre-ville de Saint-Genis-Laval", body: "Secteur résidentiel de la commune, au sud d'Oullins." },
    ],
    casUsageTitle: "Motifs de déplacement courants",
    casUsageItems: [
      "Trajet résidentiel vers Lyon ou Oullins.",
      "Déplacement vers une gare ou l'aéroport.",
    ],
    frequentTrips: [
      { title: "Saint-Genis-Laval → Oullins-Pierre-Bénite", body: "Trajet vers la commune voisine.", href: "/vtc-oullins-pierre-benite" },
      { title: "Saint-Genis-Laval → Lyon centre", body: "Trajet vers le centre de Lyon." },
      { title: "Saint-Genis-Laval → Aéroport Lyon-Saint Exupéry", body: "Transfert vers l'aéroport.", href: "/transfert-aeroport" },
    ],
    faq: [
      { q: "KDRIVE dessert-il tout Saint-Genis-Laval ?", a: "KDRIVE prend en charge les demandes à Saint-Genis-Laval au cas par cas ; chaque demande est confirmée individuellement par l'équipe avant la course." },
      { q: "Combien de temps pour rejoindre Lyon depuis Saint-Genis-Laval ?", a: "Aucun délai n'est garanti à l'avance ; la durée dépend du trafic au moment du trajet." },
    ],
    neighborLinksTitle: "Communes voisines",
    neighborLinks: [
      { href: "/vtc-banlieue-sud-lyon", label: "Banlieue sud de Lyon" },
      { href: "/vtc-oullins-pierre-benite", label: "VTC Oullins-Pierre-Bénite" },
      { href: "/vtc-givors", label: "VTC Givors" },
    ],
    pillarLinksTitle: "Poursuivre votre réservation",
    pillarLinks: standardPillarLinks,
    sources: ["Connaissance générale de Saint-Genis-Laval — à consolider auprès du site officiel de la commune."],
  },
  {
    slug: "vtc-corbas",
    family: "commune",
    editorialStatus: "needsEnrichment",
    title: "VTC Corbas | Chauffeur privé | KDRIVE",
    metaDescription: "Chauffeur privé à Corbas : trajets vers Lyon et les zones logistiques du sud-est lyonnais. Tarif confirmé avant votre course.",
    eyebrow: "VTC Corbas",
    h1: "Chauffeur privé à Corbas",
    breadcrumbParent: { label: "Banlieue sud", href: "/vtc-banlieue-sud-lyon" },
    heroImage: "/images/service-affaires.jpg",
    heroLead: "KDRIVE dessert Corbas, commune du sud-est lyonnais regroupant d'importantes zones d'activité et logistiques.",
    presentationTitle: "KDRIVE dessert Corbas",
    presentationBody: [
      "Corbas, au sud-est de Lyon, près de Vénissieux, regroupe d'importantes zones d'activité logistique et industrielle. La commune est aussi résidentielle, à plus petite échelle.",
      "KDRIVE y assure des prises en charge pour des trajets professionnels vers ces zones d'activité et des trajets résidentiels.",
    ],
    quartiersTitle: "Repères à Corbas",
    quartiers: [
      { title: "Zones d'activité logistique", body: "Corbas regroupe plusieurs zones d'activité au sud-est de la métropole." },
    ],
    casUsageTitle: "Motifs de déplacement courants",
    casUsageItems: [
      "Trajet professionnel vers une zone d'activité de Corbas.",
      "Déplacement résidentiel vers Lyon ou une commune voisine.",
    ],
    frequentTrips: [
      { title: "Corbas → Vénissieux", body: "Trajet vers la commune voisine.", href: "/vtc-venissieux" },
      { title: "Corbas → Lyon centre", body: "Trajet vers le centre de Lyon." },
      { title: "Corbas → Aéroport Lyon-Saint Exupéry", body: "Transfert vers l'aéroport.", href: "/transfert-aeroport" },
    ],
    faq: [
      { q: "KDRIVE dessert-il tout Corbas ?", a: "KDRIVE prend en charge les demandes à Corbas au cas par cas ; chaque demande est confirmée individuellement par l'équipe avant la course." },
      { q: "KDRIVE dessert-il un trajet professionnel vers une zone logistique de Corbas ?", a: "Oui, ce type de trajet est traité comme toute autre demande de VTC." },
    ],
    neighborLinksTitle: "Communes voisines",
    neighborLinks: [
      { href: "/vtc-banlieue-sud-lyon", label: "Banlieue sud de Lyon" },
      { href: "/vtc-venissieux", label: "VTC Vénissieux" },
      { href: "/vtc-feyzin", label: "VTC Feyzin" },
    ],
    pillarLinksTitle: "Poursuivre votre réservation",
    pillarLinks: standardPillarLinks,
    sources: ["Connaissance générale de Corbas (zones logistiques) — à consolider auprès du site officiel de la commune."],
  },
  {
    slug: "vtc-saint-fons",
    family: "commune",
    editorialStatus: "needsEnrichment",
    title: "VTC Saint-Fons | Chauffeur privé | KDRIVE",
    metaDescription: "Chauffeur privé à Saint-Fons : trajets vers Lyon et la vallée de la chimie. Tarif confirmé avant votre course.",
    eyebrow: "VTC Saint-Fons",
    h1: "Chauffeur privé à Saint-Fons",
    breadcrumbParent: { label: "Banlieue sud", href: "/vtc-banlieue-sud-lyon" },
    heroImage: "/images/hero-lyon.jpg",
    heroLead: "KDRIVE dessert Saint-Fons, commune du sud lyonnais située le long de la vallée de la chimie.",
    presentationTitle: "KDRIVE dessert Saint-Fons",
    presentationBody: [
      "Saint-Fons se situe au sud de Lyon, le long du couloir industriel connu sous le nom de vallée de la chimie, en bordure du Rhône. La commune regroupe un habitat résidentiel et des sites industriels.",
      "KDRIVE y confirme individuellement chaque demande, qu'il s'agisse d'un trajet résidentiel ou d'un déplacement lié à un site industriel de la commune.",
    ],
    quartiersTitle: "Repères à Saint-Fons",
    quartiers: [
      { title: "Vallée de la chimie", body: "Couloir industriel qui longe le Rhône entre Lyon et Givors, incluant Saint-Fons." },
    ],
    casUsageTitle: "Motifs de déplacement courants",
    casUsageItems: [
      "Trajet professionnel vers un site industriel de la vallée de la chimie.",
      "Déplacement résidentiel vers Lyon.",
    ],
    frequentTrips: [
      { title: "Saint-Fons → Feyzin", body: "Trajet vers la commune voisine, également dans la vallée de la chimie.", href: "/vtc-feyzin" },
      { title: "Saint-Fons → Lyon centre", body: "Trajet vers le centre de Lyon." },
      { title: "Saint-Fons → Aéroport Lyon-Saint Exupéry", body: "Transfert vers l'aéroport.", href: "/transfert-aeroport" },
    ],
    faq: [
      { q: "KDRIVE dessert-il tout Saint-Fons ?", a: "KDRIVE prend en charge les demandes à Saint-Fons au cas par cas ; chaque demande est confirmée individuellement par l'équipe avant la course." },
      { q: "KDRIVE dessert-il un trajet professionnel vers un site industriel ?", a: "Oui, ce type de trajet est traité comme toute autre demande de VTC." },
    ],
    neighborLinksTitle: "Communes voisines",
    neighborLinks: [
      { href: "/vtc-banlieue-sud-lyon", label: "Banlieue sud de Lyon" },
      { href: "/vtc-feyzin", label: "VTC Feyzin" },
      { href: "/vtc-venissieux", label: "VTC Vénissieux" },
    ],
    pillarLinksTitle: "Poursuivre votre réservation",
    pillarLinks: standardPillarLinks,
    sources: ["Vallée de la chimie (connaissance publique du couloir industriel Lyon-Givors) — à consolider auprès du site officiel de la commune."],
  },
  {
    slug: "vtc-feyzin",
    family: "commune",
    editorialStatus: "needsEnrichment",
    title: "VTC Feyzin | Chauffeur privé | KDRIVE",
    metaDescription: "Chauffeur privé à Feyzin : trajets vers Lyon et la vallée de la chimie. Tarif confirmé avant votre course.",
    eyebrow: "VTC Feyzin",
    h1: "Chauffeur privé à Feyzin",
    breadcrumbParent: { label: "Banlieue sud", href: "/vtc-banlieue-sud-lyon" },
    heroImage: "/images/hero-lyon.jpg",
    heroLead: "KDRIVE dessert Feyzin, commune du sud lyonnais, le long de la vallée de la chimie.",
    presentationTitle: "KDRIVE dessert Feyzin",
    presentationBody: [
      "Feyzin se situe au sud de Lyon, dans le prolongement de Saint-Fons, le long de la vallée de la chimie. La commune regroupe un secteur résidentiel et des sites industriels d'importance régionale.",
      "Comme à Saint-Fons, chaque demande de trajet, résidentielle ou professionnelle, y est confirmée individuellement par l'équipe KDRIVE.",
    ],
    quartiersTitle: "Repères à Feyzin",
    quartiers: [
      { title: "Vallée de la chimie", body: "Feyzin s'inscrit dans ce couloir industriel du sud lyonnais." },
    ],
    casUsageTitle: "Motifs de déplacement courants",
    casUsageItems: [
      "Trajet professionnel vers un site industriel de Feyzin.",
      "Déplacement résidentiel vers Lyon.",
    ],
    frequentTrips: [
      { title: "Feyzin → Saint-Fons", body: "Trajet vers la commune voisine.", href: "/vtc-saint-fons" },
      { title: "Feyzin → Lyon centre", body: "Trajet vers le centre de Lyon." },
      { title: "Feyzin → Aéroport Lyon-Saint Exupéry", body: "Transfert vers l'aéroport.", href: "/transfert-aeroport" },
    ],
    faq: [
      { q: "KDRIVE dessert-il tout Feyzin ?", a: "KDRIVE prend en charge les demandes à Feyzin au cas par cas ; chaque demande est confirmée individuellement par l'équipe avant la course." },
      { q: "KDRIVE dessert-il un trajet professionnel vers un site industriel de Feyzin ?", a: "Oui, ce type de trajet est traité comme toute autre demande de VTC." },
    ],
    neighborLinksTitle: "Communes voisines",
    neighborLinks: [
      { href: "/vtc-banlieue-sud-lyon", label: "Banlieue sud de Lyon" },
      { href: "/vtc-saint-fons", label: "VTC Saint-Fons" },
      { href: "/vtc-corbas", label: "VTC Corbas" },
    ],
    pillarLinksTitle: "Poursuivre votre réservation",
    pillarLinks: standardPillarLinks,
    sources: ["Vallée de la chimie (connaissance publique) — à consolider auprès du site officiel de la commune."],
  },
  {
    slug: "vtc-givors",
    family: "commune",
    editorialStatus: "needsEnrichment",
    title: "VTC Givors | Chauffeur privé | KDRIVE",
    metaDescription: "Chauffeur privé à Givors : trajets vers Lyon et l'axe sud vers Saint-Étienne. Tarif confirmé avant votre course.",
    eyebrow: "VTC Givors",
    h1: "Chauffeur privé à Givors",
    breadcrumbParent: { label: "Banlieue sud", href: "/vtc-banlieue-sud-lyon" },
    heroImage: "/images/hero-lyon.jpg",
    heroLead: "KDRIVE dessert Givors, commune du sud de la métropole lyonnaise, au confluent du Gier et du Rhône.",
    presentationTitle: "KDRIVE dessert Givors",
    presentationBody: [
      "Givors se situe à l'extrémité sud de la métropole lyonnaise, au confluent du Gier et du Rhône, sur l'axe menant vers Saint-Étienne. Une commune à l'histoire industrielle, plus éloignée du centre de Lyon.",
      "Sa position à la frontière de la métropole implique un tarif calculé sur la distance réelle, que le trajet rejoigne Lyon, une gare ou l'aéroport.",
    ],
    quartiersTitle: "Repères à Givors",
    quartiers: [
      { title: "Confluent Gier-Rhône", body: "Position géographique de Givors, à l'entrée sud de la métropole lyonnaise." },
    ],
    casUsageTitle: "Motifs de déplacement courants",
    casUsageItems: [
      "Trajet résidentiel ou professionnel vers Lyon.",
      "Déplacement vers l'axe Saint-Étienne depuis Givors.",
    ],
    frequentTrips: [
      { title: "Givors → Lyon centre", body: "Trajet vers le centre de Lyon, au nord de la commune." },
      { title: "Givors → Saint-Étienne", body: "Trajet longue distance vers Saint-Étienne, sur le même axe.", href: "/transfert-lyon-saint-etienne" },
      { title: "Givors → Aéroport Lyon-Saint Exupéry", body: "Transfert vers l'aéroport, sur une distance plus longue.", href: "/transfert-aeroport" },
    ],
    faq: [
      { q: "KDRIVE dessert-il Givors malgré la distance avec Lyon ?", a: "Oui, chaque demande est confirmée individuellement, avec un tarif calculé à partir de la distance réelle du trajet." },
      { q: "KDRIVE dessert-il un trajet vers Saint-Étienne depuis Givors ?", a: "Oui, ce trajet est traité comme un trajet longue distance classique." },
    ],
    neighborLinksTitle: "Communes voisines",
    neighborLinks: [
      { href: "/vtc-banlieue-sud-lyon", label: "Banlieue sud de Lyon" },
      { href: "/vtc-saint-genis-laval", label: "VTC Saint-Genis-Laval" },
      { href: "/transfert-lyon-saint-etienne", label: "Transfert Lyon – Saint-Étienne" },
    ],
    pillarLinksTitle: "Poursuivre votre réservation",
    pillarLinks: standardPillarLinks,
    sources: ["Connaissance générale de Givors (confluent Gier-Rhône, axe Saint-Étienne) — à consolider auprès du site officiel de la commune."],
  },
];
