import type { LocalPageContent } from "./local-page-template";
import { popularDestinations } from "@/domain/booking/popular-destinations";

const gareTgvAddress = popularDestinations.find((d) => d.label === "Gare Lyon-Saint-Exupéry TGV")!.address;

export const localPages: LocalPageContent[] = [
  {
    slug: "vtc-villeurbanne",
    family: "commune",
    editorialStatus: "readyForIndexing",
    title: "VTC Villeurbanne | Chauffeur privé | KDRIVE",
    metaDescription: "Chauffeur privé à Villeurbanne : trajets vers Lyon, la gare Part-Dieu et l'aéroport, tarif confirmé par téléphone avant votre course.",
    eyebrow: "VTC Villeurbanne",
    h1: "Chauffeur privé à Villeurbanne",
    breadcrumbParent: { label: "Banlieue est", href: "/vtc-banlieue-est-lyon" },
    neighborLinksTitle: "Communes voisines",
    neighborLinks: [
      { href: "/vtc-banlieue-est-lyon", label: "Banlieue est de Lyon" },
      { href: "/vtc-lyon-3e-arrondissement", label: "Lyon 3e (Part-Dieu)" },
      { href: "/vtc-bron", label: "VTC Bron" },
      { href: "/vtc-vaulx-en-velin", label: "VTC Vaulx-en-Velin" },
    ],
    heroLead: "Un service de VTC premium pour vos trajets au départ ou à destination de Villeurbanne, avec un tarif calculé avant confirmation.",
    heroImage: "/images/hero-lyon.jpg",
    presentationTitle: "KDRIVE dessert Villeurbanne",
    presentationBody: [
      "Villeurbanne est une commune limitrophe de Lyon, à proximité immédiate de la gare de la Part-Dieu. KDRIVE y assure des prises en charge pour des trajets vers le centre de Lyon, la gare ou l'aéroport, ainsi que pour des déplacements professionnels.",
      "Chaque demande est confirmée individuellement par l'équipe KDRIVE, avec un tarif calculé à partir de la distance réelle avant toute confirmation.",
    ],
    frequentTrips: [
      { title: "Villeurbanne → Lyon centre", body: "Trajet vers la Presqu'île ou le centre-ville de Lyon, en catégorie Essentiel ou Premium selon votre besoin." },
      { title: "Villeurbanne → Gare Part-Dieu", body: "La gare de la Part-Dieu se trouve à proximité de Villeurbanne. Indiquez votre horaire de train lors de la réservation." },
      { title: "Villeurbanne → Aéroport Lyon-Saint Exupéry", body: "Un transfert avec suivi de votre numéro de vol, pour anticiper un éventuel ajustement d'horaire." },
    ],
    extraTitle: "Déplacements professionnels depuis Villeurbanne",
    extraBody: "KDRIVE accompagne aussi les déplacements professionnels au départ de Villeurbanne : rendez-vous client, trajet vers un site d'entreprise ou transfert vers une gare pour un déplacement d'affaires. La catégorie Premium est recommandée pour ce type de trajet.",
    faq: [
      { q: "KDRIVE dessert-il tout Villeurbanne ?", a: "KDRIVE prend en charge les demandes de VTC à Villeurbanne au cas par cas ; chaque demande est confirmée individuellement par l'équipe avant la course." },
      { q: "Combien de temps pour rejoindre la Part-Dieu depuis Villeurbanne ?", a: "La durée dépend du trafic et de l'adresse exacte de départ ; aucun délai n'est garanti à l'avance, mais le trajet est proche de Lyon." },
      { q: "Quel véhicule choisir pour un trajet professionnel ?", a: "La catégorie Premium est adaptée aux rendez-vous professionnels ; Essentiel convient pour un trajet simple." },
    ],
    pillarLinksTitle: "Poursuivre votre réservation",
    pillarLinks: [
      { href: "/transfert-aeroport", label: "Transfert aéroport" },
      { href: "/transfert-gare", label: "Transfert gare" },
      { href: "/chauffeur-entreprise", label: "Chauffeur entreprise" },
      { href: "/vehicules", label: "Nos véhicules" },
      { href: "/tarifs", label: "Grille tarifaire" },
      { href: "/reserver", label: "Réserver un trajet" },
    ],
  },
  {
    slug: "vtc-lyon-part-dieu",
    family: "gare",
    editorialStatus: "readyForIndexing",
    title: "VTC Gare Lyon Part-Dieu | Chauffeur privé | KDRIVE",
    metaDescription: "Chauffeur privé à la gare de Lyon Part-Dieu : prise en charge organisée selon votre horaire de train, tarif confirmé avant votre trajet.",
    eyebrow: "VTC Lyon Part-Dieu",
    h1: "Chauffeur privé gare de Lyon Part-Dieu",
    breadcrumbParent: { label: "Transfert gare", href: "/transfert-gare" },
    neighborLinksTitle: "Autour de la Part-Dieu",
    neighborLinks: [
      { href: "/vtc-lyon-3e-arrondissement", label: "Lyon 3e arrondissement" },
      { href: "/vtc-villeurbanne", label: "VTC Villeurbanne" },
      { href: "/transfert-gare", label: "Toutes les gares de Lyon" },
    ],
    heroLead: "Une prise en charge organisée pour votre arrivée ou votre départ depuis la gare de Lyon Part-Dieu, sur réservation.",
    heroImage: "/images/service-transferts.jpg",
    presentationTitle: "Un transfert préparé autour de votre horaire de train",
    presentationBody: [
      "Premier pôle multimodal de la région lyonnaise, la gare de Lyon Part-Dieu concentre TGV, TER, métro, tramway et Rhônexpress vers l'aéroport. KDRIVE y organise des prises en charge pour les voyageurs, avec ou sans bagages, sur la base de l'horaire indiqué lors de la réservation.",
      "Aucune correspondance n'est suivie automatiquement en temps réel : en cas de changement d'horaire, contactez KDRIVE dès que possible afin d'ajuster la prise en charge.",
    ],
    practicalInfoTitle: "Repères pour votre venue à Part-Dieu",
    practicalInfoItems: [
      "Adresse : 5 place Charles-Béraudier, 69003 Lyon (3ᵉ arrondissement).",
      "Deux accès principaux : côté place Charles-Béraudier / boulevard Vivier-Merle (centre commercial, quartier d'affaires) et côté rue de la Villette.",
      "La gare jouxte le centre commercial de la Part-Dieu, repère pratique pour un point de rendez-vous.",
      "Métro B, tramways T1/T3/T4 et Rhônexpress (liaison aéroport) desservent directement la gare.",
    ],
    frequentTrips: [
      { title: "Part-Dieu → Aéroport Lyon-Saint Exupéry", body: "Transfert direct vers l'aéroport, catégorie adaptée au nombre de bagages annoncés." },
      { title: "Part-Dieu → Lyon centre", body: "Trajet court vers la Presqu'île, Confluence ou un autre quartier de Lyon." },
      { title: "Part-Dieu → Villeurbanne", body: "Trajet vers Villeurbanne, à proximité immédiate de la gare." },
    ],
    extraTitle: "Voyageurs et bagages",
    extraBody: "Indiquez le nombre de passagers et de bagages lors de votre demande : KDRIVE confirme la catégorie de véhicule la plus adaptée (Essentiel ou Premium pour les groupes réduits ; Van pour davantage de bagages ou de passagers).",
    faq: [
      { q: "KDRIVE suit-il mon train en temps réel ?", a: "Non, aucun suivi automatique des correspondances n'est en place actuellement ; en cas de retard, contactez KDRIVE pour ajuster l'heure de prise en charge." },
      { q: "Où se fait la prise en charge à la gare Part-Dieu ?", a: "Le point de prise en charge précis est confirmé avec vous au moment de la réservation, selon les zones d'accès autorisées de la gare (côté Vivier-Merle ou côté Villette)." },
      { q: "Puis-je réserver un Van pour plusieurs bagages ?", a: "Oui, la catégorie Van est calculée comme les autres catégories. KDRIVE vous contacte par téléphone après votre demande pour confirmer le tarif et la disponibilité." },
    ],
    pillarLinksTitle: "Poursuivre votre réservation",
    pillarLinks: [
      { href: "/transfert-gare", label: "Transfert gare" },
      { href: "/transfert-aeroport", label: "Transfert aéroport" },
      { href: "/vehicules", label: "Nos véhicules" },
      { href: "/tarifs", label: "Grille tarifaire" },
      { href: "/reserver", label: "Réserver un trajet" },
    ],
  },
  {
    slug: "vtc-lyon-perrache",
    family: "gare",
    editorialStatus: "readyForIndexing",
    title: "VTC Gare Lyon Perrache | Chauffeur privé | KDRIVE",
    metaDescription: "Chauffeur privé à la gare de Lyon Perrache : prise en charge organisée selon votre horaire de train, tarif confirmé avant votre trajet.",
    eyebrow: "VTC Lyon Perrache",
    h1: "Chauffeur privé gare de Lyon Perrache",
    breadcrumbParent: { label: "Transfert gare", href: "/transfert-gare" },
    neighborLinksTitle: "Autour de Perrache",
    neighborLinks: [
      { href: "/vtc-lyon-2e-arrondissement", label: "Lyon 2e arrondissement" },
      { href: "/transfert-gare", label: "Toutes les gares de Lyon" },
    ],
    heroLead: "Une prise en charge organisée pour votre arrivée ou votre départ depuis la gare de Lyon Perrache, sur réservation.",
    heroImage: "/images/hero-lyon.jpg",
    presentationTitle: "Un transfert au cœur de la Presqu'île",
    presentationBody: [
      "La gare de Lyon Perrache se trouve à la pointe de la Presqu'île, entre Saône et Rhône, à quelques minutes de la Confluence et du centre-ville. KDRIVE y organise des prises en charge pour les voyageurs, avec ou sans bagages, sur la base de l'horaire indiqué lors de la réservation.",
      "Aucune correspondance n'est suivie automatiquement en temps réel : en cas de changement d'horaire, contactez KDRIVE dès que possible afin d'ajuster la prise en charge.",
    ],
    practicalInfoTitle: "Repères pour votre venue à Perrache",
    practicalInfoItems: [
      "Adresse : 14 cours de Verdun, 69002 Lyon (2ᵉ arrondissement), quartier de Perrache.",
      "La gare donne sur la place Carnot au nord ; le centre d'échanges de Perrache (niveau 1) relie la gare au métro, au tramway et aux bus.",
      "Métro A et tramways T1/T2 desservent directement le pôle d'échanges.",
      "Depuis janvier 2026, la gare routière longue distance (FlixBus, BlaBlaBus, Itabus) a été transférée à Gerland (7ᵉ arrondissement) : elle ne se trouve plus à Perrache.",
    ],
    frequentTrips: [
      { title: "Perrache → Confluence", body: "Trajet court vers le quartier de la Confluence, en catégorie Essentiel ou Premium selon votre besoin." },
      { title: "Perrache → Presqu'île / Bellecour", body: "Trajet vers le centre-ville de Lyon, à quelques minutes de la gare." },
      { title: "Perrache → Aéroport Lyon-Saint Exupéry", body: "Transfert direct vers l'aéroport, sans passer par un autre point de correspondance." },
    ],
    extraTitle: "Un point de départ pour vos correspondances longue distance",
    extraBody: "Si votre trajet se poursuit en car (FlixBus, BlaBlaBus, Itabus), sachez que la gare routière de ces compagnies a quitté Perrache pour Gerland début 2026 : précisez votre point de départ ou d'arrivée exact lors de votre demande, KDRIVE organise la prise en charge en conséquence.",
    faq: [
      { q: "KDRIVE suit-il mon train en temps réel ?", a: "Non, aucun suivi automatique des correspondances n'est en place actuellement ; en cas de retard, contactez KDRIVE pour ajuster l'heure de prise en charge." },
      { q: "Où se fait la prise en charge à la gare Perrache ?", a: "Le point de prise en charge précis est confirmé avec vous au moment de la réservation, selon les zones d'accès autorisées (parvis, place Carnot ou centre d'échanges)." },
      { q: "Puis-je réserver un VTC pour un départ en car FlixBus ou BlaBlaBus ?", a: "Oui, mais la gare routière de ces compagnies n'est plus à Perrache depuis janvier 2026 : elle se trouve désormais à Gerland. Indiquez l'adresse exacte lors de votre demande." },
    ],
    pillarLinksTitle: "Poursuivre votre réservation",
    pillarLinks: [
      { href: "/transfert-gare", label: "Transfert gare" },
      { href: "/transfert-aeroport", label: "Transfert aéroport" },
      { href: "/vehicules", label: "Nos véhicules" },
      { href: "/tarifs", label: "Grille tarifaire" },
      { href: "/reserver", label: "Réserver un trajet" },
    ],
  },
  {
    slug: "vtc-gare-lyon-saint-exupery-tgv",
    family: "gare",
    editorialStatus: "readyForIndexing",
    title: "VTC Gare Lyon Saint-Exupéry TGV | KDRIVE",
    metaDescription: "Chauffeur privé à la gare de Lyon Saint-Exupéry TGV : prise en charge sur réservation, distincte des terminaux aéroportuaires.",
    eyebrow: "VTC Gare Lyon Saint-Exupéry TGV",
    h1: "Votre VTC à la gare Lyon Saint-Exupéry TGV",
    breadcrumbParent: { label: "Transfert gare", href: "/transfert-gare" },
    heroLead: "Une prise en charge organisée pour votre arrivée ou votre départ depuis la gare ferroviaire de Lyon Saint-Exupéry TGV, sur réservation.",
    heroImage: "/images/service-transferts.jpg",
    prefillAddress: gareTgvAddress,
    prefillLabel: "la gare TGV",
    presentationTitle: "Une gare ferroviaire à part entière, distincte des terminaux",
    presentationBody: [
      "La gare de Lyon-Saint-Exupéry TGV accueille des trains TGV et Ouigo, dans un bâtiment distinct des terminaux aéroportuaires, relié à eux par une passerelle piétonne. KDRIVE y organise des prises en charge pour les voyageurs, avec ou sans bagages, sur la base de l'horaire indiqué lors de la réservation.",
      "Aucune correspondance n'est suivie automatiquement en temps réel : en cas de changement d'horaire, contactez KDRIVE dès que possible afin d'ajuster la prise en charge.",
    ],
    departureArrivalTitle: "Un chauffeur pour votre départ ou votre arrivée en train",
    departure: { title: "Au départ", body: "Votre chauffeur vient vous chercher à l'adresse indiquée lors de la réservation, avec la marge nécessaire pour rejoindre la gare avant l'heure de votre train." },
    arrival: { title: "À l'arrivée", body: "Indiquez l'heure d'arrivée prévue de votre train lors de la demande. Le point de rendez-vous précis à la gare est ensuite confirmé avec vous ; aucun suivi automatique des trains n'est en place, contactez KDRIVE en cas de changement d'horaire." },
    practicalInfoTitle: "Repères pour votre venue à la gare TGV",
    practicalInfoItems: [
      "La gare se trouve à Colombier-Saugnieu, au sein du complexe aéroportuaire mais dans un bâtiment distinct des terminaux, reconnaissable à son architecture (conception Santiago Calatrava).",
      "Elle est reliée au Terminal 1 par une passerelle piétonne d'environ 250 mètres avec tapis roulant, et au Terminal 2 par un cheminement équivalent.",
      "La gare dessert des trains TGV et Ouigo, ainsi que la liaison Rhônexpress vers le centre de Lyon.",
      "Ne confondez pas la gare TGV et les terminaux aéroportuaires lors de votre réservation : précisez votre point de départ ou d'arrivée exact.",
    ],
    frequentTrips: [
      { title: "Gare TGV → Lyon centre", body: "Trajet vers la Presqu'île ou le centre-ville de Lyon." },
      { title: "Gare TGV → Villeurbanne", body: "Trajet vers Villeurbanne, à proximité du secteur aéroportuaire.", href: "/vtc-villeurbanne" },
      { title: "Gare TGV → Saint-Priest", body: "Trajet vers la commune de Saint-Priest, à proximité de l'aéroport.", href: "/vtc-saint-priest" },
    ],
    pricingTitle: "Estimer et réserver votre trajet",
    pricingBody: "KDRIVE vous contacte par téléphone après votre demande pour vous communiquer le tarif, calculé selon la catégorie de véhicule et le trajet, avant toute confirmation.",
    faq: [
      { q: "Comment préciser qu'il s'agit de la gare TGV et non de l'aéroport ?", a: "La gare TGV et les terminaux aéroportuaires sont deux points distincts au sein du même complexe : indiquez précisément votre lieu de rendez-vous lors de la réservation pour éviter toute confusion." },
      { q: "Comment signaler un changement d'horaire de mon train ?", a: "Contactez KDRIVE par téléphone dès que possible : aucun suivi automatique des horaires SNCF n'est en place, l'ajustement de la prise en charge se fait par échange direct avec l'équipe." },
      { q: "Quelles informations de train transmettre lors de la réservation ?", a: "Le numéro de train n'est pas requis ; l'heure d'arrivée ou de départ prévue, le nombre de passagers et de bagages suffisent pour envoyer votre demande." },
      { q: "Comment sont pris en compte les passagers et les bagages ?", a: "Indiquez le nombre exact de passagers et de bagages dans le formulaire : KDRIVE confirme la catégorie de véhicule la plus adaptée (Essentiel, Premium ou Van)." },
      { q: "Puis-je réserver un VTC pour rejoindre un terminal depuis la gare TGV ?", a: "Les terminaux sont accessibles à pied depuis la gare TGV via la passerelle piétonne. KDRIVE n'organise pas de transfert motorisé pour ce trajet court ; pour un vol, consultez la page transfert aéroport." },
    ],
    pillarLinksTitle: "Poursuivre votre réservation",
    pillarLinks: [
      { href: "/transfert-gare", label: "Transfert gare" },
      { href: "/transfert-aeroport", label: "Transfert aéroport" },
      { href: "/vehicules", label: "Nos véhicules" },
      { href: "/tarifs", label: "Grille tarifaire" },
      { href: "/reserver", label: "Réserver un trajet" },
    ],
  },
  {
    slug: "vtc-lyon-grenoble",
    family: "longue-distance",
    editorialStatus: "readyForIndexing",
    title: "Transfert Lyon – Grenoble | Chauffeur privé | KDRIVE",
    metaDescription: "Trajet longue distance entre Lyon et Grenoble avec chauffeur privé : tarif calculé sur la distance réelle, confirmé avant votre départ.",
    eyebrow: "VTC Lyon Grenoble",
    h1: "Chauffeur privé Lyon – Grenoble",
    breadcrumbParent: { label: "Longues distances", href: "/longues-distances" },
    neighborLinksTitle: "Autres longues distances",
    neighborLinks: [
      { href: "/longues-distances", label: "Toutes les longues distances" },
      { href: "/transfert-lyon-chambery", label: "Lyon – Chambéry" },
      { href: "/transfert-lyon-annecy", label: "Lyon – Annecy" },
    ],
    heroLead: "Un trajet longue distance entre Lyon et Grenoble avec un chauffeur privé, sur réservation à l'avance.",
    heroImage: "/images/hero-longues-distances.jpg",
    presentationTitle: "Une liaison longue distance confirmée par l'équipe KDRIVE",
    presentationBody: [
      "Le trajet entre Lyon et Grenoble est traité par KDRIVE comme une longue distance : le tarif est calculé à partir de la distance réelle, sans facturation à la minute, et confirmé par l'équipe avant votre départ.",
      "Une réservation à l'avance est recommandée pour ce type de trajet, afin de permettre la préparation du véhicule et la confirmation du tarif dans de bonnes conditions.",
    ],
    frequentTrips: [
      { title: "Lyon → Grenoble", body: "Trajet direct, catégorie Essentiel ou Premium selon le niveau de prestation souhaité." },
      { title: "Grenoble → Aéroport Lyon-Saint Exupéry", body: "Liaison vers l'aéroport pour un vol au départ de Lyon-Saint Exupéry." },
      { title: "Grenoble → Lyon centre", body: "Trajet retour vers le centre de Lyon ou un autre point de la métropole." },
    ],
    extraTitle: "Bagages et arrêts éventuels",
    extraBody: "Indiquez vos besoins en bagages lors de la réservation ; un arrêt intermédiaire peut être évoqué avec l'équipe KDRIVE au moment de la confirmation, selon la faisabilité du trajet. Aucun prix fixe n'est affiché avant confirmation : le tarif dépend de la distance réelle du trajet demandé.",
    faq: [
      { q: "Le tarif Lyon-Grenoble est-il fixe ?", a: "Non, le tarif est calculé à partir de la distance réelle de votre trajet et confirmé par KDRIVE avant votre départ ; aucun prix fixe n'est affiché à l'avance sur cette page." },
      { q: "Faut-il réserver longtemps à l'avance ?", a: "Une réservation anticipée est recommandée pour un trajet longue distance, afin de permettre une confirmation dans de bonnes conditions." },
      { q: "Puis-je demander un arrêt en cours de route ?", a: "Cette possibilité peut être évoquée avec l'équipe KDRIVE au moment de la confirmation du trajet, selon sa faisabilité." },
    ],
    pillarLinksTitle: "Poursuivre votre réservation",
    pillarLinks: [
      { href: "/longues-distances", label: "Longues distances" },
      { href: "/vehicules", label: "Nos véhicules" },
      { href: "/tarifs", label: "Grille tarifaire" },
      { href: "/reserver", label: "Réserver un trajet" },
      { href: "/contact", label: "Contacter KDRIVE" },
    ],
  },
  {
    slug: "vtc-bron",
    family: "commune",
    editorialStatus: "readyForIndexing",
    title: "VTC Bron | Chauffeur privé | KDRIVE",
    metaDescription: "Chauffeur privé à Bron : trajets vers Lyon, l'aéroport Lyon-Saint Exupéry et la gare Part-Dieu, tarif confirmé par téléphone avant votre course.",
    eyebrow: "VTC Bron",
    h1: "Chauffeur privé à Bron",
    breadcrumbParent: { label: "Banlieue est", href: "/vtc-banlieue-est-lyon" },
    neighborLinksTitle: "Communes voisines",
    neighborLinks: [
      { href: "/vtc-banlieue-est-lyon", label: "Banlieue est de Lyon" },
      { href: "/vtc-lyon-8e-arrondissement", label: "Lyon 8e arrondissement" },
      { href: "/vtc-saint-priest", label: "VTC Saint-Priest" },
      { href: "/vtc-eurexpo-lyon", label: "VTC Eurexpo Lyon" },
    ],
    heroLead: "Un service de VTC premium pour vos trajets au départ ou à destination de Bron, avec un tarif calculé avant confirmation.",
    heroImage: "/images/service-affaires.jpg",
    presentationTitle: "KDRIVE dessert Bron",
    presentationBody: [
      "Bron se situe à l'est de Lyon, sur l'axe menant à l'aéroport Lyon-Saint Exupéry. KDRIVE y assure des prises en charge pour des trajets vers le centre de Lyon, l'aéroport ou d'autres communes de la métropole.",
      "Ce secteur peut convenir à des trajets professionnels ou vers l'aéroport, sans que cela ne constitue une clientèle type : chaque demande est traitée individuellement selon le trajet indiqué.",
    ],
    frequentTrips: [
      { title: "Bron → Lyon centre", body: "Trajet vers la Presqu'île ou un autre quartier du centre de Lyon." },
      { title: "Bron → Aéroport Lyon-Saint Exupéry", body: "Un axe direct vers l'aéroport, avec suivi de votre numéro de vol si vous le renseignez." },
      { title: "Bron → Gare Part-Dieu", body: "Transfert vers la gare de la Part-Dieu, sur la base de votre horaire de train." },
    ],
    faq: [
      { q: "KDRIVE dessert-il tout Bron ?", a: "KDRIVE prend en charge les demandes de VTC à Bron au cas par cas ; chaque demande est confirmée individuellement par l'équipe avant la course." },
      { q: "Puis-je réserver un trajet professionnel depuis Bron ?", a: "Oui, la catégorie Premium est recommandée pour un déplacement professionnel ; le tarif est communiqué par téléphone avant confirmation." },
      { q: "Le trajet vers l'aéroport est-il rapide depuis Bron ?", a: "Aucun délai n'est garanti à l'avance ; la durée dépend du trafic au moment du trajet." },
    ],
    pillarLinksTitle: "Poursuivre votre réservation",
    pillarLinks: [
      { href: "/transfert-aeroport", label: "Transfert aéroport" },
      { href: "/chauffeur-entreprise", label: "Chauffeur entreprise" },
      { href: "/vehicules", label: "Nos véhicules" },
      { href: "/tarifs", label: "Grille tarifaire" },
      { href: "/reserver", label: "Réserver un trajet" },
    ],
  },
  {
    slug: "vtc-saint-priest",
    family: "commune",
    editorialStatus: "readyForIndexing",
    title: "VTC Saint-Priest | Chauffeur privé | KDRIVE",
    metaDescription: "Chauffeur privé à Saint-Priest : trajets vers Lyon, l'aéroport et longues distances, tarif confirmé par téléphone avant votre course.",
    eyebrow: "VTC Saint-Priest",
    h1: "Chauffeur privé à Saint-Priest",
    breadcrumbParent: { label: "Banlieue est", href: "/vtc-banlieue-est-lyon" },
    neighborLinksTitle: "Communes voisines",
    neighborLinks: [
      { href: "/vtc-banlieue-est-lyon", label: "Banlieue est de Lyon" },
      { href: "/vtc-bron", label: "VTC Bron" },
      { href: "/vtc-eurexpo-lyon", label: "VTC Eurexpo Lyon" },
    ],
    heroLead: "Un service de VTC premium pour vos trajets au départ ou à destination de Saint-Priest, avec un tarif calculé avant confirmation.",
    heroImage: "/images/corporate.jpg",
    presentationTitle: "KDRIVE dessert Saint-Priest",
    presentationBody: [
      "Saint-Priest se situe au sud-est de la métropole lyonnaise. KDRIVE y assure des prises en charge pour des trajets vers Lyon, l'aéroport ou des déplacements professionnels, ainsi que pour des trajets longue distance au départ de la commune.",
      "Ce secteur regroupe plusieurs zones d'activité, sans que cela ne constitue une preuve de clientèle établie : chaque demande est traitée individuellement selon le trajet indiqué.",
    ],
    frequentTrips: [
      { title: "Saint-Priest → Lyon centre", body: "Trajet vers le centre de Lyon, catégorie Essentiel ou Premium selon votre besoin." },
      { title: "Saint-Priest → Aéroport Lyon-Saint Exupéry", body: "Transfert vers l'aéroport, avec suivi de votre numéro de vol si vous le renseignez." },
      { title: "Saint-Priest → Longue distance", body: "Pour un trajet au-delà de la métropole lyonnaise, le tarif est calculé à partir de la distance réelle." },
    ],
    faq: [
      { q: "KDRIVE dessert-il tout Saint-Priest ?", a: "KDRIVE prend en charge les demandes de VTC à Saint-Priest au cas par cas ; chaque demande est confirmée individuellement par l'équipe avant la course." },
      { q: "Puis-je réserver un trajet longue distance depuis Saint-Priest ?", a: "Oui, le tarif est alors calculé à partir de la distance réelle du trajet et confirmé avant votre départ." },
      { q: "Quel véhicule pour un déplacement professionnel ?", a: "La catégorie Premium est recommandée pour un rendez-vous professionnel." },
    ],
    pillarLinksTitle: "Poursuivre votre réservation",
    pillarLinks: [
      { href: "/transfert-aeroport", label: "Transfert aéroport" },
      { href: "/longues-distances", label: "Longues distances" },
      { href: "/reserver", label: "Réserver un trajet" },
      { href: "/vehicules", label: "Nos véhicules" },
      { href: "/tarifs", label: "Grille tarifaire" },
    ],
  },
];
