import type { LocalPageContent } from "./local-page-template";

export const localPages: LocalPageContent[] = [
  {
    slug: "vtc-villeurbanne",
    eyebrow: "VTC Villeurbanne",
    h1: "Chauffeur privé à Villeurbanne",
    heroLead: "Un service de VTC premium pour vos trajets au départ ou à destination de Villeurbanne, avec un tarif calculé avant confirmation.",
    heroImage: "/images/hero-lyon.jpg",
    presentationTitle: "KDRIVE dessert Villeurbanne",
    presentationBody: [
      "Villeurbanne est une commune limitrophe de Lyon, à proximité immédiate de la gare de la Part-Dieu. KDRIVE y assure des prises en charge pour des trajets vers le centre de Lyon, la gare ou l'aéroport, ainsi que pour des déplacements professionnels.",
      "Chaque demande est confirmée individuellement par l'équipe KDRIVE, avec un tarif calculé à partir de la distance réelle avant toute confirmation.",
    ],
    frequentTrips: [
      { title: "Villeurbanne → Lyon centre", body: "Trajet vers la Presqu'île ou le centre-ville de Lyon, en catégorie Essentiel ou Premium selon votre besoin." },
      { title: "Villeurbanne → Gare Part-Dieu", body: "La gare de la Part-Dieu se trouve à proximité de Villeurbanne. Indiquez votre horaire de train lors de la réservation." },
      { title: "Villeurbanne → Aéroport Lyon-Saint Exupéry", body: "Un transfert avec suivi de votre numéro de vol, pour anticiper un éventuel ajustement d'horaire." },
    ],
    extraTitle: "Déplacements professionnels depuis Villeurbanne",
    extraBody: "KDRIVE accompagne aussi les déplacements professionnels au départ de Villeurbanne : rendez-vous client, trajet vers un site d'entreprise ou transfert vers une gare pour un déplacement d'affaires. La catégorie Premium est recommandée pour ce type de trajet.",
    faq: [
      { q: "KDRIVE dessert-il tout Villeurbanne ?", a: "KDRIVE prend en charge les demandes de VTC à Villeurbanne au cas par cas ; chaque demande est confirmée individuellement par l'équipe avant la course." },
      { q: "Combien de temps pour rejoindre la Part-Dieu depuis Villeurbanne ?", a: "La durée dépend du trafic et de l'adresse exacte de départ ; aucun délai n'est garanti à l'avance, mais le trajet est proche de Lyon." },
      { q: "Quel véhicule choisir pour un trajet professionnel ?", a: "La catégorie Premium est adaptée aux rendez-vous professionnels ; Essentiel convient pour un trajet simple." },
    ],
    pillarLinksTitle: "Poursuivre votre réservation",
    pillarLinks: [
      { href: "/transfert-aeroport", label: "Transfert aéroport" },
      { href: "/transfert-gare", label: "Transfert gare" },
      { href: "/chauffeur-entreprise", label: "Chauffeur entreprise" },
      { href: "/vehicules", label: "Nos véhicules" },
      { href: "/tarifs", label: "Grille tarifaire" },
      { href: "/reserver", label: "Réserver un trajet" },
    ],
  },
  {
    slug: "vtc-lyon-part-dieu",
    eyebrow: "VTC Lyon Part-Dieu",
    h1: "Chauffeur privé gare de Lyon Part-Dieu",
    heroLead: "Une prise en charge organisée pour votre arrivée ou votre départ depuis la gare de Lyon Part-Dieu, sur réservation.",
    heroImage: "/images/service-transferts.jpg",
    presentationTitle: "Un transfert préparé autour de votre horaire de train",
    presentationBody: [
      "La gare de Lyon Part-Dieu est l'une des principales gares de correspondance de la région lyonnaise. KDRIVE y organise des prises en charge pour les voyageurs, avec ou sans bagages, sur la base de l'horaire indiqué lors de la réservation.",
      "Aucune correspondance n'est suivie automatiquement en temps réel : en cas de changement d'horaire, contactez KDRIVE dès que possible afin d'ajuster la prise en charge.",
    ],
    frequentTrips: [
      { title: "Part-Dieu → Aéroport Lyon-Saint Exupéry", body: "Transfert direct vers l'aéroport, catégorie adaptée au nombre de bagages annoncés." },
      { title: "Part-Dieu → Lyon centre", body: "Trajet court vers la Presqu'île, Confluence ou un autre quartier de Lyon." },
      { title: "Part-Dieu → Villeurbanne", body: "Trajet vers Villeurbanne, à proximité immédiate de la gare." },
    ],
    extraTitle: "Voyageurs et bagages",
    extraBody: "Indiquez le nombre de passagers et de bagages lors de votre demande : KDRIVE confirme la catégorie de véhicule la plus adaptée (Essentiel ou Premium pour les groupes réduits ; Van pour davantage de bagages ou de passagers).",
    faq: [
      { q: "KDRIVE suit-il mon train en temps réel ?", a: "Non, aucun suivi automatique des correspondances n'est en place actuellement ; en cas de retard, contactez KDRIVE pour ajuster l'heure de prise en charge." },
      { q: "Où se fait la prise en charge à la gare Part-Dieu ?", a: "Le point de prise en charge précis est confirmé avec vous au moment de la réservation, selon les zones d'accès autorisées de la gare." },
      { q: "Puis-je réserver un Van pour plusieurs bagages ?", a: "Oui, la catégorie Van fait l'objet d'un devis personnalisé pour les groupes ou les trajets avec de nombreux bagages." },
    ],
    pillarLinksTitle: "Poursuivre votre réservation",
    pillarLinks: [
      { href: "/transfert-gare", label: "Transfert gare" },
      { href: "/transfert-aeroport", label: "Transfert aéroport" },
      { href: "/vehicules", label: "Nos véhicules" },
      { href: "/tarifs", label: "Grille tarifaire" },
      { href: "/reserver", label: "Réserver un trajet" },
    ],
  },
  {
    slug: "vtc-lyon-grenoble",
    eyebrow: "VTC Lyon Grenoble",
    h1: "Chauffeur privé Lyon – Grenoble",
    heroLead: "Un trajet longue distance entre Lyon et Grenoble avec un chauffeur privé, sur réservation à l'avance.",
    heroImage: "/images/hero-longues-distances.jpg",
    presentationTitle: "Une liaison longue distance confirmée par l'équipe KDRIVE",
    presentationBody: [
      "Le trajet entre Lyon et Grenoble est traité par KDRIVE comme une longue distance : le tarif est calculé à partir de la distance réelle, sans facturation à la minute, et confirmé par l'équipe avant votre départ.",
      "Une réservation à l'avance est recommandée pour ce type de trajet, afin de permettre la préparation du véhicule et la confirmation du tarif dans de bonnes conditions.",
    ],
    frequentTrips: [
      { title: "Lyon → Grenoble", body: "Trajet direct, catégorie Essentiel ou Premium selon le niveau de prestation souhaité." },
      { title: "Grenoble → Aéroport Lyon-Saint Exupéry", body: "Liaison vers l'aéroport pour un vol au départ de Lyon-Saint Exupéry." },
      { title: "Grenoble → Lyon centre", body: "Trajet retour vers le centre de Lyon ou un autre point de la métropole." },
    ],
    extraTitle: "Bagages et arrêts éventuels",
    extraBody: "Indiquez vos besoins en bagages lors de la réservation ; un arrêt intermédiaire peut être évoqué avec l'équipe KDRIVE au moment de la confirmation, selon la faisabilité du trajet. Aucun prix fixe n'est affiché avant confirmation : le tarif dépend de la distance réelle du trajet demandé.",
    faq: [
      { q: "Le tarif Lyon-Grenoble est-il fixe ?", a: "Non, le tarif est calculé à partir de la distance réelle de votre trajet et confirmé par KDRIVE avant votre départ ; aucun prix fixe n'est affiché à l'avance sur cette page." },
      { q: "Faut-il réserver longtemps à l'avance ?", a: "Une réservation anticipée est recommandée pour un trajet longue distance, afin de permettre une confirmation dans de bonnes conditions." },
      { q: "Puis-je demander un arrêt en cours de route ?", a: "Cette possibilité peut être évoquée avec l'équipe KDRIVE au moment de la confirmation du trajet, selon sa faisabilité." },
    ],
    pillarLinksTitle: "Poursuivre votre réservation",
    pillarLinks: [
      { href: "/longues-distances", label: "Longues distances" },
      { href: "/vehicules", label: "Nos véhicules" },
      { href: "/tarifs", label: "Grille tarifaire" },
      { href: "/reserver", label: "Réserver un trajet" },
      { href: "/contact", label: "Contacter KDRIVE" },
    ],
  },
  {
    slug: "vtc-bron",
    eyebrow: "VTC Bron",
    h1: "Chauffeur privé à Bron",
    heroLead: "Un service de VTC premium pour vos trajets au départ ou à destination de Bron, avec un tarif calculé avant confirmation.",
    heroImage: "/images/service-affaires.jpg",
    presentationTitle: "KDRIVE dessert Bron",
    presentationBody: [
      "Bron se situe à l'est de Lyon, sur l'axe menant à l'aéroport Lyon-Saint Exupéry. KDRIVE y assure des prises en charge pour des trajets vers le centre de Lyon, l'aéroport ou d'autres communes de la métropole.",
      "Ce secteur peut convenir à des trajets professionnels ou vers l'aéroport, sans que cela ne constitue une clientèle type : chaque demande est traitée individuellement selon le trajet indiqué.",
    ],
    frequentTrips: [
      { title: "Bron → Lyon centre", body: "Trajet vers la Presqu'île ou un autre quartier du centre de Lyon." },
      { title: "Bron → Aéroport Lyon-Saint Exupéry", body: "Un axe direct vers l'aéroport, avec suivi de votre numéro de vol si vous le renseignez." },
      { title: "Bron → Gare Part-Dieu", body: "Transfert vers la gare de la Part-Dieu, sur la base de votre horaire de train." },
    ],
    faq: [
      { q: "KDRIVE dessert-il tout Bron ?", a: "KDRIVE prend en charge les demandes de VTC à Bron au cas par cas ; chaque demande est confirmée individuellement par l'équipe avant la course." },
      { q: "Puis-je réserver un trajet professionnel depuis Bron ?", a: "Oui, la catégorie Premium est recommandée pour un déplacement professionnel ; le tarif est communiqué par téléphone avant confirmation." },
      { q: "Le trajet vers l'aéroport est-il rapide depuis Bron ?", a: "Aucun délai n'est garanti à l'avance ; la durée dépend du trafic au moment du trajet." },
    ],
    pillarLinksTitle: "Poursuivre votre réservation",
    pillarLinks: [
      { href: "/transfert-aeroport", label: "Transfert aéroport" },
      { href: "/chauffeur-entreprise", label: "Chauffeur entreprise" },
      { href: "/vehicules", label: "Nos véhicules" },
      { href: "/tarifs", label: "Grille tarifaire" },
      { href: "/reserver", label: "Réserver un trajet" },
    ],
  },
  {
    slug: "vtc-saint-priest",
    eyebrow: "VTC Saint-Priest",
    h1: "Chauffeur privé à Saint-Priest",
    heroLead: "Un service de VTC premium pour vos trajets au départ ou à destination de Saint-Priest, avec un tarif calculé avant confirmation.",
    heroImage: "/images/corporate.jpg",
    presentationTitle: "KDRIVE dessert Saint-Priest",
    presentationBody: [
      "Saint-Priest se situe au sud-est de la métropole lyonnaise. KDRIVE y assure des prises en charge pour des trajets vers Lyon, l'aéroport ou des déplacements professionnels, ainsi que pour des trajets longue distance au départ de la commune.",
      "Ce secteur regroupe plusieurs zones d'activité, sans que cela ne constitue une preuve de clientèle établie : chaque demande est traitée individuellement selon le trajet indiqué.",
    ],
    frequentTrips: [
      { title: "Saint-Priest → Lyon centre", body: "Trajet vers le centre de Lyon, catégorie Essentiel ou Premium selon votre besoin." },
      { title: "Saint-Priest → Aéroport Lyon-Saint Exupéry", body: "Transfert vers l'aéroport, avec suivi de votre numéro de vol si vous le renseignez." },
      { title: "Saint-Priest → Longue distance", body: "Pour un trajet au-delà de la métropole lyonnaise, le tarif est calculé à partir de la distance réelle." },
    ],
    faq: [
      { q: "KDRIVE dessert-il tout Saint-Priest ?", a: "KDRIVE prend en charge les demandes de VTC à Saint-Priest au cas par cas ; chaque demande est confirmée individuellement par l'équipe avant la course." },
      { q: "Puis-je réserver un trajet longue distance depuis Saint-Priest ?", a: "Oui, le tarif est alors calculé à partir de la distance réelle du trajet et confirmé avant votre départ." },
      { q: "Quel véhicule pour un déplacement professionnel ?", a: "La catégorie Premium est recommandée pour un rendez-vous professionnel." },
    ],
    pillarLinksTitle: "Poursuivre votre réservation",
    pillarLinks: [
      { href: "/transfert-aeroport", label: "Transfert aéroport" },
      { href: "/longues-distances", label: "Longues distances" },
      { href: "/reserver", label: "Réserver un trajet" },
      { href: "/vehicules", label: "Nos véhicules" },
      { href: "/tarifs", label: "Grille tarifaire" },
    ],
  },
];
