import type { LocalPageContent } from "./local-page-template";

/**
 * Destinations longue distance au départ de Lyon (hors Grenoble, déjà
 * couvert par vtc-lyon-grenoble dans local-pages-content.ts — pas de
 * doublon créé, cf. rapport de sprint). Chaque page couvre les deux sens du
 * trajet. Aucun kilométrage, durée figée ou prix n'est inventé : le
 * fonctionnement tarifaire réel (devis KDRIVE) est repris de la page pilier
 * /longues-distances. Pour Genève, aucune formalité n'est présentée comme un
 * conseil juridique : la page renvoie à une vérification personnelle des
 * documents nécessaires.
 */

const longDistancePillarLinks: LocalPageContent["pillarLinks"] = [
  { href: "/longues-distances", label: "Toutes les longues distances" },
  { href: "/vehicules", label: "Nos véhicules" },
  { href: "/tarifs", label: "Grille tarifaire" },
  { href: "/reserver", label: "Réserver un trajet" },
  { href: "/contact", label: "Contacter KDRIVE" },
];

function longDistanceFaq(destination: string): { q: string; a: string }[] {
  return [
    { q: `Le tarif Lyon – ${destination} est-il fixe ?`, a: "Non, le tarif est calculé à partir de la distance réelle de votre trajet et confirmé par KDRIVE avant votre départ ; aucun prix fixe n'est affiché à l'avance sur cette page." },
    { q: "Faut-il réserver longtemps à l'avance ?", a: "Une réservation anticipée est recommandée pour un trajet longue distance, afin de permettre une confirmation dans de bonnes conditions." },
    { q: "Le trajet retour est-il possible dans les mêmes conditions ?", a: "Oui, cette page couvre les deux sens du trajet ; indiquez le sens souhaité lors de votre demande." },
  ];
}

export const longueDistancePages: LocalPageContent[] = [
  {
    slug: "transfert-lyon-annecy",
    family: "longue-distance",
    editorialStatus: "needsEnrichment",
    title: "Transfert Lyon – Annecy | Chauffeur privé | KDRIVE",
    metaDescription: "Trajet longue distance entre Lyon et Annecy avec chauffeur privé : tarif calculé sur la distance réelle, confirmé avant votre départ.",
    eyebrow: "Transfert Lyon – Annecy",
    h1: "Chauffeur privé Lyon – Annecy",
    breadcrumbParent: { label: "Longues distances", href: "/longues-distances" },
    heroImage: "/images/hero-longues-distances.jpg",
    heroLead: "Un trajet longue distance entre Lyon et Annecy avec un chauffeur privé, dans les deux sens, sur réservation à l'avance.",
    presentationTitle: "Une liaison longue distance confirmée par l'équipe KDRIVE",
    presentationBody: [
      "Le trajet entre Lyon et Annecy, au bord du lac, est traité par KDRIVE comme une longue distance : le tarif est calculé à partir de la distance réelle et confirmé par l'équipe avant votre départ, dans les deux sens du trajet.",
      "Une réservation à l'avance est recommandée, notamment en période de forte affluence touristique autour du lac d'Annecy.",
    ],
    casUsageTitle: "Motifs de déplacement courants",
    casUsageItems: [
      "Trajet professionnel entre Lyon et Annecy.",
      "Trajet touristique ou de loisirs vers le lac d'Annecy.",
      "Correspondance avec un vol ou un train à Lyon depuis Annecy.",
    ],
    frequentTrips: [
      { title: "Lyon → Annecy", body: "Trajet direct, catégorie Essentiel ou Premium selon le niveau de prestation souhaité." },
      { title: "Annecy → Aéroport Lyon-Saint Exupéry", body: "Liaison vers l'aéroport pour un vol au départ de Lyon.", href: "/transfert-aeroport" },
      { title: "Annecy → Lyon centre", body: "Trajet retour vers le centre de Lyon ou un autre point de la métropole." },
    ],
    faq: longDistanceFaq("Annecy"),
    neighborLinksTitle: "Autres longues distances",
    neighborLinks: [
      { href: "/transfert-lyon-chambery", label: "Lyon – Chambéry" },
      { href: "/transfert-lyon-geneve", label: "Lyon – Genève" },
      { href: "/vtc-lyon-grenoble", label: "Lyon – Grenoble" },
    ],
    pillarLinksTitle: "Poursuivre votre réservation",
    pillarLinks: longDistancePillarLinks,
    sources: ["Connaissance générale (Annecy, lac d'Annecy) — aucune donnée de distance/durée affichée, conformément au brief."],
  },
  {
    slug: "transfert-lyon-chambery",
    family: "longue-distance",
    editorialStatus: "needsEnrichment",
    title: "Transfert Lyon – Chambéry | Chauffeur privé | KDRIVE",
    metaDescription: "Trajet longue distance entre Lyon et Chambéry avec chauffeur privé : tarif calculé sur la distance réelle, confirmé avant votre départ.",
    eyebrow: "Transfert Lyon – Chambéry",
    h1: "Chauffeur privé Lyon – Chambéry",
    breadcrumbParent: { label: "Longues distances", href: "/longues-distances" },
    heroImage: "/images/hero-longues-distances.jpg",
    heroLead: "Un trajet longue distance entre Lyon et Chambéry avec un chauffeur privé, dans les deux sens, sur réservation à l'avance.",
    presentationTitle: "Une liaison longue distance confirmée par l'équipe KDRIVE",
    presentationBody: [
      "Le trajet entre Lyon et Chambéry, porte d'entrée de la Savoie, est traité par KDRIVE comme une longue distance : le tarif est calculé à partir de la distance réelle et confirmé par l'équipe avant votre départ, dans les deux sens.",
      "Une réservation à l'avance est recommandée pour ce type de trajet, notamment en période hivernale (accès aux stations de ski savoyardes).",
    ],
    casUsageTitle: "Motifs de déplacement courants",
    casUsageItems: [
      "Trajet professionnel entre Lyon et Chambéry.",
      "Correspondance vers une station de ski savoyarde depuis Chambéry ou Lyon.",
      "Trajet vers une gare ou l'aéroport de Lyon depuis Chambéry.",
    ],
    frequentTrips: [
      { title: "Lyon → Chambéry", body: "Trajet direct, catégorie Essentiel ou Premium selon le niveau de prestation souhaité." },
      { title: "Chambéry → Aéroport Lyon-Saint Exupéry", body: "Liaison vers l'aéroport pour un vol au départ de Lyon.", href: "/transfert-aeroport" },
      { title: "Chambéry → Stations de ski", body: "Chambéry est un point de passage courant vers plusieurs stations savoyardes.", href: "/transfert-stations-ski-depuis-lyon" },
    ],
    faq: longDistanceFaq("Chambéry"),
    neighborLinksTitle: "Autres longues distances",
    neighborLinks: [
      { href: "/transfert-lyon-annecy", label: "Lyon – Annecy" },
      { href: "/transfert-lyon-geneve", label: "Lyon – Genève" },
      { href: "/transfert-stations-ski-depuis-lyon", label: "Transferts stations de ski" },
    ],
    pillarLinksTitle: "Poursuivre votre réservation",
    pillarLinks: longDistancePillarLinks,
    sources: ["Connaissance générale (Chambéry, porte d'entrée Savoie) — aucune donnée de distance/durée affichée."],
  },
  {
    slug: "transfert-lyon-geneve",
    family: "longue-distance",
    editorialStatus: "needsEnrichment",
    title: "Transfert Lyon – Genève | Chauffeur privé | KDRIVE",
    metaDescription: "Trajet longue distance entre Lyon et Genève avec chauffeur privé : tarif calculé sur la distance réelle, confirmé avant votre départ.",
    eyebrow: "Transfert Lyon – Genève",
    h1: "Chauffeur privé Lyon – Genève",
    breadcrumbParent: { label: "Longues distances", href: "/longues-distances" },
    heroImage: "/images/hero-longues-distances.jpg",
    heroLead: "Un trajet longue distance entre Lyon et Genève avec un chauffeur privé, dans les deux sens, sur réservation à l'avance.",
    presentationTitle: "Un trajet transfrontalier confirmé par l'équipe KDRIVE",
    presentationBody: [
      "Le trajet entre Lyon et Genève, en Suisse, est traité par KDRIVE comme une longue distance transfrontalière : le tarif est calculé à partir de la distance réelle et confirmé par l'équipe avant votre départ, dans les deux sens.",
      "Ce trajet implique un passage de frontière : vérifiez par vous-même, avant votre départ, les documents d'identité ou de voyage nécessaires selon votre situation (cette page ne constitue pas un conseil juridique ou administratif).",
    ],
    casUsageTitle: "Motifs de déplacement courants",
    casUsageItems: [
      "Trajet professionnel transfrontalier entre Lyon et Genève.",
      "Correspondance avec un vol au départ de Genève ou de Lyon.",
      "Trajet touristique vers Genève et sa région.",
    ],
    frequentTrips: [
      { title: "Lyon → Genève", body: "Trajet direct, catégorie Essentiel ou Premium selon le niveau de prestation souhaité." },
      { title: "Genève → Aéroport Lyon-Saint Exupéry", body: "Liaison vers l'aéroport de Lyon pour une correspondance.", href: "/transfert-aeroport" },
      { title: "Genève → Lyon centre", body: "Trajet retour vers le centre de Lyon." },
    ],
    faq: [
      { q: "Le tarif Lyon – Genève est-il fixe ?", a: "Non, le tarif est calculé à partir de la distance réelle de votre trajet et confirmé par KDRIVE avant votre départ ; aucun prix fixe n'est affiché à l'avance sur cette page." },
      { q: "Quels documents faut-il pour passer la frontière ?", a: "Vérifiez par vous-même les documents d'identité ou de voyage requis avant votre départ ; KDRIVE n'apporte pas de conseil juridique ou administratif sur ce point." },
      { q: "Faut-il réserver longtemps à l'avance pour ce trajet transfrontalier ?", a: "Une réservation anticipée est recommandée pour ce type de trajet, afin de permettre une confirmation dans de bonnes conditions." },
      { q: "Le trajet retour Genève → Lyon est-il possible ?", a: "Oui, cette page couvre les deux sens du trajet ; indiquez le sens souhaité lors de votre demande." },
    ],
    neighborLinksTitle: "Autres longues distances",
    neighborLinks: [
      { href: "/transfert-lyon-chambery", label: "Lyon – Chambéry" },
      { href: "/transfert-lyon-annecy", label: "Lyon – Annecy" },
    ],
    pillarLinksTitle: "Poursuivre votre réservation",
    pillarLinks: longDistancePillarLinks,
    sources: ["Trajet transfrontalier Lyon-Genève : aucune formalité précise affirmée, renvoi explicite à une vérification personnelle, conformément au brief (pas de conseil juridique)."],
  },
  {
    slug: "transfert-lyon-saint-etienne",
    family: "longue-distance",
    editorialStatus: "needsEnrichment",
    title: "Transfert Lyon – Saint-Étienne | Chauffeur privé | KDRIVE",
    metaDescription: "Trajet longue distance entre Lyon et Saint-Étienne avec chauffeur privé : tarif calculé sur la distance réelle, confirmé avant votre départ.",
    eyebrow: "Transfert Lyon – Saint-Étienne",
    h1: "Chauffeur privé Lyon – Saint-Étienne",
    breadcrumbParent: { label: "Longues distances", href: "/longues-distances" },
    heroImage: "/images/hero-longues-distances.jpg",
    heroLead: "Un trajet longue distance entre Lyon et Saint-Étienne avec un chauffeur privé, dans les deux sens, sur réservation à l'avance.",
    presentationTitle: "Une liaison longue distance confirmée par l'équipe KDRIVE",
    presentationBody: [
      "Le trajet entre Lyon et Saint-Étienne, sur l'axe sud-ouest via Givors, est traité par KDRIVE comme une longue distance : le tarif est calculé à partir de la distance réelle et confirmé par l'équipe avant votre départ, dans les deux sens.",
      "Une réservation à l'avance est recommandée pour ce type de trajet, afin de permettre la préparation du véhicule.",
    ],
    casUsageTitle: "Motifs de déplacement courants",
    casUsageItems: [
      "Trajet professionnel entre Lyon et Saint-Étienne.",
      "Correspondance avec un vol ou un train à Lyon depuis Saint-Étienne.",
    ],
    frequentTrips: [
      { title: "Lyon → Saint-Étienne", body: "Trajet direct, catégorie Essentiel ou Premium selon le niveau de prestation souhaité." },
      { title: "Saint-Étienne → Aéroport Lyon-Saint Exupéry", body: "Liaison vers l'aéroport pour un vol au départ de Lyon.", href: "/transfert-aeroport" },
      { title: "Saint-Étienne → Givors", body: "Givors se situe sur le trajet entre Lyon et Saint-Étienne.", href: "/vtc-givors" },
    ],
    faq: longDistanceFaq("Saint-Étienne"),
    neighborLinksTitle: "Autres longues distances",
    neighborLinks: [
      { href: "/transfert-lyon-valence", label: "Lyon – Valence" },
      { href: "/vtc-givors", label: "VTC Givors" },
    ],
    pillarLinksTitle: "Poursuivre votre réservation",
    pillarLinks: longDistancePillarLinks,
    sources: ["Connaissance générale (Saint-Étienne, axe via Givors) — aucune donnée de distance/durée affichée."],
  },
  {
    slug: "transfert-lyon-valence",
    family: "longue-distance",
    editorialStatus: "needsEnrichment",
    title: "Transfert Lyon – Valence | Chauffeur privé | KDRIVE",
    metaDescription: "Trajet longue distance entre Lyon et Valence avec chauffeur privé : tarif calculé sur la distance réelle, confirmé avant votre départ.",
    eyebrow: "Transfert Lyon – Valence",
    h1: "Chauffeur privé Lyon – Valence",
    breadcrumbParent: { label: "Longues distances", href: "/longues-distances" },
    heroImage: "/images/hero-longues-distances.jpg",
    heroLead: "Un trajet longue distance entre Lyon et Valence avec un chauffeur privé, dans les deux sens, sur réservation à l'avance.",
    presentationTitle: "Une liaison longue distance confirmée par l'équipe KDRIVE",
    presentationBody: [
      "Le trajet entre Lyon et Valence, sur l'axe sud de la vallée du Rhône, est traité par KDRIVE comme une longue distance : le tarif est calculé à partir de la distance réelle et confirmé par l'équipe avant votre départ, dans les deux sens.",
      "Réservez si possible à l'avance, afin que KDRIVE puisse organiser le véhicule et confirmer le tarif dans de bonnes conditions.",
    ],
    casUsageTitle: "Motifs de déplacement courants",
    casUsageItems: [
      "Trajet professionnel entre Lyon et Valence.",
      "Correspondance avec un vol ou un train à Lyon depuis Valence.",
    ],
    frequentTrips: [
      { title: "Lyon → Valence", body: "Trajet direct, catégorie Essentiel ou Premium selon le niveau de prestation souhaité." },
      { title: "Valence → Aéroport Lyon-Saint Exupéry", body: "Liaison vers l'aéroport pour un vol au départ de Lyon.", href: "/transfert-aeroport" },
      { title: "Valence → Lyon centre", body: "Trajet retour vers le centre de Lyon." },
    ],
    faq: longDistanceFaq("Valence"),
    neighborLinksTitle: "Autres longues distances",
    neighborLinks: [
      { href: "/transfert-lyon-saint-etienne", label: "Lyon – Saint-Étienne" },
      { href: "/transfert-lyon-clermont-ferrand", label: "Lyon – Clermont-Ferrand" },
    ],
    pillarLinksTitle: "Poursuivre votre réservation",
    pillarLinks: longDistancePillarLinks,
    sources: ["Connaissance générale (Valence, vallée du Rhône) — aucune donnée de distance/durée affichée."],
  },
  {
    slug: "transfert-lyon-clermont-ferrand",
    family: "longue-distance",
    editorialStatus: "needsEnrichment",
    title: "Transfert Lyon – Clermont-Ferrand | Chauffeur privé | KDRIVE",
    metaDescription: "Trajet longue distance entre Lyon et Clermont-Ferrand avec chauffeur privé : tarif calculé sur la distance réelle, confirmé avant votre départ.",
    eyebrow: "Transfert Lyon – Clermont-Ferrand",
    h1: "Chauffeur privé Lyon – Clermont-Ferrand",
    breadcrumbParent: { label: "Longues distances", href: "/longues-distances" },
    heroImage: "/images/hero-longues-distances.jpg",
    heroLead: "Un trajet longue distance entre Lyon et Clermont-Ferrand avec un chauffeur privé, dans les deux sens, sur réservation à l'avance.",
    presentationTitle: "Une liaison longue distance confirmée par l'équipe KDRIVE",
    presentationBody: [
      "Le trajet entre Lyon et Clermont-Ferrand, à l'ouest, est traité par KDRIVE comme une longue distance : le tarif est calculé à partir de la distance réelle et confirmé par l'équipe avant votre départ, dans les deux sens.",
      "Pour ce trajet comme pour les autres longues distances, anticipez votre demande afin de faciliter la confirmation du véhicule et du tarif.",
    ],
    casUsageTitle: "Motifs de déplacement courants",
    casUsageItems: [
      "Trajet professionnel entre Lyon et Clermont-Ferrand.",
      "Correspondance avec un vol ou un train à Lyon depuis Clermont-Ferrand.",
    ],
    frequentTrips: [
      { title: "Lyon → Clermont-Ferrand", body: "Trajet direct, catégorie Essentiel ou Premium selon le niveau de prestation souhaité." },
      { title: "Clermont-Ferrand → Aéroport Lyon-Saint Exupéry", body: "Liaison vers l'aéroport pour un vol au départ de Lyon.", href: "/transfert-aeroport" },
      { title: "Clermont-Ferrand → Lyon centre", body: "Trajet retour vers le centre de Lyon." },
    ],
    faq: longDistanceFaq("Clermont-Ferrand"),
    neighborLinksTitle: "Autres longues distances",
    neighborLinks: [
      { href: "/transfert-lyon-valence", label: "Lyon – Valence" },
      { href: "/transfert-lyon-dijon", label: "Lyon – Dijon" },
    ],
    pillarLinksTitle: "Poursuivre votre réservation",
    pillarLinks: longDistancePillarLinks,
    sources: ["Connaissance générale (Clermont-Ferrand, axe ouest) — aucune donnée de distance/durée affichée."],
  },
  {
    slug: "transfert-lyon-dijon",
    family: "longue-distance",
    editorialStatus: "needsEnrichment",
    title: "Transfert Lyon – Dijon | Chauffeur privé | KDRIVE",
    metaDescription: "Trajet longue distance entre Lyon et Dijon avec chauffeur privé : tarif calculé sur la distance réelle, confirmé avant votre départ.",
    eyebrow: "Transfert Lyon – Dijon",
    h1: "Chauffeur privé Lyon – Dijon",
    breadcrumbParent: { label: "Longues distances", href: "/longues-distances" },
    heroImage: "/images/hero-longues-distances.jpg",
    heroLead: "Un trajet longue distance entre Lyon et Dijon avec un chauffeur privé, dans les deux sens, sur réservation à l'avance.",
    presentationTitle: "Une liaison longue distance confirmée par l'équipe KDRIVE",
    presentationBody: [
      "Le trajet entre Lyon et Dijon, sur l'axe nord vers la Bourgogne, est traité par KDRIVE comme une longue distance : le tarif est calculé à partir de la distance réelle et confirmé par l'équipe avant votre départ, dans les deux sens.",
      "Une demande anticipée reste préférable sur cet axe, afin que KDRIVE puisse confirmer le véhicule et le tarif avant votre départ.",
    ],
    casUsageTitle: "Motifs de déplacement courants",
    casUsageItems: [
      "Trajet professionnel entre Lyon et Dijon.",
      "Correspondance avec un vol ou un train à Lyon depuis Dijon.",
    ],
    frequentTrips: [
      { title: "Lyon → Dijon", body: "Trajet direct, catégorie Essentiel ou Premium selon le niveau de prestation souhaité." },
      { title: "Dijon → Aéroport Lyon-Saint Exupéry", body: "Liaison vers l'aéroport pour un vol au départ de Lyon.", href: "/transfert-aeroport" },
      { title: "Dijon → Lyon centre", body: "Trajet retour vers le centre de Lyon." },
    ],
    faq: longDistanceFaq("Dijon"),
    neighborLinksTitle: "Autres longues distances",
    neighborLinks: [
      { href: "/transfert-lyon-paris", label: "Lyon – Paris" },
      { href: "/transfert-lyon-clermont-ferrand", label: "Lyon – Clermont-Ferrand" },
    ],
    pillarLinksTitle: "Poursuivre votre réservation",
    pillarLinks: longDistancePillarLinks,
    sources: ["Connaissance générale (Dijon, axe nord A6) — aucune donnée de distance/durée affichée."],
  },
  {
    slug: "transfert-lyon-paris",
    family: "longue-distance",
    editorialStatus: "needsEnrichment",
    title: "Transfert Lyon – Paris | Chauffeur privé | KDRIVE",
    metaDescription: "Trajet longue distance entre Lyon et Paris avec chauffeur privé : tarif calculé sur la distance réelle, confirmé avant votre départ.",
    eyebrow: "Transfert Lyon – Paris",
    h1: "Chauffeur privé Lyon – Paris",
    breadcrumbParent: { label: "Longues distances", href: "/longues-distances" },
    heroImage: "/images/hero-longues-distances.jpg",
    heroLead: "Un trajet longue distance entre Lyon et Paris avec un chauffeur privé, dans les deux sens, sur réservation à l'avance.",
    presentationTitle: "Une liaison longue distance confirmée par l'équipe KDRIVE",
    presentationBody: [
      "Le trajet entre Lyon et Paris, via l'autoroute A6, est traité par KDRIVE comme une longue distance : le tarif est calculé à partir de la distance réelle et confirmé par l'équipe avant votre départ, dans les deux sens.",
      "Une réservation à l'avance est recommandée pour ce trajet, le plus long proposé par KDRIVE au départ de Lyon ; la faisabilité (relais éventuel, horaires) est confirmée directement avec l'équipe.",
    ],
    casUsageTitle: "Motifs de déplacement courants",
    casUsageItems: [
      "Trajet professionnel entre Lyon et Paris.",
      "Correspondance avec un vol ou un train à Lyon ou à Paris.",
      "Trajet privé pour un événement à Paris.",
    ],
    frequentTrips: [
      { title: "Lyon → Paris", body: "Trajet direct, catégorie Premium recommandée pour ce trajet long." },
      { title: "Paris → Aéroport Lyon-Saint Exupéry", body: "Liaison retour vers l'aéroport de Lyon.", href: "/transfert-aeroport" },
      { title: "Paris → Lyon centre", body: "Trajet retour vers le centre de Lyon." },
    ],
    faq: [
      { q: "Le tarif Lyon – Paris est-il fixe ?", a: "Non, le tarif est calculé à partir de la distance réelle de votre trajet et confirmé par KDRIVE avant votre départ ; aucun prix fixe n'est affiché à l'avance sur cette page." },
      { q: "Ce trajet est-il réalisable en une fois ?", a: "La faisabilité et l'organisation du trajet (éventuel relais, horaires) sont confirmées directement avec l'équipe KDRIVE avant votre départ." },
      { q: "Faut-il réserver longtemps à l'avance pour Lyon – Paris ?", a: "Oui, une réservation anticipée est fortement recommandée pour ce trajet, le plus long proposé par KDRIVE au départ de Lyon." },
      { q: "Le trajet retour Paris → Lyon est-il possible ?", a: "Oui, cette page couvre les deux sens du trajet ; indiquez le sens souhaité lors de votre demande." },
    ],
    neighborLinksTitle: "Autres longues distances",
    neighborLinks: [
      { href: "/transfert-lyon-dijon", label: "Lyon – Dijon" },
      { href: "/longues-distances", label: "Toutes les longues distances" },
    ],
    pillarLinksTitle: "Poursuivre votre réservation",
    pillarLinks: longDistancePillarLinks,
    sources: ["Connaissance générale (Lyon-Paris, axe A6) — aucune donnée de distance/durée affichée ; faisabilité explicitement renvoyée à une confirmation directe, cf. brief (aucune promesse de transporteur longue distance spécialisé)."],
  },
];
