import type { ServicePageContent } from "./service-page-template";

export const servicePages: ServicePageContent[] = [
  {
    key: "aeroport",
    navLabel: "Transfert aéroport",
    eyebrow: "Transfert aéroport",
    title: "Lyon-Saint Exupéry, sans stress.",
    lead: "Une prise en charge préparée à l’avance pour votre arrivée ou votre départ à l’aéroport Lyon-Saint Exupéry.",
    ctaLabel: "Réserver mon transfert",
    heroImage: "/images/airport-transfer.jpg",
    presentationEyebrow: "La prestation",
    presentationTitle: "Une arrivée aussi sereine que le vol",
    presentationBody: "Vous pouvez renseigner votre numéro de vol lors de la réservation. Cette information permet à l’équipe KDRIVE de mieux préparer votre prise en charge et de vous recontacter si une adaptation est nécessaire.",
    benefits: [
      { title: "Numéro de vol", body: "Renseignez-le lors de la réservation pour faciliter la préparation de votre trajet." },
      { title: "Bagages", body: "Un véhicule adapté au nombre de passagers et de bagages annoncés." },
      { title: "Tarif annoncé à l’avance", body: "Un prix calculé avant confirmation, sans surprise à l’arrivée." },
    ],
    visualImage: "/images/service-transferts.jpg",
    steps: [
      { title: "Indiquez votre trajet", body: "Adresse ou aéroport de départ, destination, date et heure." },
      { title: "Confirmez votre demande", body: "Un numéro de téléphone suffit pour envoyer votre demande." },
      { title: "Votre chauffeur vous attend", body: "KDRIVE confirme rapidement la disponibilité et le tarif." },
    ],
    usefulInfo: [
      "Aéroport Lyon-Saint Exupéry (LYS)",
      "En cas de changement ou de retard, contactez KDRIVE dès que possible afin de confirmer ou d’ajuster l’heure de prise en charge",
      "Trajet aller simple ou aller-retour",
    ],
    reassuranceTitle: "Une prise en charge préparée avec attention",
    reassuranceBody: "Vol, bagages, réservation anticipée : KDRIVE cadre chaque transfert aéroport par un échange direct avec l’équipe, avant confirmation de l’heure de prise en charge.",
    ctaFinalTitle: "Votre transfert aéroport, en quelques secondes",
    relatedLinksTitle: "Poursuivre votre réservation",
    relatedLinks: [
      { href: "/vehicules", label: "Voir les véhicules disponibles" },
      { href: "/tarifs", label: "Consulter la grille tarifaire" },
      { href: "/longues-distances", label: "Trajet au-delà de Lyon" },
    ],
  },
  {
    key: "gare",
    navLabel: "Transfert gare",
    eyebrow: "Transfert gare",
    title: "Votre train, votre chauffeur, à l’heure.",
    lead: "KDRIVE assure des prises en charge sur réservation aux principales gares de Lyon, notamment Part-Dieu et Perrache.",
    ctaLabel: "Réserver mon transfert",
    heroImage: "/images/service-transferts.jpg",
    presentationEyebrow: "La prestation",
    presentationTitle: "Un départ ou une arrivée sans course contre la montre",
    presentationBody: "Indiquez votre gare, l’heure de votre train et votre adresse de destination : votre chauffeur organise la prise en charge avec la marge nécessaire pour ne jamais manquer votre train.",
    benefits: [
      { title: "Gares de Lyon couvertes", body: "Part-Dieu et Perrache, avec point de rendez-vous précis." },
      { title: "Marge de sécurité", body: "Un départ calculé pour arriver avec de l’avance." },
      { title: "Tarif annoncé à l’avance", body: "Un prix calculé avant confirmation, sans surprise à l’arrivée." },
    ],
    visualImage: "/images/hero-lyon.jpg",
    steps: [
      { title: "Indiquez votre trajet", body: "Gare de départ ou d’arrivée, destination, date et heure." },
      { title: "Confirmez votre demande", body: "Un numéro de téléphone suffit pour envoyer votre demande." },
      { title: "Votre chauffeur vous attend", body: "KDRIVE confirme rapidement la disponibilité et le tarif." },
    ],
    usefulInfo: [
      "Gare de Lyon Part-Dieu",
      "Gare de Lyon Perrache",
      "Trajet aller simple ou aller-retour, bagages compris dans la demande",
    ],
    reassuranceTitle: "Une prise en charge organisée avec vous",
    reassuranceBody: "Arrivée ou départ en train, bagages, adresse de destination : chaque transfert gare est confirmé par un échange direct avec l’équipe KDRIVE avant votre trajet.",
    ctaFinalTitle: "Votre transfert gare, en quelques secondes",
    relatedLinksTitle: "Poursuivre votre réservation",
    relatedLinks: [
      { href: "/transfert-aeroport", label: "Transfert aéroport" },
      { href: "/chauffeur-entreprise", label: "Déplacements professionnels" },
      { href: "/vehicules", label: "Voir les véhicules disponibles" },
      { href: "/tarifs", label: "Consulter la grille tarifaire" },
    ],
  },
  {
    key: "entreprise",
    navLabel: "Chauffeur entreprise",
    eyebrow: "Chauffeur privé entreprise",
    title: "Des déplacements professionnels sans friction.",
    lead: "Ponctualité, discrétion et disponibilité pour vos rendez-vous, équipes et visiteurs.",
    ctaLabel: "Demander un devis",
    heroImage: "/images/service-affaires.jpg",
    presentationEyebrow: "La prestation",
    presentationTitle: "Un chauffeur pour vos enjeux professionnels",
    presentationBody: "Rendez-vous clients, accueil de visiteurs, trajets d’équipe : KDRIVE accompagne les entreprises lyonnaises qui veulent confier leurs déplacements à un service fiable, sans les contraintes d’un parc de véhicules.",
    benefits: [
      { title: "Discrétion professionnelle", body: "Un service sobre, adapté aux échanges confidentiels." },
      { title: "Ponctualité", body: "Un chauffeur en avance sur le point de rendez-vous convenu." },
      { title: "Facturation simplifiée", body: "Une seule interlocutrice pour l’ensemble de vos trajets." },
    ],
    visualImage: "/images/corporate.jpg",
    steps: [
      { title: "Décrivez votre besoin", body: "Trajet ponctuel, récurrent ou mise à disposition d’équipe." },
      { title: "Échangez avec KDRIVE", body: "Un contact direct pour cadrer le déroulé et le tarif." },
      { title: "Votre chauffeur intervient", body: "Selon le calendrier et les points de rendez-vous convenus." },
    ],
    usefulInfo: [
      "Trajets ponctuels ou récurrents",
      "Accueil de visiteurs et délégations",
      "Interlocuteur dédié pour les entreprises",
    ],
    reassuranceTitle: "Une équipe locale, un service pensé pour durer",
    reassuranceBody: "KDRIVE est une entreprise locale à Lyon. Chaque demande professionnelle est traitée par un échange direct avec l’équipe.",
    ctaFinalTitle: "Parlons de vos déplacements professionnels",
    relatedLinksTitle: "Services complémentaires",
    relatedLinks: [
      { href: "/mise-a-disposition", label: "Mise à disposition" },
      { href: "/transfert-aeroport", label: "Transfert aéroport" },
      { href: "/transfert-gare", label: "Transfert gare" },
      { href: "/vehicules", label: "Voir les véhicules disponibles" },
    ],
  },
  {
    key: "disposition",
    navLabel: "Mise à disposition",
    eyebrow: "Mise à disposition",
    title: "Un chauffeur dédié, à votre rythme.",
    lead: "Pour une soirée, un événement ou une journée complète, votre chauffeur reste à votre disposition.",
    ctaLabel: "Demander un devis",
    heroImage: "/images/service-vip.jpg",
    presentationEyebrow: "La prestation",
    presentationTitle: "Le temps d’un événement, d’une soirée ou d’une journée",
    presentationBody: "Plutôt qu’un trajet unique, votre chauffeur reste disponible sur la durée convenue : plusieurs arrêts, temps d’attente, changements de dernière minute.",
    benefits: [
      { title: "Disponibilité continue", body: "Un chauffeur qui reste à votre écoute pendant toute la mise à disposition." },
      { title: "Plusieurs arrêts possibles", body: "Un déroulé adapté à votre programme, pas l’inverse." },
      { title: "Tarif annoncé à l’avance", body: "Une durée et un prix définis avant confirmation." },
    ],
    visualImage: "/images/service-disposition.jpg",
    steps: [
      { title: "Décrivez votre programme", body: "Durée souhaitée, étapes principales, date et heure de début." },
      { title: "Confirmez votre demande", body: "Un numéro de téléphone suffit pour envoyer votre demande." },
      { title: "Votre chauffeur vous accompagne", body: "KDRIVE confirme rapidement la disponibilité et le tarif." },
    ],
    usefulInfo: [
      "Mise à disposition à l’heure ou à la journée",
      "Adaptée aux événements privés ou professionnels",
      "Programme ajustable en cours de prestation",
    ],
    reassuranceTitle: "Une équipe locale, un service pensé pour durer",
    reassuranceBody: "KDRIVE est une entreprise locale à Lyon. Chaque demande est confirmée par un échange direct, sans réservation automatique non vérifiée.",
    ctaFinalTitle: "Votre mise à disposition, en quelques secondes",
    relatedLinksTitle: "Services complémentaires",
    relatedLinks: [
      { href: "/chauffeur-entreprise", label: "Déplacements professionnels" },
      { href: "/longues-distances", label: "Trajet longue distance" },
      { href: "/vehicules", label: "Voir les véhicules disponibles" },
    ],
  },
  {
    key: "longues-distances",
    navLabel: "Longues distances",
    eyebrow: "Longues distances",
    title: "Au-delà de Lyon, sans changer de chauffeur.",
    lead: "Pour les trajets longue distance, un devis est établi avant toute confirmation.",
    ctaLabel: "Demander un devis",
    heroImage: "/images/hero-longues-distances.jpg",
    presentationEyebrow: "La prestation",
    presentationTitle: "Un trajet long, préparé avec attention",
    presentationBody: "Au-delà d’un certain rayon autour de Lyon, chaque trajet longue distance fait l’objet d’un devis personnalisé plutôt que d’un tarif calculé automatiquement, pour tenir compte de la durée et des conditions réelles du trajet.",
    benefits: [
      { title: "Devis personnalisé", body: "Un tarif établi selon la distance réelle et les conditions du trajet." },
      { title: "Un seul chauffeur", body: "Pas de changement de véhicule en cours de route." },
      { title: "Échange direct", body: "Votre demande est confirmée par KDRIVE avant tout engagement." },
    ],
    visualImage: "/images/about-lyon.jpg",
    steps: [
      { title: "Indiquez votre trajet", body: "Adresse de départ, destination, date et heure souhaitées." },
      { title: "Recevez votre devis", body: "KDRIVE revient vers vous avec un tarif adapté au trajet." },
      { title: "Confirmez votre départ", body: "Une fois le devis validé, votre chauffeur est confirmé." },
    ],
    usefulInfo: [
      "Devis établi avant toute confirmation",
      "Trajets hors zone Lyon et agglomération",
      "Aller simple ou aller-retour",
    ],
    reassuranceTitle: "Une équipe locale, un service pensé pour durer",
    reassuranceBody: "KDRIVE est une entreprise locale à Lyon. Chaque trajet longue distance est cadré par un échange direct avant confirmation.",
    ctaFinalTitle: "Demandez votre devis longue distance",
    relatedLinksTitle: "Services complémentaires",
    relatedLinks: [
      { href: "/vehicules", label: "Voir les véhicules disponibles" },
      { href: "/tarifs", label: "Consulter la grille tarifaire" },
      { href: "/mise-a-disposition", label: "Mise à disposition" },
    ],
  },
];
