import type { LocalPageContent } from "./local-page-template";

/**
 * Transferts vers les principales stations de ski depuis Lyon. Noms de
 * communes/vallées vérifiés par recherche (Les 3 Vallées, Paradiski, Espace
 * Killy — cf. rapport de sprint, sources consultées le 2026-09-10).
 * Aucun tarif, équipement hivernal garanti, transport de skis confirmé ou
 * condition de circulation n'est affirmé sans réserve : chaque page renvoie
 * à une confirmation directe avec KDRIVE.
 */

const skiCasUsage = [
  "Trajet depuis Lyon, une gare (Part-Dieu, gare TGV Saint-Exupéry) ou l'aéroport vers la station.",
  "Transport de bagages et de matériel de ski, à signaler lors de la réservation.",
  "Trajet retour en fin de séjour, dans les mêmes conditions.",
];

function skiFaq(station: string): { q: string; a: string }[] {
  return [
    { q: `Le tarif Lyon – ${station} est-il fixe ?`, a: "Non, le tarif est calculé à partir de la distance réelle de votre trajet et confirmé par KDRIVE avant votre départ ; aucun prix fixe n'est affiché à l'avance sur cette page." },
    { q: "KDRIVE transporte-t-il le matériel de ski ?", a: "L'espace disponible pour le matériel de ski dépend du véhicule et du nombre de passagers : signalez-le lors de la réservation, KDRIVE confirme la faisabilité avant votre départ." },
    { q: "Les conditions hivernales sont-elles garanties ?", a: "Non, aucune condition de circulation hivernale n'est garantie à l'avance ; le trajet reste soumis aux conditions réelles du jour." },
    { q: "Faut-il réserver longtemps à l'avance en période de vacances scolaires ?", a: "Oui, une réservation anticipée est fortement recommandée en haute saison, lorsque la demande est la plus forte." },
  ];
}

const skiPillarLinks: LocalPageContent["pillarLinks"] = [
  { href: "/transfert-stations-ski-depuis-lyon", label: "Toutes les stations de ski" },
  { href: "/vehicules", label: "Nos véhicules" },
  { href: "/tarifs", label: "Grille tarifaire" },
  { href: "/reserver", label: "Réserver un trajet" },
];

export const skiPages: LocalPageContent[] = [
  {
    slug: "transfert-lyon-courchevel",
    family: "ski-station",
    editorialStatus: "needsEnrichment",
    title: "Transfert Lyon – Courchevel | Chauffeur privé | KDRIVE",
    metaDescription: "Transfert avec chauffeur privé entre Lyon et Courchevel (Les 3 Vallées) : tarif calculé sur la distance réelle, confirmé avant votre départ.",
    eyebrow: "Transfert ski",
    h1: "Transfert Lyon – Courchevel",
    breadcrumbParent: { label: "Stations de ski", href: "/transfert-stations-ski-depuis-lyon" },
    heroImage: "/images/hero-longues-distances.jpg",
    heroLead: "Un transfert avec chauffeur privé entre Lyon et Courchevel, sur réservation à l'avance.",
    presentationTitle: "Courchevel, station du domaine Les 3 Vallées",
    presentationBody: [
      "Courchevel, commune de Saint-Bon-Tarentaise en Savoie, fait partie du domaine skiable des 3 Vallées. La station se répartit en plusieurs altitudes (Courchevel 1850, 1650, 1550, Le Praz) : précisez le secteur exact de votre hébergement lors de la réservation.",
      "Comme pour toute liaison vers les 3 Vallées, le tarif de ce trajet longue distance est calculé sur la distance réelle et confirmé par KDRIVE avant votre départ.",
    ],
    quartiersTitle: "Secteurs de Courchevel",
    quartiers: [
      { title: "Courchevel 1850", body: "Altitude la plus élevée de la station, secteur central." },
      { title: "Courchevel 1650 / 1550", body: "Secteurs intermédiaires, à préciser selon votre hébergement." },
      { title: "Le Praz", body: "Village en contrebas de la station, également desservi." },
    ],
    casUsageTitle: "Motifs de déplacement courants",
    casUsageItems: skiCasUsage,
    frequentTrips: [
      { title: "Lyon → Courchevel", body: "Trajet direct depuis Lyon." },
      { title: "Aéroport Lyon-Saint Exupéry → Courchevel", body: "Transfert depuis l'aéroport en début de séjour.", href: "/transfert-aeroport" },
      { title: "Courchevel → Méribel", body: "Les deux stations font partie du même domaine skiable.", href: "/transfert-lyon-meribel" },
    ],
    faq: skiFaq("Courchevel"),
    neighborLinksTitle: "Autres stations des 3 Vallées",
    neighborLinks: [
      { href: "/transfert-lyon-meribel", label: "Lyon – Méribel" },
      { href: "/transfert-lyon-val-thorens", label: "Lyon – Val Thorens" },
      { href: "/transfert-lyon-les-menuires", label: "Lyon – Les Menuires" },
    ],
    pillarLinksTitle: "Poursuivre votre réservation",
    pillarLinks: skiPillarLinks,
    sources: ["Courchevel / Saint-Bon-Tarentaise / Les 3 Vallées vérifié par recherche web le 2026-09-10."],
  },
  {
    slug: "transfert-lyon-meribel",
    family: "ski-station",
    editorialStatus: "needsEnrichment",
    title: "Transfert Lyon – Méribel | Chauffeur privé | KDRIVE",
    metaDescription: "Transfert avec chauffeur privé entre Lyon et Méribel (Les 3 Vallées) : tarif calculé sur la distance réelle, confirmé avant votre départ.",
    eyebrow: "Transfert ski",
    h1: "Transfert Lyon – Méribel",
    breadcrumbParent: { label: "Stations de ski", href: "/transfert-stations-ski-depuis-lyon" },
    heroImage: "/images/hero-longues-distances.jpg",
    heroLead: "Un transfert avec chauffeur privé entre Lyon et Méribel, sur réservation à l'avance.",
    presentationTitle: "Méribel, cœur du domaine Les 3 Vallées",
    presentationBody: [
      "Méribel, sur la commune des Allues en Savoie, occupe une position centrale dans le domaine skiable des 3 Vallées, entre Courchevel et Val Thorens.",
      "Le secteur de Méribel comptant plusieurs sites d'altitude, précisez celui de votre hébergement lors de la réservation ; le tarif du trajet est ensuite calculé sur la distance réelle et confirmé avant votre départ.",
    ],
    quartiersTitle: "Repères à Méribel",
    quartiers: [
      { title: "Méribel-Village", body: "Secteur d'accès à la station." },
      { title: "Méribel-Centre", body: "Cœur de la station, au pied des pistes." },
      { title: "Méribel-Mottaret", body: "Secteur en altitude, à préciser selon votre hébergement." },
    ],
    casUsageTitle: "Motifs de déplacement courants",
    casUsageItems: skiCasUsage,
    frequentTrips: [
      { title: "Lyon → Méribel", body: "Trajet direct depuis Lyon." },
      { title: "Aéroport Lyon-Saint Exupéry → Méribel", body: "Transfert depuis l'aéroport en début de séjour.", href: "/transfert-aeroport" },
      { title: "Méribel → Courchevel", body: "Les deux stations font partie du même domaine skiable.", href: "/transfert-lyon-courchevel" },
    ],
    faq: skiFaq("Méribel"),
    neighborLinksTitle: "Autres stations des 3 Vallées",
    neighborLinks: [
      { href: "/transfert-lyon-courchevel", label: "Lyon – Courchevel" },
      { href: "/transfert-lyon-val-thorens", label: "Lyon – Val Thorens" },
      { href: "/transfert-lyon-les-menuires", label: "Lyon – Les Menuires" },
    ],
    pillarLinksTitle: "Poursuivre votre réservation",
    pillarLinks: skiPillarLinks,
    sources: ["Méribel / Les Allues / Les 3 Vallées vérifié par recherche web le 2026-09-10."],
  },
  {
    slug: "transfert-lyon-val-thorens",
    family: "ski-station",
    editorialStatus: "needsEnrichment",
    title: "Transfert Lyon – Val Thorens | Chauffeur privé | KDRIVE",
    metaDescription: "Transfert avec chauffeur privé entre Lyon et Val Thorens (Les 3 Vallées) : tarif calculé sur la distance réelle, confirmé avant votre départ.",
    eyebrow: "Transfert ski",
    h1: "Transfert Lyon – Val Thorens",
    breadcrumbParent: { label: "Stations de ski", href: "/transfert-stations-ski-depuis-lyon" },
    heroImage: "/images/hero-longues-distances.jpg",
    heroLead: "Un transfert avec chauffeur privé entre Lyon et Val Thorens, sur réservation à l'avance.",
    presentationTitle: "Val Thorens, la plus haute station d'Europe",
    presentationBody: [
      "Val Thorens, sur la commune de Saint-Martin-de-Belleville en Savoie, est la station la plus haute d'Europe (environ 2300 mètres) et fait partie du domaine skiable des 3 Vallées.",
      "KDRIVE organise ce transfert comme un trajet longue distance en altitude : les conditions d'accès peuvent varier fortement selon la météo, sans garantie fournie à l'avance.",
    ],
    quartiersTitle: "Repères à Val Thorens",
    quartiers: [
      { title: "Centre station", body: "Cœur de Val Thorens, au pied des pistes, en haute altitude." },
    ],
    casUsageTitle: "Motifs de déplacement courants",
    casUsageItems: skiCasUsage,
    frequentTrips: [
      { title: "Lyon → Val Thorens", body: "Trajet direct depuis Lyon, vers la station la plus haute d'Europe." },
      { title: "Aéroport Lyon-Saint Exupéry → Val Thorens", body: "Transfert depuis l'aéroport en début de séjour.", href: "/transfert-aeroport" },
      { title: "Val Thorens → Les Menuires", body: "Les deux stations partagent la même vallée (Belleville).", href: "/transfert-lyon-les-menuires" },
    ],
    faq: skiFaq("Val Thorens"),
    neighborLinksTitle: "Autres stations des 3 Vallées",
    neighborLinks: [
      { href: "/transfert-lyon-les-menuires", label: "Lyon – Les Menuires" },
      { href: "/transfert-lyon-meribel", label: "Lyon – Méribel" },
      { href: "/transfert-lyon-courchevel", label: "Lyon – Courchevel" },
    ],
    pillarLinksTitle: "Poursuivre votre réservation",
    pillarLinks: skiPillarLinks,
    sources: ["Val Thorens / Saint-Martin-de-Belleville, altitude ~2300 m, plus haute station d'Europe : vérifié par recherche web le 2026-09-10."],
  },
  {
    slug: "transfert-lyon-les-menuires",
    family: "ski-station",
    editorialStatus: "needsEnrichment",
    title: "Transfert Lyon – Les Menuires | Chauffeur privé | KDRIVE",
    metaDescription: "Transfert avec chauffeur privé entre Lyon et Les Menuires (Les 3 Vallées) : tarif calculé sur la distance réelle, confirmé avant votre départ.",
    eyebrow: "Transfert ski",
    h1: "Transfert Lyon – Les Menuires",
    breadcrumbParent: { label: "Stations de ski", href: "/transfert-stations-ski-depuis-lyon" },
    heroImage: "/images/hero-longues-distances.jpg",
    heroLead: "Un transfert avec chauffeur privé entre Lyon et Les Menuires, sur réservation à l'avance.",
    presentationTitle: "Les Menuires, dans la vallée des Belleville",
    presentationBody: [
      "Les Menuires, sur la commune de Saint-Martin-de-Belleville en Savoie, se situe dans la vallée des Belleville et fait partie du domaine skiable des 3 Vallées, aux côtés de Val Thorens.",
      "Ce trajet vers la vallée des Belleville est traité comme une longue distance : le tarif dépend de la distance réelle parcourue et vous est confirmé avant le départ.",
    ],
    quartiersTitle: "Repères aux Menuires",
    quartiers: [
      { title: "La Croisette", body: "Secteur central de la station des Menuires." },
      { title: "Reberty / Les Bruyères", body: "Secteurs périphériques, à préciser selon votre hébergement." },
    ],
    casUsageTitle: "Motifs de déplacement courants",
    casUsageItems: skiCasUsage,
    frequentTrips: [
      { title: "Lyon → Les Menuires", body: "Trajet direct depuis Lyon." },
      { title: "Aéroport Lyon-Saint Exupéry → Les Menuires", body: "Transfert depuis l'aéroport en début de séjour.", href: "/transfert-aeroport" },
      { title: "Les Menuires → Val Thorens", body: "Les deux stations partagent la même vallée.", href: "/transfert-lyon-val-thorens" },
    ],
    faq: skiFaq("Les Menuires"),
    neighborLinksTitle: "Autres stations des 3 Vallées",
    neighborLinks: [
      { href: "/transfert-lyon-val-thorens", label: "Lyon – Val Thorens" },
      { href: "/transfert-lyon-meribel", label: "Lyon – Méribel" },
    ],
    pillarLinksTitle: "Poursuivre votre réservation",
    pillarLinks: skiPillarLinks,
    sources: ["Les Menuires / Saint-Martin-de-Belleville / vallée des Belleville : vérifié par recherche web le 2026-09-10 (source Wikipédia)."],
  },
  {
    slug: "transfert-lyon-les-arcs",
    family: "ski-station",
    editorialStatus: "needsEnrichment",
    title: "Transfert Lyon – Les Arcs | Chauffeur privé | KDRIVE",
    metaDescription: "Transfert avec chauffeur privé entre Lyon et Les Arcs (Paradiski) : tarif calculé sur la distance réelle, confirmé avant votre départ.",
    eyebrow: "Transfert ski",
    h1: "Transfert Lyon – Les Arcs",
    breadcrumbParent: { label: "Stations de ski", href: "/transfert-stations-ski-depuis-lyon" },
    heroImage: "/images/hero-longues-distances.jpg",
    heroLead: "Un transfert avec chauffeur privé entre Lyon et Les Arcs, sur réservation à l'avance.",
    presentationTitle: "Les Arcs, sur la commune de Bourg-Saint-Maurice",
    presentationBody: [
      "Les Arcs, rattachée à la commune de Bourg-Saint-Maurice en Savoie, fait partie du domaine skiable Paradiski, relié à La Plagne par téléphérique. La station se répartit en plusieurs sites (Arc 1600, 1800, 1950, 2000).",
      "KDRIVE organise ce transfert comme un trajet longue distance : précisez le site exact de votre hébergement lors de la réservation.",
    ],
    quartiersTitle: "Sites des Arcs",
    quartiers: [
      { title: "Arc 1600 / 1800", body: "Sites historiques de la station, en contrebas." },
      { title: "Arc 1950 / 2000", body: "Sites plus récents, en altitude." },
    ],
    casUsageTitle: "Motifs de déplacement courants",
    casUsageItems: skiCasUsage,
    frequentTrips: [
      { title: "Lyon → Les Arcs", body: "Trajet direct depuis Lyon." },
      { title: "Aéroport Lyon-Saint Exupéry → Les Arcs", body: "Transfert depuis l'aéroport en début de séjour.", href: "/transfert-aeroport" },
      { title: "Les Arcs → La Plagne", body: "Les deux stations forment le domaine Paradiski.", href: "/transfert-lyon-la-plagne" },
    ],
    faq: skiFaq("Les Arcs"),
    neighborLinksTitle: "Autres stations du domaine Paradiski",
    neighborLinks: [
      { href: "/transfert-lyon-la-plagne", label: "Lyon – La Plagne" },
      { href: "/transfert-lyon-tignes", label: "Lyon – Tignes" },
    ],
    pillarLinksTitle: "Poursuivre votre réservation",
    pillarLinks: skiPillarLinks,
    sources: ["Les Arcs / Bourg-Saint-Maurice / domaine Paradiski : vérifié par recherche web le 2026-09-10."],
  },
  {
    slug: "transfert-lyon-la-plagne",
    family: "ski-station",
    editorialStatus: "needsEnrichment",
    title: "Transfert Lyon – La Plagne | Chauffeur privé | KDRIVE",
    metaDescription: "Transfert avec chauffeur privé entre Lyon et La Plagne (Paradiski) : tarif calculé sur la distance réelle, confirmé avant votre départ.",
    eyebrow: "Transfert ski",
    h1: "Transfert Lyon – La Plagne",
    breadcrumbParent: { label: "Stations de ski", href: "/transfert-stations-ski-depuis-lyon" },
    heroImage: "/images/hero-longues-distances.jpg",
    heroLead: "Un transfert avec chauffeur privé entre Lyon et La Plagne, sur réservation à l'avance.",
    presentationTitle: "La Plagne, plusieurs villages d'un même domaine",
    presentationBody: [
      "La Plagne, commune de La Plagne Tarentaise en Savoie, regroupe plusieurs villages d'altitude (Plagne Centre, Plagne 1800, Belle Plagne, Montchavin, etc.) au sein du domaine skiable Paradiski, relié aux Arcs.",
      "La station comptant de nombreux villages distincts, indiquez celui de votre hébergement lors de la réservation ; KDRIVE traite ce trajet comme une longue distance classique.",
    ],
    quartiersTitle: "Villages de La Plagne",
    quartiers: [
      { title: "Plagne Centre / 1800", body: "Secteurs centraux de la station." },
      { title: "Belle Plagne", body: "Village d'altitude du domaine." },
      { title: "Montchavin / Les Coches", body: "Villages plus bas, également reliés au domaine." },
    ],
    casUsageTitle: "Motifs de déplacement courants",
    casUsageItems: skiCasUsage,
    frequentTrips: [
      { title: "Lyon → La Plagne", body: "Trajet direct depuis Lyon." },
      { title: "Aéroport Lyon-Saint Exupéry → La Plagne", body: "Transfert depuis l'aéroport en début de séjour.", href: "/transfert-aeroport" },
      { title: "La Plagne → Les Arcs", body: "Les deux stations forment le domaine Paradiski.", href: "/transfert-lyon-les-arcs" },
    ],
    faq: skiFaq("La Plagne"),
    neighborLinksTitle: "Autres stations du domaine Paradiski",
    neighborLinks: [
      { href: "/transfert-lyon-les-arcs", label: "Lyon – Les Arcs" },
      { href: "/transfert-lyon-tignes", label: "Lyon – Tignes" },
    ],
    pillarLinksTitle: "Poursuivre votre réservation",
    pillarLinks: skiPillarLinks,
    sources: ["La Plagne / La Plagne Tarentaise / domaine Paradiski : vérifié par recherche web le 2026-09-10."],
  },
  {
    slug: "transfert-lyon-tignes",
    family: "ski-station",
    editorialStatus: "needsEnrichment",
    title: "Transfert Lyon – Tignes | Chauffeur privé | KDRIVE",
    metaDescription: "Transfert avec chauffeur privé entre Lyon et Tignes (Espace Killy) : tarif calculé sur la distance réelle, confirmé avant votre départ.",
    eyebrow: "Transfert ski",
    h1: "Transfert Lyon – Tignes",
    breadcrumbParent: { label: "Stations de ski", href: "/transfert-stations-ski-depuis-lyon" },
    heroImage: "/images/hero-longues-distances.jpg",
    heroLead: "Un transfert avec chauffeur privé entre Lyon et Tignes, sur réservation à l'avance.",
    presentationTitle: "Tignes, au sein du domaine Espace Killy",
    presentationBody: [
      "Tignes, en Savoie, forme avec Val d'Isère le domaine skiable Espace Killy. La station comprend plusieurs villages (Tignes-le-Lac, Val Claret, Tignes 1800).",
      "KDRIVE organise ce transfert comme un trajet longue distance : précisez le village exact de votre hébergement lors de la réservation.",
    ],
    quartiersTitle: "Villages de Tignes",
    quartiers: [
      { title: "Tignes-le-Lac", body: "Secteur central de la station, au bord du lac." },
      { title: "Val Claret", body: "Secteur en altitude, au pied des pistes." },
    ],
    casUsageTitle: "Motifs de déplacement courants",
    casUsageItems: skiCasUsage,
    frequentTrips: [
      { title: "Lyon → Tignes", body: "Trajet direct depuis Lyon." },
      { title: "Aéroport Lyon-Saint Exupéry → Tignes", body: "Transfert depuis l'aéroport en début de séjour.", href: "/transfert-aeroport" },
      { title: "Tignes → Val d'Isère", body: "Les deux stations forment le domaine Espace Killy.", href: "/transfert-lyon-val-disere" },
    ],
    faq: skiFaq("Tignes"),
    neighborLinksTitle: "Autres stations de l'Espace Killy",
    neighborLinks: [
      { href: "/transfert-lyon-val-disere", label: "Lyon – Val d'Isère" },
      { href: "/transfert-lyon-la-plagne", label: "Lyon – La Plagne" },
    ],
    pillarLinksTitle: "Poursuivre votre réservation",
    pillarLinks: skiPillarLinks,
    sources: ["Tignes / domaine Espace Killy (avec Val d'Isère) : vérifié par recherche web le 2026-09-10."],
  },
  {
    slug: "transfert-lyon-val-disere",
    family: "ski-station",
    editorialStatus: "needsEnrichment",
    title: "Transfert Lyon – Val d'Isère | Chauffeur privé | KDRIVE",
    metaDescription: "Transfert avec chauffeur privé entre Lyon et Val d'Isère (Espace Killy) : tarif calculé sur la distance réelle, confirmé avant votre départ.",
    eyebrow: "Transfert ski",
    h1: "Transfert Lyon – Val d'Isère",
    breadcrumbParent: { label: "Stations de ski", href: "/transfert-stations-ski-depuis-lyon" },
    heroImage: "/images/hero-longues-distances.jpg",
    heroLead: "Un transfert avec chauffeur privé entre Lyon et Val d'Isère, sur réservation à l'avance.",
    presentationTitle: "Val d'Isère, au sein du domaine Espace Killy",
    presentationBody: [
      "Val d'Isère, en Savoie, forme avec Tignes le domaine skiable Espace Killy, l'un des plus étendus des Alpes françaises.",
      "Cette liaison vers l'Espace Killy est traitée comme un trajet longue distance : le tarif dépend de la distance réelle et vous est communiqué par KDRIVE avant votre départ.",
    ],
    quartiersTitle: "Repères à Val d'Isère",
    quartiers: [
      { title: "Centre du village", body: "Cœur historique de la station." },
      { title: "La Daille", body: "Secteur d'accès aux pistes, à l'entrée de la station." },
    ],
    casUsageTitle: "Motifs de déplacement courants",
    casUsageItems: skiCasUsage,
    frequentTrips: [
      { title: "Lyon → Val d'Isère", body: "Trajet direct depuis Lyon." },
      { title: "Aéroport Lyon-Saint Exupéry → Val d'Isère", body: "Transfert depuis l'aéroport en début de séjour.", href: "/transfert-aeroport" },
      { title: "Val d'Isère → Tignes", body: "Les deux stations forment le domaine Espace Killy.", href: "/transfert-lyon-tignes" },
    ],
    faq: skiFaq("Val d'Isère"),
    neighborLinksTitle: "Autres stations de l'Espace Killy",
    neighborLinks: [
      { href: "/transfert-lyon-tignes", label: "Lyon – Tignes" },
      { href: "/transfert-lyon-les-arcs", label: "Lyon – Les Arcs" },
    ],
    pillarLinksTitle: "Poursuivre votre réservation",
    pillarLinks: skiPillarLinks,
    sources: ["Val d'Isère / domaine Espace Killy (avec Tignes) : vérifié par recherche web le 2026-09-10."],
  },
  {
    slug: "transfert-lyon-les-deux-alpes",
    family: "ski-station",
    editorialStatus: "needsEnrichment",
    title: "Transfert Lyon – Les Deux Alpes | Chauffeur privé | KDRIVE",
    metaDescription: "Transfert avec chauffeur privé entre Lyon et Les Deux Alpes : tarif calculé sur la distance réelle, confirmé avant votre départ.",
    eyebrow: "Transfert ski",
    h1: "Transfert Lyon – Les Deux Alpes",
    breadcrumbParent: { label: "Stations de ski", href: "/transfert-stations-ski-depuis-lyon" },
    heroImage: "/images/hero-longues-distances.jpg",
    heroLead: "Un transfert avec chauffeur privé entre Lyon et Les Deux Alpes, sur réservation à l'avance.",
    presentationTitle: "Les Deux Alpes, dans le massif de l'Oisans",
    presentationBody: [
      "Les Deux Alpes, en Isère, se situe dans le massif de l'Oisans, plus proche de Grenoble que les stations de Savoie. La station est connue pour son glacier accessible en été comme en hiver.",
      "Ce trajet vers l'Oisans est plus court que vers les stations de Savoie, mais reste traité comme une longue distance : le tarif dépend de la distance réelle et vous est confirmé avant le départ.",
    ],
    quartiersTitle: "Repères aux Deux Alpes",
    quartiers: [
      { title: "Les Deux Alpes 1650", body: "Secteur principal de la station." },
      { title: "Glacier du Mont-de-Lans", body: "Secteur d'altitude accessible en saison." },
    ],
    casUsageTitle: "Motifs de déplacement courants",
    casUsageItems: skiCasUsage,
    frequentTrips: [
      { title: "Lyon → Les Deux Alpes", body: "Trajet direct depuis Lyon, via l'Isère." },
      { title: "Aéroport Lyon-Saint Exupéry → Les Deux Alpes", body: "Transfert depuis l'aéroport en début de séjour.", href: "/transfert-aeroport" },
      { title: "Les Deux Alpes → Alpe d'Huez", body: "Deux stations du massif de l'Oisans.", href: "/transfert-lyon-alpe-dhuez" },
    ],
    faq: skiFaq("Les Deux Alpes"),
    neighborLinksTitle: "Autres stations de l'Oisans",
    neighborLinks: [
      { href: "/transfert-lyon-alpe-dhuez", label: "Lyon – Alpe d'Huez" },
      { href: "/vtc-lyon-grenoble", label: "Lyon – Grenoble" },
    ],
    pillarLinksTitle: "Poursuivre votre réservation",
    pillarLinks: skiPillarLinks,
    sources: ["Les Deux Alpes / massif de l'Oisans / Isère : vérifié par recherche web le 2026-09-10."],
  },
  {
    slug: "transfert-lyon-alpe-dhuez",
    family: "ski-station",
    editorialStatus: "needsEnrichment",
    title: "Transfert Lyon – Alpe d'Huez | Chauffeur privé | KDRIVE",
    metaDescription: "Transfert avec chauffeur privé entre Lyon et l'Alpe d'Huez : tarif calculé sur la distance réelle, confirmé avant votre départ.",
    eyebrow: "Transfert ski",
    h1: "Transfert Lyon – Alpe d'Huez",
    breadcrumbParent: { label: "Stations de ski", href: "/transfert-stations-ski-depuis-lyon" },
    heroImage: "/images/hero-longues-distances.jpg",
    heroLead: "Un transfert avec chauffeur privé entre Lyon et l'Alpe d'Huez, sur réservation à l'avance.",
    presentationTitle: "L'Alpe d'Huez, sur la commune de Huez, en Isère",
    presentationBody: [
      "L'Alpe d'Huez, rattachée à la commune de Huez en Isère, est une station du massif de l'Oisans connue notamment pour sa route d'accès en lacets, également empruntée par le Tour de France.",
      "Comme pour les autres stations de l'Oisans, ce trajet est traité comme une longue distance : le tarif dépend de la distance réelle parcourue et vous est confirmé par KDRIVE avant le départ.",
    ],
    quartiersTitle: "Repères à l'Alpe d'Huez",
    quartiers: [
      { title: "Centre station", body: "Cœur de l'Alpe d'Huez, au pied des pistes." },
    ],
    casUsageTitle: "Motifs de déplacement courants",
    casUsageItems: skiCasUsage,
    frequentTrips: [
      { title: "Lyon → Alpe d'Huez", body: "Trajet direct depuis Lyon, via l'Isère." },
      { title: "Aéroport Lyon-Saint Exupéry → Alpe d'Huez", body: "Transfert depuis l'aéroport en début de séjour.", href: "/transfert-aeroport" },
      { title: "Alpe d'Huez → Les Deux Alpes", body: "Deux stations du massif de l'Oisans.", href: "/transfert-lyon-les-deux-alpes" },
    ],
    faq: skiFaq("l'Alpe d'Huez"),
    neighborLinksTitle: "Autres stations de l'Oisans",
    neighborLinks: [
      { href: "/transfert-lyon-les-deux-alpes", label: "Lyon – Les Deux Alpes" },
      { href: "/vtc-lyon-grenoble", label: "Lyon – Grenoble" },
    ],
    pillarLinksTitle: "Poursuivre votre réservation",
    pillarLinks: skiPillarLinks,
    sources: ["Alpe d'Huez / commune de Huez / massif de l'Oisans : vérifié par recherche web le 2026-09-10."],
  },
  {
    slug: "transfert-lyon-chamonix",
    family: "ski-station",
    editorialStatus: "needsEnrichment",
    title: "Transfert Lyon – Chamonix | Chauffeur privé | KDRIVE",
    metaDescription: "Transfert avec chauffeur privé entre Lyon et Chamonix-Mont-Blanc : tarif calculé sur la distance réelle, confirmé avant votre départ.",
    eyebrow: "Transfert ski",
    h1: "Transfert Lyon – Chamonix",
    breadcrumbParent: { label: "Stations de ski", href: "/transfert-stations-ski-depuis-lyon" },
    heroImage: "/images/hero-longues-distances.jpg",
    heroLead: "Un transfert avec chauffeur privé entre Lyon et Chamonix-Mont-Blanc, sur réservation à l'avance.",
    presentationTitle: "Chamonix-Mont-Blanc, au pied du plus haut sommet des Alpes",
    presentationBody: [
      "Chamonix-Mont-Blanc, en Haute-Savoie, est une station internationalement connue, au pied du mont Blanc. Le secteur regroupe plusieurs domaines skiables distincts (Grands Montets, Brévent-Flégère, etc.).",
      "Précisez le village de la vallée (Chamonix centre, Argentière…) lors de la réservation ; le tarif de ce trajet longue distance est calculé sur la distance réelle et confirmé avant votre départ.",
    ],
    quartiersTitle: "Repères à Chamonix",
    quartiers: [
      { title: "Chamonix centre", body: "Cœur de la vallée, au pied du mont Blanc." },
      { title: "Argentière", body: "Village de la vallée, proche du domaine des Grands Montets." },
    ],
    casUsageTitle: "Motifs de déplacement courants",
    casUsageItems: skiCasUsage,
    frequentTrips: [
      { title: "Lyon → Chamonix", body: "Trajet direct depuis Lyon." },
      { title: "Aéroport Lyon-Saint Exupéry → Chamonix", body: "Transfert depuis l'aéroport en début de séjour.", href: "/transfert-aeroport" },
      { title: "Chamonix → Megève", body: "Deux stations de la Haute-Savoie.", href: "/transfert-lyon-megeve" },
    ],
    faq: skiFaq("Chamonix"),
    neighborLinksTitle: "Autres stations de Haute-Savoie",
    neighborLinks: [
      { href: "/transfert-lyon-megeve", label: "Lyon – Megève" },
      { href: "/transfert-lyon-annecy", label: "Lyon – Annecy" },
    ],
    pillarLinksTitle: "Poursuivre votre réservation",
    pillarLinks: skiPillarLinks,
    sources: ["Chamonix-Mont-Blanc / Haute-Savoie : connaissance publique largement établie."],
  },
  {
    slug: "transfert-lyon-megeve",
    family: "ski-station",
    editorialStatus: "needsEnrichment",
    title: "Transfert Lyon – Megève | Chauffeur privé | KDRIVE",
    metaDescription: "Transfert avec chauffeur privé entre Lyon et Megève : tarif calculé sur la distance réelle, confirmé avant votre départ.",
    eyebrow: "Transfert ski",
    h1: "Transfert Lyon – Megève",
    breadcrumbParent: { label: "Stations de ski", href: "/transfert-stations-ski-depuis-lyon" },
    heroImage: "/images/hero-longues-distances.jpg",
    heroLead: "Un transfert avec chauffeur privé entre Lyon et Megève, sur réservation à l'avance.",
    presentationTitle: "Megève, station de Haute-Savoie",
    presentationBody: [
      "Megève, en Haute-Savoie, est une station de ski et de villégiature reconnue, à proximité de Chamonix et de la frontière suisse.",
      "Ce trajet vers Megève est traité comme une longue distance classique : le tarif dépend de la distance réelle et vous est communiqué par KDRIVE avant le départ.",
    ],
    quartiersTitle: "Repères à Megève",
    quartiers: [
      { title: "Centre village", body: "Cœur historique de la station de Megève." },
    ],
    casUsageTitle: "Motifs de déplacement courants",
    casUsageItems: skiCasUsage,
    frequentTrips: [
      { title: "Lyon → Megève", body: "Trajet direct depuis Lyon." },
      { title: "Aéroport Lyon-Saint Exupéry → Megève", body: "Transfert depuis l'aéroport en début de séjour.", href: "/transfert-aeroport" },
      { title: "Megève → Chamonix", body: "Deux stations de la Haute-Savoie.", href: "/transfert-lyon-chamonix" },
    ],
    faq: skiFaq("Megève"),
    neighborLinksTitle: "Autres stations de Haute-Savoie",
    neighborLinks: [
      { href: "/transfert-lyon-chamonix", label: "Lyon – Chamonix" },
      { href: "/transfert-lyon-geneve", label: "Lyon – Genève" },
    ],
    pillarLinksTitle: "Poursuivre votre réservation",
    pillarLinks: skiPillarLinks,
    sources: ["Megève / Haute-Savoie : connaissance publique largement établie."],
  },
];
